; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_sonic_the_hedgehog_w_rev01_sega_genesis:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw 0 ;@song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env1, @env2, @env0 ; 00 : EPSM Custom 1
	dw @env4, @env2
	dw @instrument_epsm_extra_patch0
	db $3a,$c0,$51,$7f
	dw @env1, @env2, @env0 ; 01 : EPSM Custom 2
	dw @env4, @env2
	dw @instrument_epsm_extra_patch1
	db $20,$c0,$36,$7f
	dw @env1, @env2, @env0 ; 02 : EPSM Custom 3
	dw @env4, @env2
	dw @instrument_epsm_extra_patch2
	db $14,$c0,$25,$24+4
	dw @env1, @env2, @env0 ; 03 : EPSM Custom 4
	dw @env4, @env2
	dw @instrument_epsm_extra_patch3
	db $14,$c0,$25,$7f
	dw @env1, @env2, @env0 ; 04 : EPSM Custom 6
	dw @env4, @env2
	dw @instrument_epsm_extra_patch4
	db $14,$c0,$25,$24+4
	dw @env1, @env2, @env0 ; 05 : EPSM Custom 7
	dw @env4, @env2
	dw @instrument_epsm_extra_patch5
	db $14,$c0,$25,$24+4
	dw @env1, @env2, @env0 ; 06 : EPSM Custom 8
	dw @env4, @env2
	dw @instrument_epsm_extra_patch6
	db $14,$c0,$25,$24+4
	dw @env1, @env2, @env0 ; 07 : EPSM Custom 9
	dw @env4, @env2
	dw @instrument_epsm_extra_patch7
	db $14,$c0,$25,$24+4
	dw @env1, @env2, @env0 ; 08 : EPSM Custom 10
	dw @env4, @env2
	dw @instrument_epsm_extra_patch8
	db $14,$c0,$25,$24+4
	dw @env1, @env2, @env0 ; 09 : EPSM Custom 11
	dw @env4, @env2
	dw @instrument_epsm_extra_patch9
	db $14,$c0,$25,$24+4

@instrument_epsm_extra_patch0:
	db $1e,$1f,$00,$0f,$00,$08,$7f+0,$1e,$1f,$00,$0f,$00,$51,$7f+0,$1e,$1f,$00,$0f,$00,$02,$7f+0,$10,$0f,$02,$1f,$00,$00
@instrument_epsm_extra_patch1:
	db $df,$07,$07,$2f,$00,$35,$7f+0,$df,$06,$06,$1f,$00,$30,$7f+0,$9f,$09,$06,$1f,$00,$31,$7f+0,$9f,$06,$08,$ff,$00,$00
@instrument_epsm_extra_patch2:
	db $1f,$15,$0b,$0f,$00,$33,$0b+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$06+4,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$15,$0b,$0f,$00,$33,$7f+0,$1f,$18,$08,$9f,$00,$36,$7f+0,$1f,$1c,$0d,$8f,$00,$11,$7f+0,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch4:
	db $1f,$15,$0b,$0f,$00,$33,$0e+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$0b+4,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch5:
	db $1f,$15,$0b,$0f,$00,$33,$13+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$10+4,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch6:
	db $1f,$15,$0b,$0f,$00,$33,$18+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$15+4,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch7:
	db $1f,$15,$0b,$0f,$00,$33,$1d+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$1a+4,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch8:
	db $1f,$15,$0b,$0f,$00,$33,$22+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$1f+4,$1f,$13,$09,$0f,$00,$00
@instrument_epsm_extra_patch9:
	db $1f,$15,$0b,$0f,$00,$33,$27+4,$1f,$18,$08,$9f,$00,$36,$0a+4,$1f,$1c,$0d,$8f,$00,$11,$24+4,$1f,$13,$09,$0f,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$cf,$7f,$00,$02
@env2:
	db $c0,$7f,$00,$01
@env3:
	db $7f,$00,$00
@env4:
	db $c8,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $ff, $ff, $ff, $42
;	dw @song0ch0loop

@song0ch8:
@song0ch8loop:
	db $83, $80, $3a, $ff, $ff, $ff, $cb, $00, $ab, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $83, $82, $0a, $ff, $ff, $ff, $cb, $00, $ab, $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $81, $84, $31, $8b, $35, $8b, $38, $8b, $4d, $fc, $33, $8b, $4d, $04, $36, $8b, $4d, $00, $3a, $8b, $35, $8b, $38, $8b
	db $4d, $b0, $3d, $8b, $4d, $04, $36, $8b, $4d, $00, $3a, $8b, $3d, $8b, $38, $8b, $4d, $b0, $3d, $8b, $4d, $f8, $3f, $8b
	db $4d, $00, $88, $38, $8b, $4d, $b0, $3d, $8b, $4d, $f8, $3f, $8b, $4d, $00, $8a, $38, $8b, $4d, $b0, $3d, $8b, $4d, $f8
	db $3f, $8b, $4d, $00, $8c, $38, $8b, $4d, $b0, $3d, $8b, $4d, $f8, $3f, $8b, $4d, $00, $8e, $38, $8b, $4d, $b0, $3d, $8b
	db $4d, $f8, $3f, $8b, $4d, $00, $90, $38, $8b, $4d, $b0, $3d, $8b, $4d, $f8, $3f, $8b, $4d, $00, $92, $38, $8b, $4d, $b0
	db $3d, $8b, $4d, $f8, $3f, $8d, $00, $ab ; , $42
	db $5B ; halt
	;dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $83, $4d, $b0, $86, $3d, $89, $4d, $00, $84, $35, $a7, $4d, $04, $36, $a7, $4d, $00, $38, $a7, $3a, $a7, $4d, $b0, $3d
	db $a7, $88, $3d, $a7, $8a, $3d, $a7, $8c, $3d, $a7, $8e, $3d, $a7, $90, $3d, $a7, $92, $3d, $9b, $00, $ab, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $81, $84, $31, $a7, $33, $a7, $35, $a7, $4d, $04, $36, $a7, $4d, $00, $38, $a7, $88, $38, $a7, $8a, $38, $a7, $8c, $38
	db $a7, $8e, $38, $a7, $90, $38, $a7, $92, $38, $a9, $00, $ab, $42
	dw @song0ch12loop

