; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_06_star_light_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 06. Star Light Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env5,@env6,@env8,@env0 ; 00 : Hi hat
	dw @env2,@env6,@env8,@env0 ; 01 : Longer Noise

@instruments_exp:
	dw @env7, @env6, @env0 ; 00 : 1 Fade
	dw @env10, @env6
	dw @instrument_epsm_extra_patch3
	db $04,$c0,$00,$20
	dw @env3, @env6, @env0 ; 01 : 1-Organ L
	dw @env10, @env6
	dw @instrument_epsm_extra_patch4
	db $04,$80,$72,$22
	dw @env3, @env6, @env0 ; 02 : 1-Organ R
	dw @env10, @env6
	dw @instrument_epsm_extra_patch5
	db $04,$40,$72,$22
	dw @env3, @env6, @env0 ; 03 : EPSM Custom 15
	dw @env10, @env6
	dw @instrument_epsm_extra_patch6
	db $3c,$c0,$31,$1a
	dw @env3, @env6, @env0 ; 04 : EPSM Star
	dw @env10, @env6
	dw @instrument_epsm_extra_patch7
	db $34,$c0,$33,$23
	dw @env3, @env6, @env0 ; 05 : EPSM Weird
	dw @env10, @env6
	dw @instrument_epsm_extra_patch8
	db $3c,$c0,$38,$1e
	dw @env3, @env6, @env9 ; 06 : Trumpet
	dw @env10, @env6
	dw @instrument_epsm_extra_patch9
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch4:
	db $5f,$04,$00,$57,$00,$72,$1e,$1f,$80,$03,$07,$00,$02,$22,$1f,$00,$00,$57,$00,$02,$1e,$19,$85,$03,$07,$00,$08
@instrument_epsm_extra_patch5:
	db $5f,$04,$00,$57,$00,$72,$1e,$1f,$80,$03,$07,$00,$02,$22,$1f,$00,$00,$57,$00,$02,$1e,$19,$85,$03,$07,$00,$08
@instrument_epsm_extra_patch6:
	db $52,$08,$04,$1f,$00,$52,$15,$53,$00,$00,$0f,$00,$50,$16,$52,$08,$04,$1f,$00,$30,$15,$53,$00,$00,$0f,$00,$00
@instrument_epsm_extra_patch7:
	db $5b,$04,$00,$ff,$00,$41,$10,$9f,$07,$00,$ff,$00,$7e,$29,$5f,$07,$00,$ef,$00,$74,$17,$1f,$08,$00,$ff,$00,$00
@instrument_epsm_extra_patch8:
	db $10,$02,$03,$2f,$00,$74,$20,$10,$07,$09,$2f,$00,$76,$1e,$10,$04,$03,$2f,$00,$33,$20,$10,$07,$09,$2f,$00,$00
@instrument_epsm_extra_patch9:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c7,$c7,$c6,$c3,$c3,$c2,$c1,$00,$07
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env6:
	db $c0,$7f,$00,$01
@env7:
	db $00,$cd,$02,$cc,$02,$cb,$02,$ca,$00,$07
@env8:
	db $7f,$00,$00
@env9:
	db $00,$bd,$be,$c0,$00,$03
@env10:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $a7
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47
;	db $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf
;	db $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $a7
;@song0ch1loop:
;@song0ref67:
;	db $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf
;	db $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $a7
;@song0ch2loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch2loop
@song0ch3:
	db $ef, $77, $80, $2f, $8b, $2f, $8b, $82, $2f, $99
@song0ch3loop:
	db $77
@song0ref135:
	db $80, $2f, $8b, $2f, $8b, $82, $2f, $99, $80, $2f, $8b, $2f, $8b, $82, $2f, $99, $80, $2f, $8b, $2f, $8b, $82, $2f, $99
	db $80, $2f, $8b, $2f, $8b, $82, $2f, $99
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $41, $18
	dw @song0ref135
	db $42
	dw @song0ch3loop
@song0ch4:
	db $ff, $a7
@song0ch4loop:
@song0ref236:
	db $04, $99, $00, $99, $04, $99, $00, $99, $04, $99, $00, $99, $04, $99, $00, $99, $04, $99, $00, $99, $04, $99, $00, $99
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $41, $18
	dw @song0ref236
	db $04, $99, $00, $99, $04, $99, $00, $99, $04, $99, $00, $99, $04, $99, $00, $99, $42
	dw @song0ch4loop
@song0ch5:
	db $ff, $a7
@song0ch5loop:
	db $80
@song0ref322:
	db $2c, $99, $00, $8b, $2c, $8b, $00, $99, $2c, $ff, $89, $2a, $99, $00, $8b, $2a, $8b, $00, $99, $29, $ff, $89, $2e, $a7
	db $2c, $a7, $2a, $99, $2e, $a7, $2c, $a7, $2a, $99, $2e, $a7, $2c, $a7, $2a, $ff, $89, $2a, $99, $00, $8b, $2a, $8b, $00
	db $99, $2a, $ff, $89, $2d, $99, $00, $8b, $2d, $8b, $00, $99, $2d, $ff, $89, $2c, $99, $00, $8b, $2c, $8b, $00, $99, $2c
	db $ed, $30, $a7, $00, $8b, $30, $8b, $00, $8b, $2e, $99, $00, $99, $2c, $8b, $00, $8b, $2a, $d1
	db $41, $3f
	dw @song0ref322
@song0ref416:
	db $00, $99, $30, $8f, $5a, $87, $00, $8b, $30, $8f, $5a, $87, $00, $8b, $30, $8f, $5a, $87, $00, $8b, $30, $8f, $5a, $87
	db $00, $8b, $30, $85, $5a, $83, $30, $8b, $00, $99, $31, $8f, $5a, $87, $00, $8b, $31, $8f, $5a, $87, $00, $8b, $31, $8f
	db $5a, $87, $00, $8b, $31, $8f, $5a, $87, $00, $8b, $31, $85, $5a, $83, $31, $8b, $00, $99, $33, $8f, $5a, $87, $00, $8b
	db $33, $8f, $5a, $87, $00, $8b, $33, $8f, $5a, $87, $00, $8b, $33, $8f, $5a, $87, $00, $8b, $33, $85, $5a, $83, $33, $8b
	db $00, $99, $35, $8f, $5a, $87, $00, $8b, $35, $8f, $5a, $87, $00, $8b, $35, $8f, $5a, $87, $00, $8b, $33, $8f, $5a, $87
	db $00, $8b, $30, $8f, $5a, $87
	db $41, $61
	dw @song0ref416
	db $b5, $2e, $ff, $a5, $42
	dw @song0ch5loop
@song0ch6:
	db $ff, $a7
@song0ch6loop:
	db $80
@song0ref556:
	db $29, $99, $00, $8b, $29, $8b, $00, $99, $29, $ff, $89, $27, $99, $00, $8b, $27, $8b, $00, $99, $26, $ff, $89, $2a, $a7
	db $29, $a7, $27, $99, $2a, $a7, $29, $a7, $27, $99, $2a, $a7, $29, $a7, $27, $ff, $89, $27, $99, $00, $8b, $27, $8b, $00
	db $99, $27, $ff, $89, $2a, $99, $00, $8b, $2a, $8b, $00, $99, $2a, $ff, $89, $29, $99, $00, $8b, $29, $8b, $00, $99, $29
	db $ed, $2c, $a7, $00, $8b, $2c, $8b, $00, $8b, $2a, $99, $00, $99, $29, $8b, $00, $8b, $27, $d1
	db $41, $3f
	dw @song0ref556
@song0ref650:
	db $00, $99, $2c, $8f, $5a, $87, $00, $8b, $2c, $8f, $5a, $87, $00, $8b, $2c, $8f, $5a, $87, $00, $8b, $2c, $8f, $5a, $87
	db $00, $8b, $2c, $85, $5a, $83, $2c, $8b, $00, $99, $2e, $8f, $5a, $87, $00, $8b, $2e, $8f, $5a, $87, $00, $8b, $2e, $8f
	db $5a, $87, $00, $8b, $2e, $8f, $5a, $87, $00, $8b, $2e, $85, $5a, $83, $2e, $8b
	db $41, $34
	dw @song0ref416
	db $30, $8f, $5a, $87, $00, $8b, $2c, $8f, $5a, $87
	db $41, $40
	dw @song0ref650
	db $41, $21
	dw @song0ref416
	db $b5, $2a, $ff, $a5, $42
	dw @song0ch6loop
;@song0ch7:
;	db $ff, $a7
;@song0ch7loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch7loop
@song0ch8:
	db $88, $20, $b5, $22, $b5, $2c, $b5
@song0ch8loop:
@song0ref757:
	db $29, $ff, $c1, $29, $8b, $2a, $8b, $2c, $a7, $2e, $a7, $2f, $99, $2e, $b5, $2c, $b5, $2a, $ff, $89, $2a, $99, $29, $99
	db $2a, $ff, $89, $27, $b5, $29, $b5, $2a, $ff, $c1, $27, $8b, $29, $8b, $2a, $a7, $2c, $a7, $2d, $99, $2c, $b5, $2a, $b5
	db $29, $ff, $89, $2a, $99, $29, $99, $27, $d1, $20, $b5, $22, $b5, $2c, $b5
	db $41, $31
	dw @song0ref757
	db $d1, $00, $b5, $35, $99, $31, $ff, $89, $00, $ff, $89, $ff, $8b, $35, $99, $31, $ff, $89, $00, $ff, $89, $ff, $8b, $35
	db $99, $31, $ff, $89, $00, $ff, $89, $ff, $8b, $35, $99, $31, $ed, $20, $b5, $22, $b5, $2c, $b5, $42
	dw @song0ch8loop
@song0ch9:
	db $ff, $a7
@song0ch9loop:
	db $86, $19, $99, $00, $8b, $19, $8b, $00, $99, $19, $df, $00, $8b, $19, $85, $00, $83, $19, $83, $00, $85
@song0ref893:
	db $17, $99, $00, $8b, $17, $8b, $00, $99, $16, $df, $00, $8b, $16, $85, $00, $83, $16, $83, $00, $85, $1b, $99, $00, $8b
	db $1b, $8b, $00, $99, $1b, $85, $00, $83, $1b, $83, $00, $85, $1a, $99, $00, $8b, $1a, $8b, $00, $99, $1a, $85, $00, $83
	db $1a, $83, $00, $85, $19, $99, $00, $8b, $19, $8b, $00, $99, $19, $85, $00, $83, $19, $83, $00, $85, $18, $99, $00, $8b
	db $18, $8b, $00, $99, $18, $85, $00, $83, $18, $83, $00, $85, $14, $99, $00, $8b, $14, $8b, $00, $99, $14, $df, $00, $8b
	db $14, $85, $00, $83, $14, $83, $00, $85, $18, $99, $00, $8b, $18, $8b, $00, $99, $18, $df, $00, $8b, $18, $85, $00, $83
	db $18
@song0ref1014:
	db $83, $00, $85, $19, $99, $00, $8b, $19, $8b, $00, $99, $19, $df, $00, $8b, $19, $85, $00, $83, $19, $83, $00, $85, $1b
	db $99, $00, $8b, $1b, $8b, $00, $99, $14, $df, $00, $8b, $1b, $85, $00, $83, $14
	db $41, $17
	dw @song0ref1014
	db $41, $74
	dw @song0ref893
	db $1b, $85, $00, $83, $18
@song0ref1065:
	db $83, $00, $85, $19, $99, $00, $8b, $19, $8b, $00, $99, $19, $df, $00, $8b, $14, $85, $00, $83, $19, $83, $00, $85, $1b
	db $99, $00, $8b, $1b, $8b, $00, $99, $1b, $df, $00, $8b, $14, $85, $00, $83, $1b, $83, $00, $85, $1d, $99, $00, $8b, $1d
	db $8b, $00, $99, $1d, $df, $00, $8b, $19, $85, $00, $83, $1d, $83, $00, $85, $1e, $99, $00, $8b, $1e, $8b, $00, $99, $1e
	db $df, $00, $8b, $20, $85, $00, $83, $1e
	db $41, $37
	dw @song0ref1065
	db $1d, $85, $00, $83, $1e, $83, $00, $85, $20, $8b, $00, $a7, $14, $ff, $a5, $42
	dw @song0ch9loop
@song0ch10:
	db $ff, $a7
@song0ch10loop:
	db $82
@song0ref1170:
	db $20, $99, $00, $8b, $20, $8b, $00, $99, $20, $ff, $89, $1e, $99, $00, $8b, $1e, $8b, $00, $99, $1d, $ff, $89, $22, $a7
	db $20, $a7, $1e, $99, $22, $a7, $20, $a7, $1e, $99, $22, $a7, $20, $a7, $1e, $ff, $89, $1e, $99, $00, $8b, $1e, $8b, $00
	db $99, $1e, $ff, $89, $21, $99, $00, $8b, $21, $8b, $00, $99, $21, $ff, $89, $20, $99, $00, $8b, $20, $8b, $00, $99, $20
	db $ed, $24, $a7, $00, $8b, $24, $8b, $00, $8b, $22, $99, $00, $99, $20, $8b, $00, $8b, $1e, $d1
	db $41, $3f
	dw @song0ref1170
@song0ref1264:
	db $00, $99, $24, $8f, $5a, $87, $00, $8b, $24, $8f, $5a, $87, $00, $8b, $24, $8f, $5a, $87, $00, $8b, $24, $8f, $5a, $87
	db $00, $8b, $24, $85, $5a, $83, $24, $8b, $00, $99, $25, $8f, $5a, $87, $00, $8b, $25, $8f, $5a, $87, $00, $8b, $25, $8f
	db $5a, $87, $00, $8b, $25, $8f, $5a, $87, $00, $8b, $25, $85, $5a, $83, $25, $8b, $00, $99, $27, $8f, $5a, $87, $00, $8b
	db $27, $8f, $5a, $87, $00, $8b, $27, $8f, $5a, $87, $00, $8b, $27, $8f, $5a, $87, $00, $8b, $27, $85, $5a, $83, $27, $8b
	db $00, $99, $29, $8f, $5a, $87, $00, $8b, $29, $8f, $5a, $87, $00, $8b, $29, $8f, $5a, $87, $00, $8b, $27, $8f, $5a, $87
	db $00, $8b, $24, $8f, $5a, $87
	db $41, $61
	dw @song0ref1264
	db $b5, $22, $ff, $a5, $42
	dw @song0ch10loop
@song0ch11:
	db $ff, $a7
@song0ch11loop:
	db $84
@song0ref1404:
	db $1d, $99, $00, $8b, $1d, $8b, $00, $99, $1d, $ff, $89, $1b, $99, $00, $8b, $1b, $8b, $00, $99, $1a, $ff, $89, $1e, $a7
	db $1d, $a7, $1b, $99, $1e, $a7, $1d, $a7, $1b, $99, $1e, $a7, $1d, $a7, $1b, $ff, $89, $1b, $99, $00, $8b, $1b, $8b, $00
	db $99, $1b, $ff, $89, $1e, $99, $00, $8b, $1e, $8b, $00, $99, $1e, $ff, $89, $1d, $99, $00, $8b, $1d, $8b, $00, $99, $1d
	db $ed, $20, $a7, $00, $8b, $20, $8b, $00, $8b, $1e, $99, $00, $99, $1d, $8b, $00, $8b, $1b, $d1
	db $41, $3f
	dw @song0ref1404
@song0ref1498:
	db $00, $99, $20, $8f, $5a, $87, $00, $8b, $20, $8f, $5a, $87, $00, $8b, $20, $8f, $5a, $87, $00, $8b, $20, $8f, $5a, $87
	db $00, $8b, $20, $85, $5a, $83, $20, $8b, $00, $99, $22, $8f, $5a, $87, $00, $8b, $22, $8f, $5a, $87, $00, $8b, $22, $8f
	db $5a, $87, $00, $8b, $22, $8f, $5a, $87, $00, $8b, $22, $85, $5a, $83, $22, $8b
	db $41, $34
	dw @song0ref1264
	db $24, $8f, $5a, $87, $00, $8b, $20, $8f, $5a, $87
	db $41, $40
	dw @song0ref1498
	db $41, $21
	dw @song0ref1264
	db $b5, $1e, $ff, $a5, $42
	dw @song0ch11loop
@song0ch12:
	db $8a, $2c, $b5, $2e, $b5, $38, $b5
@song0ch12loop:
	db $8a
@song0ref1597:
	db $35, $ff, $c1, $35, $8b, $36, $8b, $38, $a7, $3a, $a7, $3b, $99, $3a, $b5, $38, $b5, $36, $ff, $89, $36, $99, $35, $99
	db $36, $ff, $89, $33, $b5, $35, $b5, $36, $ff, $c1, $33, $8b, $35, $8b, $36, $a7, $38, $a7, $39, $99, $38, $b5, $36, $b5
	db $35, $ff, $89, $36, $99, $35, $99, $33, $d1, $2c, $b5, $2e, $b5, $38, $b5
	db $41, $31
	dw @song0ref1597
	db $99, $8c
@song0ref1665:
	db $2c, $8b, $2e, $8b, $31, $87, $00, $81, $31, $8b, $00, $8b, $2e, $8b, $31, $87, $00, $81, $31, $8b, $00, $ed, $35, $99
	db $00, $99, $31, $99, $00, $99, $2e, $99, $31, $99, $2e, $99, $00, $99
	db $41, $18
	dw @song0ref1665
	db $36, $99, $35, $99, $36, $99, $38, $99, $00, $99, $31, $99, $00, $99
	db $41, $1f
	dw @song0ref1665
	db $85, $00, $83, $2e, $8b, $31, $99, $2e, $99, $00, $99
	db $41, $15
	dw @song0ref1665
	db $b5, $35, $8b, $36, $8b, $38, $8b, $00, $a7, $4f, $0a, $48, $49, $8b, $3d, $ff, $97, $42
	dw @song0ch12loop
;@song0ch13:
;	db $ff, $a7
;@song0ch13loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $a7
;@song0ch14loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $a7
;@song0ch15loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $a7
;@song0ch16loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $a7
;@song0ch17loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $a7
;@song0ch18loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $a7
;@song0ch19loop:
;	db $41, $2c
;	dw @song0ref67
;	db $42
;	dw @song0ch19loop
