; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_08b_special_stage_beta_s1_smsgg:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 08B. Special Stage Beta (S1 SMS/GG)

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw @song0ch2 ; triangle
	dw 0 ; @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ; @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw @song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env12,@env7,@env1,@env0 ; 00 : Lead

@instruments_exp:
	dw @env8, @env7, @env0 ; 00 : 1 Short Soft 1
	dw @env11, @env7
	dw @instrument_epsm_extra_patch2
	db $04,$c0,$00,$20
	dw @env4, @env7, @env3 ; 01 : 1-Synth Voice
	dw @env11, @env7
	dw @instrument_epsm_extra_patch3
	db $04,$c0,$72,$26
	dw @env4, @env7, @env0 ; 02 : Bass Slap
	dw @env11, @env7
	dw @instrument_epsm_extra_patch4
	db $08,$c0,$09,$25
	dw @env4, @env7, @env0 ; 03 : EPSM Custom 6
	dw @env11, @env7
	dw @instrument_epsm_extra_patch5
	db $3a,$c0,$01,$18
	dw @env4, @env7, @env0 ; 04 : Percusion Crash SSG-Env 2
	dw @env11, @env7
	dw @instrument_epsm_extra_patch6
	db $02,$c0,$48,$00
	dw @env4, @env5, @env0 ; 05 : Percusion Hi-Hat Fast
	dw @env11, @env7
	dw @instrument_epsm_extra_patch7
	db $3b,$c0,$7f,$00
	dw @env4, @env2, @env10 ; 06 : Percusion Snare 2
	dw @env11, @env7
	dw @instrument_epsm_extra_patch8
	db $3a,$c0,$01,$00
	dw @env4, @env7, @env0 ; 07 : Star
	dw @env11, @env7
	dw @instrument_epsm_extra_patch9
	db $0d,$c0,$33,$1e

@instrument_epsm_extra_patch2:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch3:
	db $5f,$02,$00,$51,$00,$72,$14,$1f,$80,$03,$03,$00,$12,$26,$1f,$04,$00,$51,$00,$12,$14,$1a,$8e,$03,$03,$00,$08
@instrument_epsm_extra_patch4:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch5:
	db $8e,$0e,$00,$1f,$00,$07,$28,$8e,$0e,$00,$ff,$00,$01,$27,$8d,$0e,$00,$1f,$00,$01,$0a,$53,$03,$00,$0f,$00,$00
@instrument_epsm_extra_patch6:
	db $5f,$80,$1f,$88,$08,$0f,$00,$df,$9f,$1f,$80,$08,$08,$00,$5f,$1f,$1f,$80,$0a,$71,$06,$1f,$8c,$0c,$08,$00,$00
@instrument_epsm_extra_patch7:
	db $1f,$80,$00,$88,$00,$5f,$00,$df,$9f,$1f,$f0,$0e,$6f,$00,$df,$1f,$1f,$00,$09,$71,$02,$1f,$13,$13,$08,$00,$00
@instrument_epsm_extra_patch8:
	db $9f,$00,$10,$00,$0b,$00,$00,$df,$80,$08,$08,$0f,$00,$00,$5f,$00,$08,$09,$0f,$00,$00,$1f,$10,$10,$08,$00,$00
@instrument_epsm_extra_patch9:
	db $1f,$08,$05,$f6,$00,$02,$19,$19,$0a,$00,$d6,$00,$74,$19,$19,$0a,$06,$26,$00,$71,$19,$19,$0c,$00,$26,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $c3,$c9,$c5,$c7,$c6,$00,$04
@env3:
	db $00,$c0,$1c,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env4:
	db $00,$cf,$7f,$00,$02
@env5:
	db $e8,$7f,$00,$00
@env6:
	db $bf,$bf,$c0,$00,$02
@env7:
	db $c0,$7f,$00,$01
@env8:
	db $00,$ce,$cf,$02,$ce,$ce,$cd,$cd,$cc,$00,$08
@env9:
	db $7f,$00,$00
@env10:
	db $80,$c0,$a8,$00,$01
@env11:
	db $c8,$7f,$00,$00
@env12:
	db $05,$c6,$cd,$00,$02,$cb,$c8,$c3,$c1,$00,$08

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid)
;@song0ref5:
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $41, $20
;	dw @song0ref5
;	db $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ch1loop:
;@song0ref60:
;	db $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
;	db $ff, $df, $ff, $df, $ff, $df, $ff, $df
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch1loop
@song0ch2:
@song0ch2loop:
	db $7b, $80
@song0ref101:
	db $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $20, $99, $2c, $99, $20, $99, $2c, $99
	db $20, $99, $2c, $99, $20, $99, $2c, $99
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
@song0ref142:
	db $1f, $99, $2b, $99, $1f, $99, $2b, $99, $1f, $99, $2b, $99, $1f, $99, $2b, $99, $18, $99, $24, $99, $18, $99, $24, $99
	db $18, $99, $24, $99, $18, $99, $24, $99, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29, $99
	db $22, $99, $2e, $99, $23, $99, $2f, $99, $24, $99, $30, $99, $26, $99, $32, $99
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $40
	dw @song0ref142
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $22, $99, $00, $ed, $22, $99, $22, $99
	db $22, $99, $42
	dw @song0ch2loop
;@song0ch3:
;@song0ch3loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref270:
	db $04, $99, $05, $99, $04, $99, $05, $99, $04, $99, $05, $99, $04, $99, $05, $99, $04, $99, $05, $99, $04, $99, $05, $99
	db $04, $99, $05, $99, $04, $99, $05, $99
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $41, $20
	dw @song0ref270
	db $42
	dw @song0ch4loop
;@song0ch5:
;@song0ch5loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch5loop
@song0ch6:
@song0ch6loop:
	db $7c
@song0ref362:
	db $00, $99, $82
@song0ref365:
	db $33, $8b, $00, $8b, $3f, $8b, $3a, $8b, $3e, $8b, $3f, $8b, $00, $ed, $b7, $3c, $8b, $00, $8b, $3a, $8b, $38, $8b, $00
	db $ed, $00, $99, $33, $8b, $00, $8b, $3f, $8b, $3a, $8b, $3e, $8b, $3f, $8b, $00, $ed, $ff, $df, $00, $99
	db $41, $2b
	dw @song0ref365
@song0ref413:
	db $26, $b5, $23, $b5, $24, $b5, $26, $b5, $24, $b5, $2b, $8b, $2c, $8b, $2b, $8b, $27, $a7, $29, $8b, $27, $99, $24, $a7
	db $29, $b5, $1d, $b5, $1f, $b5, $21, $b5, $22, $b5, $20, $b5, $1f, $8b, $20, $8b, $1f, $8b, $1d, $99, $1b, $8b, $1d, $99
	db $00, $99
	db $41, $2d
	dw @song0ref365
	db $41, $2b
	dw @song0ref365
	db $41, $31
	dw @song0ref413
	db $ff, $dd, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $b5, $80, $3c, $8b, $3b, $8b, $3a, $8b, $00, $ff, $dd
	db $42
	dw @song0ch6loop
@song0ch7:
@song0ch7loop:
	db $7b, $80
@song0ref502:
	db $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $14, $99, $20, $99, $14, $99, $20, $99
	db $14, $99, $20, $99, $14, $99, $20, $99
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
@song0ref543:
	db $13, $99, $1f, $99, $13, $99, $1f, $99, $13, $99, $1f, $99, $13, $99, $1f, $99, $18, $99, $24, $99, $18, $99, $24, $99
	db $18, $99, $24, $99, $18, $99, $24
@song0ref574:
	db $99, $11, $99, $1d, $99, $11, $99, $1d, $99, $11, $99, $1d, $99, $11, $99, $1d, $99, $16, $99, $22, $99, $17, $99, $23
	db $99, $18, $99, $24, $99, $1a, $99, $26, $99
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $40
	dw @song0ref543
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $16, $99, $00, $ed, $16, $99, $16, $99
	db $16, $99, $42
	dw @song0ch7loop
@song0ch8:
@song0ch8loop:
	db $7b, $86
@song0ref663:
	db $3a, $f5, $00, $91
@song0ref667:
	db $37, $8b, $35, $8b, $3a, $8b, $37, $8b, $3c, $8b, $3a, $8b, $33, $8b, $00, $8b, $33, $8b, $00, $8b, $33, $8b, $30, $99
	db $33, $8b, $00, $99, $30, $8b, $00, $8b, $33, $8b, $00, $8b, $35, $8b, $00, $8b, $3a, $ed, $00, $99, $37, $8b, $35, $8b
	db $3a, $8b, $37, $8b, $3c, $8b, $3a, $8b, $3f, $8b, $00, $a7, $3c, $8b, $00, $99, $3a, $8b, $38, $8b, $00, $99, $3c, $8b
	db $00, $99, $37, $8b, $00, $8b, $3a, $ed, $00, $99
	db $41, $40
	dw @song0ref667
@song0ref752:
	db $40, $4e, $8b, $00, $8b, $40, $4e, $8b, $40, $4d, $8b, $00, $8b, $3f, $8b, $3c, $8b, $00, $99, $9b, $37, $8b, $00, $8b
	db $38, $8b, $4f, $fc, $44, $43, $99, $34, $8b, $3b, $8b, $37, $8b, $3b, $8b, $37, $8b, $3c, $8b, $39, $8b, $3e, $8b, $3b
	db $8b, $3f, $8b, $00, $a7, $3e, $8b, $00, $99, $3c, $8b, $00, $8b, $3c, $8b, $00, $8b, $3e, $8b, $3c, $8b, $00, $8b, $37
	db $8b, $00, $8b, $9b, $35, $8b, $00, $8b, $37, $8b, $00, $8b, $35, $8b, $00, $8b, $3c, $8b, $00, $8b, $3c, $8b, $00, $8b
	db $3e, $8b, $00, $8b, $3c, $8b, $00, $8b, $3a, $ed, $00, $99, $3a, $8b, $00, $8b, $3c, $8b, $00, $8b, $3e, $8b, $00, $8b
	db $41, $56
	dw @song0ref663
	db $41, $40
	dw @song0ref667
	db $41, $72
	dw @song0ref752
@song0ref881:
	db $3f, $8b, $00, $8b, $3f, $8b, $00, $8b, $3f, $8b, $00, $b5, $40, $5e, $8b, $00, $8b, $40, $5e, $8b, $40, $5e, $8b, $00
	db $8b, $40, $5e, $8b, $00, $8b, $3f, $8b, $00, $8b, $3f, $8b, $00, $8b, $3f, $8b, $00, $99, $40, $54, $8b, $00, $8b, $40
	db $58, $8b, $00, $8b, $40, $58, $8b, $40, $58, $8b, $00, $8b, $40, $54, $8b, $00, $8b
	db $41, $38
	dw @song0ref881
	db $41, $38
	dw @song0ref881
	db $3f, $8b, $00, $8b, $3f, $8b, $00, $8b, $3f, $8b, $00, $b5, $40, $5e, $8b, $00, $8b, $40, $5e, $8b, $40, $5e, $8b, $00
	db $8b, $40, $5e, $8b, $00, $8b, $9b, $40, $57, $99, $40, $54, $99, $40, $51, $99, $00, $8b, $33, $99, $33, $8b, $33, $8b
	db $00, $8b, $35, $99, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $7a
	db $41, $2f
	dw @song0ref362
	db $41, $2b
	dw @song0ref365
	db $41, $32
	dw @song0ref413
	db $41, $2d
	dw @song0ref365
	db $41, $2b
	dw @song0ref365
	db $41, $31
	dw @song0ref413
	db $ff, $dd, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $b5, $80, $3c, $8b, $3b, $8b, $3a, $8b, $00, $ff, $dd
	db $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $8e
	db $41, $31
	dw @song0ref413
	db $ff, $dd, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	db $41, $31
	dw @song0ref413
	db $ff, $dd, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $42
	dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $7a, $84
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $40
	dw @song0ref142
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $40
	dw @song0ref142
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $41, $20
	dw @song0ref101
	db $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $22, $99, $00, $ed, $22, $99, $22, $99
	db $22, $99, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $7b, $84
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
@song0ref1199:
	db $13, $99, $1f, $99, $13, $99, $1f, $99, $13, $99, $1f, $99, $13, $99, $1f, $99, $0c, $99, $18, $99, $0c, $99, $18, $99
	db $0c, $99, $18, $99, $0c, $99, $18
	db $41, $21
	dw @song0ref574
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $1f
	dw @song0ref1199
	db $41, $21
	dw @song0ref574
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $41, $20
	dw @song0ref502
	db $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $16, $99, $00, $ed, $16, $99, $16, $99
	db $16, $99, $42
	dw @song0ch12loop
;@song0ch13:
;@song0ch13loop:
;	db $7a, $8a
;@song0ref1292:
;	db $27, $8b, $27, $8b, $8c, $27, $8b, $8a, $27, $8b, $27, $8b, $27, $8b, $8c, $27, $8b, $8a, $27, $8b, $27, $8b, $27, $8b
;	db $8c, $27, $8b, $8a, $27, $8b, $27, $8b, $27, $8b, $8c, $27, $8b, $8a, $27, $8b
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $41, $20
;	dw @song0ref1292
;	db $88, $27, $c3, $00, $b5, $8c, $27, $99, $27, $8b, $27, $8b, $00, $8b, $27, $99, $42
;	dw @song0ch13loop
;@song0ch14:
;@song0ch14loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;@song0ch15loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;@song0ch16loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;@song0ch17loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;@song0ch18loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;@song0ch19loop:
;	db $41, $20
;	dw @song0ref60
;	db $41, $20
;	dw @song0ref60
;	db $42
;	dw @song0ch19loop
