; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_16_continue:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 16. Continue?

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env4,@env5,@env6,@env0 ; 00 : Hi hat

@instruments_exp:
	dw @env2, @env5, @env0 ; 00 : EPSM Custom 33
	dw @env8, @env5
	dw @instrument_epsm_extra_patch2
	db $3a,$c0,$51,$18
	dw @env2, @env5, @env7 ; 01 : Trumpet
	dw @env8, @env5
	dw @instrument_epsm_extra_patch3
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch2:
	db $1e,$1f,$00,$0f,$00,$08,$24,$1e,$1f,$00,$0f,$00,$51,$22,$1e,$1f,$00,$0f,$00,$02,$0f,$10,$0f,$02,$1f,$00,$00
@instrument_epsm_extra_patch3:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $bf,$bf,$c0,$00,$02
@env4:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $00,$bd,$be,$c0,$00,$03
@env8:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $bf
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ref22:
;	db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $41, $0b
;	dw @song0ref22
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
@song0ch3:
	db $ff, $80
@song0ref48:
	db $0f, $9d, $0f, $9d, $0f, $9d, $0f, $9d, $0f, $9d, $0f, $9d
	db $41, $0c
	dw @song0ref48
	db $41, $0c
	dw @song0ref48
	db $41, $0c
	dw @song0ref48
	db $0f, $9d, $0f, $9d, $0f, $9d, $0f, $9d, $0f, $9d, $00, $dd, $ff, $bf
@song0ch3loop:
	db $00, $42
	dw @song0ch3loop
@song0ch4:
	db $ff
@song0ref89:
	db $04, $9d, $05, $9d, $04, $9d, $05, $9d, $04, $9d, $05, $9d
	db $41, $0c
	dw @song0ref89
	db $41, $0c
	dw @song0ref89
	db $41, $0c
	dw @song0ref89
	db $41, $0b
	dw @song0ref89
	db $8d, $04, $a5, $00, $a5, $ff, $bf
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
;@song0ch5:
;	db $41, $0b
;	dw @song0ref22
;@song0ch5loop:
;	db $00, $42
;	dw @song0ch5loop
;@song0ch6:
;	db $41, $0b
;	dw @song0ref22
;@song0ch6loop:
;	db $00, $42
;	dw @song0ch6loop
;@song0ch7:
;	db $41, $0b
;	dw @song0ref22
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $ff, $9f, $7c, $80, $26, $a5, $00, $95, $26, $8d, $00, $8d, $27, $a5, $00, $85, $24, $c5, $00, $85, $9f, $27, $ad, $00
	db $8d, $27, $8d, $00, $8d, $28, $a5, $00, $85, $25, $c5, $00, $85, $9f, $28, $ad, $00, $8d, $28, $8d, $00, $8d, $29, $a5
	db $00, $85, $26, $c5, $00, $85, $2a, $8d, $00, $8d, $2a, $8d, $00, $8d, $2a, $8d, $00, $8d, $25, $8d, $00, $8d, $23, $9d
	db $00, $8d, $27, $cd, $ff, $bf
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $ff, $7c, $82, $35, $9d
@song0ref237:
	db $35, $8d, $00, $8d, $32, $8d, $00, $8d, $32, $8d, $00, $8d, $33, $a5, $00, $85, $33, $cd, $35, $8d, $00, $8d
	db $41, $16
	dw @song0ref237
	db $41, $16
	dw @song0ref237
	db $41, $0c
	dw @song0ref237
	db $38, $9d, $00, $8d, $38, $cd, $ff, $bf
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $ff, $7c, $82, $32, $9d
@song0ref286:
	db $32, $8d, $00, $8d, $2e, $8d, $00, $8d, $2e, $8d, $00, $8d, $2c, $a5, $00, $85, $30, $cd, $32, $8d, $00, $8d
	db $41, $16
	dw @song0ref286
	db $41, $16
	dw @song0ref286
	db $41, $0c
	dw @song0ref286
	db $33, $9d, $00, $8d, $33, $cd, $ff, $bf
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $7c, $80, $16, $9d, $15, $9d, $14, $9d, $13, $9d, $16, $8d, $00, $8d, $16, $8d, $00, $8d, $11, $8d, $00, $8d, $11, $8d
	db $00, $8d, $14, $ad, $13, $9d, $14, $8d, $13, $95, $00, $85, $17, $8d, $00, $8d, $17, $8d, $00, $8d, $12, $8d, $00, $8d
	db $12, $8d, $00, $8d, $15, $ad, $14, $9d, $15, $8d, $14
@song0ref389:
	db $95, $00, $85, $18, $8d, $00, $8d, $18, $8d, $00, $8d, $13, $8d, $00, $8d, $13, $8d, $00, $8d, $16, $ad, $15, $9d, $16
	db $8d, $15
	db $41, $13
	dw @song0ref389
	db $1d, $9d, $00, $8d, $1c, $cd, $ff, $bf
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $7c, $80, $22, $9d, $21, $9d, $20, $9d, $1f, $9d, $00, $ff, $fd, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $bf
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $41, $0b
;	dw @song0ref22
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $41, $0b
;	dw @song0ref22
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $41, $0b
;	dw @song0ref22
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $41, $0b
;	dw @song0ref22
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $41, $0b
;	dw @song0ref22
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $41, $0b
;	dw @song0ref22
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $41, $0b
;	dw @song0ref22
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
