; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_04_spring_yard_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 04. Spring Yard Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq1
	dw 0 ;@song0ch7 ; epsm sq2
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env5,@env6,@env8,@env0 ; 00 : Hi hat

@instruments_exp:
	dw @env7, @env6, @env0 ; 00 : 1 Soft
	dw @env10, @env6
	dw @instrument_epsm_extra_patch2
	db $04,$c0,$00,$20
	dw @env3, @env6, @env0 ; 01 : Bass 2
	dw @env10, @env6
	dw @instrument_epsm_extra_patch3
	db $10,$c0,$12,$1a
	dw @env3, @env6, @env0 ; 02 : Bell
	dw @env10, @env6
	dw @instrument_epsm_extra_patch4
	db $04,$c0,$07,$1e
	dw @env3, @env6, @env0 ; 03 : Brass 3 L
	dw @env10, @env6
	dw @instrument_epsm_extra_patch5
	db $3d,$80,$32,$1c
	dw @env3, @env6, @env0 ; 04 : Brass 3 R
	dw @env10, @env6
	dw @instrument_epsm_extra_patch6
	db $3d,$40,$32,$1c
	dw @env3, @env6, @env2 ; 05 : GHZ Trumpet Left
	dw @env10, @env6
	dw @instrument_epsm_extra_patch7
	db $32,$80,$71,$17
	dw @env3, @env6, @env11 ; 06 : GHZ Trumpet Right
	dw @env10, @env6
	dw @instrument_epsm_extra_patch8
	db $32,$40,$71,$17
	dw @env3, @env6, @env9 ; 07 : Trumpet
	dw @env10, @env6
	dw @instrument_epsm_extra_patch9
	db $3a,$c0,$01,$18
	dw @env3, @env6, @env0 ; 08 : Trumpet 2
	dw @env10, @env6
	dw @instrument_epsm_extra_patch10
	db $3a,$c1,$12,$1d

@instrument_epsm_extra_patch2:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$2f,$00,$70,$25,$1f,$13,$04,$2f,$00,$20,$14,$5f,$0a,$04,$2f,$00,$00,$0d,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch4:
	db $15,$03,$0d,$a0,$00,$72,$19,$1f,$02,$07,$a9,$00,$77,$1e,$1f,$00,$07,$10,$00,$72,$1e,$1f,$06,$07,$a7,$00,$08
@instrument_epsm_extra_patch5:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$3e,$94,$00,$02,$17,$00,$72,$18,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch6:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$3e,$94,$00,$02,$17,$00,$72,$18,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch7:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch8:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch9:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch10:
	db $1b,$00,$00,$34,$00,$01,$27,$19,$04,$00,$04,$00,$01,$26,$0f,$00,$00,$04,$00,$02,$0d,$16,$03,$03,$44,$00,$0b

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$be,$bf,$c1,$00,$03
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env6:
	db $c0,$7f,$00,$01
@env7:
	db $00,$c8,$c8,$c9,$c9,$ca,$ca,$cb,$00,$07
@env8:
	db $7f,$00,$00
@env9:
	db $00,$bd,$be,$c0,$00,$03
@env10:
	db $c8,$7f,$00,$00
@env11:
	db $00,$bc,$bd,$bf,$00,$03

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ff, $9f
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid)
;@song0ref8:
;	db $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $ff, $ff, $9f, $47
;	db $ff, $ff, $9f, $47, $ff, $ff, $9f, $47
;	db $41, $18
;	dw @song0ref8
;	db $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $ff, $9f
;@song0ch1loop:
;@song0ref50:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f, $ff, $ff, $9f
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $ff, $9f
;@song0ch2loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch2loop
@song0ch3:
	db $78, $99, $80, $2f, $00, $9f, $2f, $00, $9f, $2f, $00, $9f, $2f, $00, $9f, $2f, $00, $9f, $2f, $00, $9f, $2f, $00, $85
	db $2f, $00, $95, $2f, $00, $85
@song0ch3loop:
@song0ref124:
	db $2f, $00, $95, $2f, $00, $85, $2f, $00, $95, $2f, $00, $85, $2f, $00, $95, $2f, $00, $85, $2f, $00, $95, $2f, $00, $85
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $41, $18
	dw @song0ref124
	db $42
	dw @song0ch3loop
@song0ch4:
	db $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $8f
	db $05, $8f, $00, $83, $05, $89, $05, $8f, $00, $83, $04, $89
@song0ch4loop:
@song0ref281:
	db $00, $a1, $04, $8f, $00, $8f, $05, $8f, $00, $8f, $04, $8f, $00, $8f, $04, $8f, $00, $b3, $05, $8f, $00, $a7, $04, $89
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
	db $04, $8f, $00, $8f, $04, $8f, $00, $8f, $05, $8f, $00, $8f, $04, $8f, $00, $8f, $04, $8f, $00, $8f, $05, $8f, $00, $8f
	db $05, $8f, $00, $8f, $05, $8f, $00, $83, $04, $89
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
	db $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f, $00, $cb, $05, $89, $05, $8f
	db $00, $83, $04, $89
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
@song0ref391:
	db $04, $8f, $00, $b3, $05, $8f, $00, $a7, $04, $89, $04, $89, $00, $95, $05, $8f, $00, $8f, $05, $8f, $00, $8f, $05, $8f
	db $00, $83, $04, $89
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
	db $41, $18
	dw @song0ref281
	db $41, $1c
	dw @song0ref391
	db $42
	dw @song0ch4loop
@song0ch5:
	db $7b, $c7, $4a, <(@env1), >(@env1), $80, $21, $8f, $00, $8f, $4c, $21, $8f, $00, $8f, $4c, $19, $8f, $00, $8f, $4c, $19
	db $8f, $00, $8f, $4c, $1a, $8f, $00, $8f, $4c, $1a, $8f, $00, $8f
@song0ch5loop:
	db $4b, $4d, $01
@song0ref473:
	db $35, $ff, $d5, $36, $a1, $38, $a1, $35, $ff, $d5, $31, $a1, $33, $a1, $35, $ff, $d5, $36, $a1, $38, $a1, $3a, $ff, $ff
	db $9d, $4d, $01
@song0ref500:
	db $35, $ff, $d5, $36, $a1, $38, $a1, $35, $ff, $d5, $31, $a1, $33, $a1, $35, $ff, $d5, $36, $a1, $38, $a1, $3e, $8f, $00
	db $8f, $3e, $8f, $00, $8f, $3e, $8f, $00, $8f, $3e, $8f, $00, $8f, $3e
@song0ref538:
	db $8f, $00, $ef
@song0ref541:
	db $33, $89, $00, $95, $33, $ad, $33, $8f, $00, $8f, $33, $8f, $00, $8f, $31, $8f, $00, $8f, $3a, $8f, $00, $8f, $36, $8f
	db $00, $a7, $2f, $89, $00, $95, $2f, $ad, $2f, $8f, $00, $8f, $2f, $8f, $00, $8f, $2e
	db $41, $2c
	dw @song0ref538
	db $8f, $00, $8f, $2e, $8f, $00, $8f, $2f, $95, $31, $a1
	db $41, $29
	dw @song0ref541
	db $8f, $00, $fb, $2e, $c5, $32, $c5, $35, $c5, $3e, $b9, $3f, $89, $00, $ff, $ff, $9d, $42
	dw @song0ch5loop
;@song0ch6:
;	db $ff, $ff, $9f
;@song0ch6loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch6loop
;@song0ch7:
;	db $ff, $ff, $9f
;@song0ch7loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch7loop
@song0ch8:
	db $85, $00, $ff, $ff, $8b, $90, $29, $89
@song0ch8loop:
@song0ref654:
	db $00, $95, $29, $ad, $25, $8f, $00, $8f, $22, $8f, $00, $8f, $29, $b9, $25, $89, $00, $c5, $ff, $ff, $93, $2b, $89, $00
	db $95, $2b, $ad, $27, $8f, $00, $8f, $24, $8f, $00, $8f, $2b, $c5, $27, $c5, $2a, $ff, $ff, $91, $29, $89
	db $41, $28
	dw @song0ref654
	db $8f, $00, $8f, $2a, $8f, $00, $8f, $2c, $95, $2a, $89, $2c, $8f, $00, $8f, $2e, $a1, $00, $e9, $91, $00, $83, $84
@song0ref725:
	db $36, $ad, $35, $8f, $00, $8f, $33, $8f, $00, $8f, $31, $8f, $00, $8f, $33, $8f, $00, $8f, $31, $95, $2e, $a1, $2f, $89
	db $00, $95, $2f, $ad, $31, $8f, $00, $8f, $2f, $8f, $00, $8f, $2e, $95, $2f, $95, $00, $89, $31, $c5, $00, $89, $97, $36
	db $ad, $35, $8f, $00, $8f, $33, $8f, $00, $8f, $31, $8f, $00, $8f, $33, $8f, $00, $8f, $31, $95, $2e, $ad, $31, $c5, $38
	db $b9, $3a, $89, $00, $95, $3a, $89, $38, $95, $00, $89, $36, $c3, $5a, $91, $00, $83
	db $41, $2e
	dw @song0ref725
	db $a3, $35, $89, $00, $95, $35, $c5, $36, $c5, $35, $b9, $33, $87, $5a, $85, $00, $ff, $ff, $8b, $90, $29, $89, $42
	dw @song0ch8loop
@song0ch9:
	db $82, $16, $8f, $00, $8f, $16, $8f, $00, $8f
@song0ref851:
	db $14, $8f, $00, $8f, $14, $8f, $00, $8f, $12, $8f, $00, $8f, $12, $8f, $00, $8f, $11, $8f, $00, $8f, $11, $8f, $00, $83
	db $0f, $89
@song0ch9loop:
@song0ref878:
	db $00, $95, $0f, $ad, $11, $8f, $00, $8f, $0f, $8f, $00, $8f, $11, $8f, $00, $8f, $0f, $8f, $00, $8f, $11, $95, $16, $89
	db $00, $95, $16, $89, $00, $95, $1d, $a1, $00, $89, $19, $8f, $00, $8f, $19, $8f, $00, $8f, $16, $8f, $00, $8f, $16, $8f
	db $00, $8f, $12, $b9, $11, $89, $00, $95, $11, $ad, $13, $8f, $00, $8f, $11, $8f, $00, $8f, $13, $8f, $00, $8f, $11, $8f
	db $00, $8f, $14, $95, $17, $a1, $16, $89, $00, $95, $16, $ad
	db $41, $1a
	dw @song0ref851
	db $41, $4d
	dw @song0ref878
	db $ad, $16, $8f, $00, $8f, $16, $8f, $00, $8f, $16, $8f, $00, $8f, $16, $8f, $00, $8f, $16, $8f, $00, $ef
@song0ref989:
	db $17, $89, $00, $95, $17, $ad, $19, $8f, $00, $8f, $17, $8f, $00, $8f, $16, $a1, $00, $a1, $17, $95, $16, $a1, $14, $89
	db $00, $95, $14, $ad, $16, $8f, $00, $8f, $14, $8f, $00, $8f, $12, $8f, $00, $8f, $12, $8f, $00, $8f, $14, $95, $16, $a1
	db $41, $30
	dw @song0ref989
	db $41, $30
	dw @song0ref989
	db $11, $89, $00, $95, $11, $ad, $11, $8f, $00, $8f, $11, $8f, $00, $8f, $16, $8f, $00, $b3, $16, $b9, $0f, $89, $00, $ff
	db $ff, $91, $0f, $89, $42
	dw @song0ch9loop
@song0ch10:
	db $ff, $ff, $9f
@song0ch10loop:
	db $ff, $ff, $9f, $7c, $a3, $8e
@song0ref1084:
	db $2e, $95, $31, $89, $33, $95, $36, $89, $00, $a1, $2e, $95, $31, $89, $33, $95, $36, $89, $00, $c5, $ff, $ff, $9f, $a3
	db $3a, $89, $00, $b9, $38, $89, $00, $b9, $36, $89, $00, $95, $35, $89, $00, $89, $36, $89, $35, $89, $00, $95, $ff, $ff
	db $9f, $a3
	db $41, $17
	dw @song0ref1084
	db $2e, $89, $00, $89, $2e, $89, $32, $89, $00, $89, $32, $89, $35, $89, $00, $89, $35, $89, $38, $89, $00, $89, $38, $89
	db $3a, $89, $00, $f5
@song0ref1165:
	db $2a, $89
@song0ref1167:
	db $00, $95, $2a, $ad, $2a, $8f, $00, $8f, $2a, $8f, $00, $8f, $29, $8f, $00, $ef, $27, $89, $00, $95, $27, $ad, $27, $8f
	db $00, $8f, $27, $8f, $00, $8f, $25, $8f, $00, $fb
	db $41, $21
	dw @song0ref1167
	db $8f, $25, $8f, $00, $8f, $27, $95, $29, $a1
	db $41, $24
	dw @song0ref1165
	db $97, $3a, $ad, $38, $8f, $00, $8f, $38, $8f, $00, $8f, $36, $8f, $00, $8f, $36, $8f, $00, $8f, $35, $95, $36, $89, $35
	db $95, $33, $89, $00, $ff, $ff, $9d, $42
	dw @song0ch10loop
@song0ch11:
	db $4a, <(@env1), >(@env1), $8a
@song0ref1254:
	db $2e, $8f, $00, $8f, $4c, $2e, $8f, $00, $8f, $4c, $30, $8f, $00, $8f, $4c, $30, $8f, $00, $8f, $4c, $31, $8f, $00, $8f
	db $4c, $31, $8f, $00, $8f, $4c, $32, $8f, $00, $8f, $4c, $32, $8f, $00, $8f
@song0ch11loop:
	db $4b, $79, $86
	db $41, $19
	dw @song0ref473
	db $41, $52
	dw @song0ref500
	db $41, $2c
	dw @song0ref538
	db $8f, $00, $8f, $2e, $8f, $00, $8f, $2f, $95, $31, $a1
	db $41, $29
	dw @song0ref541
	db $8f, $00, $fb, $2e, $c5, $32, $c5, $35, $c5, $3e, $b9, $3f, $89, $00, $ff, $ff, $9d, $42
	dw @song0ch11loop
@song0ch12:
	db $4a, <(@env1), >(@env1), $8c
	db $41, $20
	dw @song0ref1254
@song0ch12loop:
	db $4b, $79, $4d, $02, $88
	db $41, $19
	dw @song0ref473
	db $4d, $02
	db $41, $52
	dw @song0ref500
	db $41, $2c
	dw @song0ref538
	db $8f, $00, $8f, $2e, $8f, $00, $8f, $2f, $95, $31, $a1
	db $41, $29
	dw @song0ref541
	db $8f, $00, $fb, $2e, $c5, $32, $c5, $35, $c5, $3e, $b9, $3f, $89, $00, $ff, $ff, $9d, $42
	dw @song0ch12loop
;@song0ch13:
;	db $ff, $ff, $9f
;@song0ch13loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $ff, $9f
;@song0ch14loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $ff, $9f
;@song0ch15loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $ff, $9f
;@song0ch16loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $ff, $9f
;@song0ch17loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $ff, $9f
;@song0ch18loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $ff, $9f
;@song0ch19loop:
;	db $41, $18
;	dw @song0ref50
;	db $41, $18
;	dw @song0ref50
;	db $42
;	dw @song0ch19loop
