; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_11_stage_clear:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 11. Stage Clear

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env7, @env5, @env0 ; 00 : 1 Long
	dw @env9, @env5
	dw @instrument_epsm_extra_patch1
	db $04,$c0,$00,$20
	dw @env3, @env5, @env0 ; 01 : Bass 3
	dw @env9, @env5
	dw @instrument_epsm_extra_patch2
	db $00,$c0,$00,$7f
	dw @env3, @env5, @env0 ; 02 : Brass 2
	dw @env9, @env5
	dw @instrument_epsm_extra_patch3
	db $3d,$c0,$32,$20
	dw @env3, @env5, @env2 ; 03 : GHZ Trumpet Left
	dw @env9, @env5
	dw @instrument_epsm_extra_patch4
	db $32,$80,$71,$17
	dw @env3, @env5, @env10 ; 04 : GHZ Trumpet Right
	dw @env9, @env5
	dw @instrument_epsm_extra_patch5
	db $32,$40,$71,$17
	dw @env3, @env5, @env0 ; 05 : Trumpet 2
	dw @env9, @env5
	dw @instrument_epsm_extra_patch6
	db $3a,$c1,$12,$1d

@instrument_epsm_extra_patch1:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch2:
	db $1f,$00,$00,$23,$00,$70,$20,$1f,$00,$04,$23,$00,$10,$1f,$5f,$05,$04,$23,$00,$20,$0b,$5f,$0a,$03,$25,$00,$00
@instrument_epsm_extra_patch3:
	db $5f,$00,$01,$47,$00,$21,$21,$90,$00,$02,$26,$00,$01,$32,$94,$00,$02,$17,$00,$14,$21,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch4:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch5:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch6:
	db $1b,$00,$00,$34,$00,$01,$27,$19,$04,$00,$04,$00,$01,$26,$0f,$00,$00,$04,$00,$02,$0d,$16,$03,$03,$44,$00,$0b

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$be,$bf,$c1,$00,$03
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $08,$cd,$05,$cc,$02,$cc,$00,$05,$cb,$02,$ca,$03,$c9,$02,$c8,$c8,$00,$0f
@env8:
	db $00,$c0,$bb,$b8,$b7,$b9,$bd,$c3,$c7,$c9,$c8,$c5,$00,$01
@env9:
	db $c8,$7f,$00,$00
@env10:
	db $00,$bc,$bd,$bf,$00,$03
@env11:
	db $00,$c0,$bd,$bc,$bd,$bf,$c1,$c3,$c4,$c3,$00,$01

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ff, $9f, $47, $ff, $ff, $9f, $47, $eb
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
;@song0ch3:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch3loop:
;	db $00, $42
;	dw @song0ch3loop
@song0ch4:
@song0ref51:
	db $05, $8f, $05, $8f, $04, $8f, $00, $8f, $04, $8f, $00, $8f
	db $41, $0c
	dw @song0ref51
	db $05, $8f, $05, $8f, $02, $8f, $02, $8f, $01, $8f, $01, $8f, $01, $8f, $01, $8f, $05, $8f, $00, $a1, $05, $8f, $00, $ff
	db $8d, $eb
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
@song0ch5:
	db $4d, $02, $00, $a1, $80, $20, $a1, $22, $a1, $24, $a1, $25, $a1, $27, $a1, $29, $a1, $2a, $a1, $2c, $c5, $3c, $85, $3d
	db $87, $3c, $8f, $38, $8f, $3a, $8f, $48, <(@env11), >(@env11), $ff, $8f, $7d, $50, $fe, $70, $e9, $81
@song0ch5loop:
	db $00, $42
	dw @song0ch5loop
@song0ch6:
	db $7b, $80, $38, $a1, $3d, $a1, $3c, $a1, $38, $a1, $3d, $a1, $3c, $a1, $38, $a1, $3d, $a1, $3c, $c5, $3d, $b3, $3c, $ff
	db $9f, $50, $fe, $50, $e9, $81
@song0ch6loop:
	db $00, $42
	dw @song0ch6loop
;@song0ch7:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $00, $a1, $84, $14, $a1, $16, $a1, $18, $a1, $19, $a1, $1b, $a1, $1d, $a1, $1e, $a1, $20, $c5, $30, $85, $43, $31, $87
	db $43, $30, $8f, $2c, $8f, $2e, $8f, $48, <(@env8), >(@env8), $ff, $8f, $50, $fe, $90, $e9, $48, <(@env0), >(@env0), $49
	db $81
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $82
@song0ref242:
	db $20, $8f, $20, $8f, $14, $8f, $00, $8f, $14, $8f, $00, $8f
	db $41, $0c
	dw @song0ref242
	db $20, $8f, $20, $8f, $00, $a1, $c7, $14, $8f, $00, $a1, $16, $ff, $9f, $50, $fe, $90, $e9, $48, <(@env0), >(@env0), $49
	db $81
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $86
@song0ref286:
	db $31, $85, $00, $87, $31, $87, $00, $cd
	db $41, $08
	dw @song0ref286
	db $31, $85, $00, $87, $31, $87, $00, $a9, $c7, $31, $b3, $33, $ff, $9f, $50, $fe, $90, $e9, $48, <(@env0), >(@env0), $49
	db $81
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $88
@song0ref326:
	db $2e, $85, $00, $87, $2e, $87, $00, $cd
	db $41, $08
	dw @song0ref326
	db $2e, $85, $00, $87, $2e, $87, $00, $a9, $c7, $2e, $b3, $30, $ff, $9f, $50, $fe, $90, $e9, $48, <(@env0), >(@env0), $49
	db $81
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $8a
@song0ref366:
	db $20, $8f, $20, $8f, $25, $a1, $24, $a1
	db $41, $08
	dw @song0ref366
	db $20, $8f, $20, $8f, $25, $a1, $24, $c5, $25, $b3, $24, $ff, $9f, $50, $fe, $90, $e9, $48, <(@env0), >(@env0), $49, $81
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $ff, $9f, $ff, $ff, $9f, $eb
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
