; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_03_marble_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 03. Marble Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw 0 ; @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env2,@env5,@env7,@env0 ; 00 : Longer Noise

@instruments_exp:
	dw @env6, @env5, @env0 ; 00 : 1 Fade
	dw @env9, @env5
	dw @instrument_epsm_extra_patch2
	db $04,$c0,$00,$20
	dw @env3, @env5, @env0 ; 01 : Bass Slap
	dw @env9, @env5
	dw @instrument_epsm_extra_patch3
	db $08,$c0,$09,$25
	dw @env3, @env5, @env0 ; 02 : EPSM Marble
	dw @env9, @env5
	dw @instrument_epsm_extra_patch4
	db $22,$c0,$0a,$1e
	dw @env3, @env5, @env8 ; 03 : Trumpet
	dw @env9, @env5
	dw @instrument_epsm_extra_patch5
	db $3a,$c0,$01,$18
	dw @env3, @env5, @env0 ; 04 : Weird Bell
	dw @env9, @env5
	dw @instrument_epsm_extra_patch6
	db $22,$c0,$34,$2d

@instrument_epsm_extra_patch2:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch4:
	db $03,$00,$03,$1f,$00,$13,$18,$12,$13,$02,$1f,$00,$05,$26,$12,$13,$02,$0f,$00,$11,$16,$11,$00,$01,$0f,$00,$00
@instrument_epsm_extra_patch5:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch6:
	db $df,$05,$07,$20,$00,$3c,$21,$df,$0a,$06,$16,$00,$31,$22,$9f,$03,$06,$17,$00,$33,$16,$9f,$08,$08,$f6,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c7,$c7,$c6,$c3,$c3,$c2,$c1,$00,$07
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $00,$cd,$02,$cc,$02,$cb,$02,$ca,$00,$07
@env7:
	db $7f,$00,$00
@env8:
	db $00,$bd,$be,$c0,$00,$03
@env9:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $e9
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f, $47
;	db $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f
;	db $47, $ff, $ff, $ff, $9f, $47, $ff, $ff, $ff, $9f, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $e9
;@song0ch1loop:
;@song0ref62:
;	db $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f
;	db $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $ff, $ff, $ff, $9f, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $e9
;@song0ch2loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch2loop
@song0ch3:
	db $ff, $e9
@song0ch3loop:
	db $80
@song0ref118:
	db $27, $97, $27, $97, $29, $97, $29, $97, $28, $97, $28, $97, $29, $97, $29, $97, $27, $97, $27, $97, $29, $97, $29, $97
	db $28, $97, $28, $97, $29, $97, $29, $97, $28, $97, $28, $97, $2a, $97, $2a, $97, $29, $97, $29, $97, $2a, $97, $2a, $97
	db $28, $97, $28, $97, $2a, $97, $2a, $97, $29, $97, $29, $97, $2a, $97, $2a, $97, $26, $97, $26, $97, $27, $97, $27, $97
	db $26, $97, $26, $97, $27, $97, $27, $97, $26, $97, $26, $97, $27, $97, $27, $97, $26, $97, $26, $97, $27, $97, $27, $97
	db $27, $97, $27, $97, $28, $97, $28, $97, $27, $97, $27, $97, $28, $97, $28, $97, $27, $97, $27, $97, $28, $97, $28, $97
	db $27, $97, $27, $97, $26, $97, $26, $97
	db $41, $50
	dw @song0ref118
	db $28, $97, $28, $97, $2a, $97, $2a, $97, $29, $97, $29, $97, $2a, $97, $2a, $97, $27, $97, $27, $97, $29, $97, $29, $97
	db $27, $97, $27, $97, $29, $97, $29, $97, $27, $97, $27, $97, $29, $97, $29, $97, $27, $97, $27, $97, $29, $97, $29
@song0ref296:
	db $97, $1a, $b1, $00, $97, $1a, $97, $1a, $b1, $00, $97, $1a, $97, $19, $b1, $00, $97, $19, $97, $1a, $b1, $00, $97, $1a
	db $41, $18
	dw @song0ref296
	db $97, $42
	dw @song0ch3loop
@song0ch4:
	db $05, $89, $05, $8b, $05, $97, $00, $97, $04, $97, $00, $97, $04, $97, $00, $97, $04, $97, $00, $97
@song0ch4loop:
@song0ref348:
	db $04, $97, $00, $97, $04, $97, $00, $97, $04, $97, $00, $97, $04, $97, $00, $97, $04, $97, $00, $97, $04, $97, $00, $97
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $41, $18
	dw @song0ref348
	db $04, $97, $00, $97, $04, $97, $00, $97, $42
	dw @song0ch4loop
@song0ch5:
	db $ff, $e9
@song0ch5loop:
	db $00, $ff, $ff, $ff, $9d, $ff, $cf
@song0ref429:
	db $80
@song0ref430:
	db $40, $4e, $89, $3f, $8b, $3a, $8b, $36, $89, $3f, $89, $3a, $8b, $36, $8b, $33, $89, $3a, $89, $36, $8b, $33, $8b, $2e
	db $89, $36, $89, $33, $8b, $2e, $8b, $2a, $89, $b3, $00, $ff, $ff, $e9, $ff, $b5, $40, $4e, $b1, $40, $4e, $97, $3f, $b1
	db $3c, $97, $39, $cb, $81, $00, $ff, $ff, $ff, $9b, $ff, $cf
	db $41, $26
	dw @song0ref430
	db $ff, $ff, $9f
@song0ref496:
	db $3a, $97, $3d, $8b, $3a, $89, $3d, $97, $3a, $97, $3c, $97, $38, $97, $33, $97, $3c, $97, $36, $97, $3a, $8b, $36, $89
	db $3a, $97, $36, $97, $38, $97, $3a, $97, $3c, $97, $38, $97
	db $41, $24
	dw @song0ref496
	db $42
	dw @song0ch5loop
@song0ch6:
	db $ff, $e9
@song0ch6loop:
	db $00, $ff, $ff, $ff, $9d, $79, $4d, $ff, $ff, $e3
	db $41, $1d
	dw @song0ref429
	db $83, $87, $2a, $bd, $00, $ff, $ff, $d5, $ff, $c9, $40, $4e, $b1, $40, $4e, $97, $3f, $b1, $3c, $97, $39, $b7, $91, $00
	db $ff, $ff, $ff, $8b, $4d, $ff, $ff, $e3
	db $41, $1d
	dw @song0ref430
	db $83, $87, $2a, $bd, $00, $ff, $ff, $d5, $ff, $ff, $ff, $9f, $93
	db $41, $23
	dw @song0ref496
	db $83, $93
	db $41, $23
	dw @song0ref496
	db $83, $42
	dw @song0ch6loop
;@song0ch7:
;	db $ff, $e9
;@song0ch7loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch7loop
@song0ch8:
	db $e7, $4d, $ff, $99, $84, $22, $97, $24, $97, $25, $97, $29, $97
@song0ch8loop:
@song0ref637:
	db $30, $a5, $00, $89, $30, $97, $2e, $97, $30, $a5, $00, $89, $30, $97, $2e, $97, $30, $a5, $00, $89, $30, $97, $2e, $97
	db $30, $97, $2e, $97, $29, $97, $25, $97, $2c, $b1, $2e, $97, $2a, $ff, $ff, $b5, $00, $97, $2e, $a5, $00, $89, $2e, $97
	db $2c, $97, $2e, $a5, $00, $89, $2e, $97, $2c, $97, $2e, $a5, $00, $89, $2e, $97, $2c, $97, $2e, $b1, $30, $b1, $2a, $cb
	db $29, $ff, $cd, $00, $97, $22, $97, $24, $97, $25, $97, $29, $97
	db $41, $2b
	dw @song0ref637
	db $ff, $99, $30, $b1, $2d, $ff, $99, $30, $b1, $30, $cb, $2e, $ff, $ff, $cf, $00, $ff, $ff, $ff, $9d, $ff, $ff, $b7, $22
	db $97, $24, $97, $25, $97, $29, $97, $42
	dw @song0ch8loop
@song0ch9:
	db $82, $1d, $89, $1d, $8b, $1d, $97, $00, $97, $11, $ff, $99
@song0ch9loop:
@song0ref772:
	db $16, $89, $00, $8b, $16, $97, $1d, $89, $00, $8b, $1d, $97, $1b, $89, $00, $8b, $1b, $97, $1d, $89, $00, $8b, $1d, $97
	db $41, $18
	dw @song0ref772
@song0ref799:
	db $1b, $89, $00, $8b, $1b, $97, $22, $89, $00, $8b, $22, $97, $1e, $89, $00, $8b, $1e, $97, $22, $89, $00, $8b, $22, $97
	db $41, $18
	dw @song0ref799
@song0ref826:
	db $14, $89, $00, $8b, $14, $97, $1b, $89, $00, $8b, $1b, $97, $18, $89, $00, $8b, $18, $97, $1b, $89, $00, $8b, $1b, $97
	db $41, $18
	dw @song0ref826
	db $19, $89, $00, $8b, $19, $97, $20, $89, $00, $8b, $20, $97, $1d, $89, $00, $8b, $1d, $97, $20, $89, $00, $8b, $20, $97
	db $18, $89, $00, $8b, $18, $97, $1e, $89, $00, $8b, $1e, $97, $1d, $89, $00, $8b, $1d, $97, $18, $89, $00, $8b, $18, $97
	db $41, $18
	dw @song0ref772
	db $41, $18
	dw @song0ref772
	db $41, $18
	dw @song0ref799
	db $41, $18
	dw @song0ref799
	db $18, $89, $00, $8b, $18, $97, $1e, $89, $00, $8b, $1e, $97, $1b, $89, $00, $8b, $1b, $97, $1e, $89, $00, $8b, $1e, $97
	db $1d, $89, $00, $8b, $1d, $97, $24, $89, $00, $8b, $24, $97, $21, $89, $00, $8b, $21, $97, $24, $89, $00, $8b, $24
@song0ref960:
	db $97, $16, $89, $00, $8b, $16, $97, $1d, $89, $00, $8b, $1d, $97, $19, $89, $00, $8b, $19, $97, $1d, $89, $00, $8b, $1d
	db $41, $18
	dw @song0ref960
	db $97, $16, $cb, $16, $97, $14, $cb, $14, $97, $12, $cb, $12, $97, $14, $cb, $14, $97, $16, $cb, $16, $97, $14, $cb, $14
	db $97, $12, $cb, $12, $97, $14, $cb, $14, $97, $42
	dw @song0ch9loop
;@song0ch10:
;	db $ff, $e9
;@song0ch10loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch10loop
@song0ch11:
	db $88, $11, $89, $11, $8b, $11, $97, $00, $97, $05, $ff, $7a, $4d, $fd, $86, $30, $97
@song0ch11loop:
@song0ref1050:
	db $99, $30, $8b, $00, $89, $31, $97, $00, $97, $30, $b1, $00, $97, $30, $b1, $30, $8b, $00, $89, $31, $97, $00, $97, $30
	db $b1, $00, $b1, $b3, $31, $89, $00, $bf, $31, $8b, $00, $f1, $31, $89, $00, $bf, $31, $8b, $00, $a3, $2e, $97, $99, $2e
	db $8b, $00, $89, $30, $97, $00, $97, $2e, $b1, $00, $97, $2e, $b1, $2e, $8b, $00, $89, $30, $97, $00, $97, $2e, $b1, $00
	db $b1, $b3, $2c, $89, $00, $bf, $2c, $8b, $00, $ff, $f3, $30, $97
	db $41, $2c
	dw @song0ref1050
	db $2a, $97, $99, $2a, $8b, $00, $89, $2e, $97, $00, $97, $2a, $b1, $00, $97, $2d, $b1, $2d, $8b, $00, $89, $30, $97, $00
	db $97, $2d, $b1, $00, $b1, $b3, $31, $89, $00, $bf, $31, $8b, $00, $a3, $35, $b1, $35, $8b, $00, $89, $33, $97, $00, $97
	db $31, $89, $00, $8b, $30, $cb
@song0ref1192:
	db $00, $97, $35, $8b, $00, $89, $31, $89, $00, $8b, $2e, $8b, $00, $a3, $33, $8b, $00, $89, $30, $89, $00, $8b, $2c, $8b
	db $00, $a3, $31, $8b, $00, $89, $2e, $89, $00, $8b, $2a, $8b, $00, $a3, $33, $8b, $00, $89, $30, $89, $00, $8b, $2c, $8b
	db $00, $89
	db $41, $32
	dw @song0ref1192
	db $42
	dw @song0ch11loop
@song0ch12:
	db $ff, $cf, $7a, $4d, $fe, $86, $2c, $97
@song0ch12loop:
@song0ref1257:
	db $99, $2c, $8b, $00, $89, $2e, $97, $00, $97, $2c, $b1, $00, $97, $2c, $b1, $2c, $8b, $00, $89, $2e, $97, $00, $97, $2c
	db $b1, $00, $b1, $b3, $2e, $89, $00, $bf, $2e, $8b, $00, $f1, $2e, $89, $00, $bf, $2e, $8b, $00, $a3, $2a, $97, $99, $2a
	db $8b, $00, $89, $2c, $97, $00, $97, $2a, $b1, $00, $97, $2a, $b1, $2a, $8b, $00, $89, $2c, $97, $00, $97, $2a, $b1, $00
	db $b1, $b3, $29, $89, $00, $bf, $29, $8b, $00, $ff, $f3, $2c, $97
	db $41, $2c
	dw @song0ref1257
	db $27, $97, $99, $27, $8b, $00, $89, $2a, $97, $00, $97, $27, $b1, $00, $97, $29, $b1, $29, $8b, $00, $89, $2d, $97, $00
	db $97, $29, $b1, $00, $b1, $b3, $2e, $89, $00, $bf, $2e, $8b, $00, $a3, $31, $b1, $31, $8b, $00, $89, $30, $97, $00, $97
	db $2e, $89, $00, $8b, $2d, $cb, $4d, $ff
	db $41, $31
	dw @song0ref1192
	db $87, $4d, $fe, $81, $4d, $ff
	db $41, $31
	dw @song0ref1192
	db $87, $4d, $fe, $81, $42
	dw @song0ch12loop
;@song0ch13:
;	db $ff, $e9
;@song0ch13loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $e9
;@song0ch14loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $e9
;@song0ch15loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $e9
;@song0ch16loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $e9
;@song0ch17loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $e9
;@song0ch18loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $e9
;@song0ch19loop:
;	db $41, $28
;	dw @song0ref62
;	db $42
;	dw @song0ch19loop
