; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_08_special_stage:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 08. Special Stage

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw 0 ;@song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env1, @env7, @env0 ; 00 : 1 Longer
	dw @env10, @env7
	dw @instrument_epsm_extra_patch0
	db $04,$c0,$00,$20
	dw @env3, @env7, @env0 ; 01 : 1 short
	dw @env10, @env7
	dw @instrument_epsm_extra_patch1
	db $04,$c0,$00,$20
	dw @env5, @env7, @env4 ; 02 : 1-Synth 2
	dw @env10, @env7
	dw @instrument_epsm_extra_patch2
	db $04,$c0,$76,$26
	dw @env5, @env7, @env0 ; 03 : Bass 3
	dw @env10, @env7
	dw @instrument_epsm_extra_patch3
	db $00,$c0,$00,$7f
	dw @env5, @env7, @env9 ; 04 : GHZ Trumpet Mid
	dw @env10, @env7
	dw @instrument_epsm_extra_patch4
	db $32,$c0,$71,$17
	dw @env5, @env7, @env0 ; 05 : Saw 
	dw @env10, @env7
	dw @instrument_epsm_extra_patch5
	db $3d,$c0,$22,$1a
	dw @env5, @env7, @env0 ; 06 : Saw L
	dw @env10, @env7
	dw @instrument_epsm_extra_patch6
	db $3d,$80,$22,$1a
	dw @env5, @env7, @env0 ; 07 : Saw R
	dw @env10, @env7
	dw @instrument_epsm_extra_patch7
	db $3d,$40,$22,$1a

@instrument_epsm_extra_patch0:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch1:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch2:
	db $5f,$02,$00,$51,$00,$72,$14,$1f,$80,$03,$03,$00,$04,$26,$1f,$04,$00,$51,$00,$04,$19,$1a,$8e,$03,$03,$00,$08
@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$23,$00,$70,$20,$1f,$00,$04,$23,$00,$10,$1f,$5f,$05,$04,$23,$00,$20,$0b,$5f,$0a,$03,$25,$00,$00
@instrument_epsm_extra_patch4:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch5:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$20,$94,$00,$02,$17,$00,$72,$41,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch6:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$20,$94,$00,$02,$17,$00,$72,$41,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch7:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$20,$94,$00,$02,$17,$00,$72,$41,$90,$80,$01,$08,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$cd,$04,$cc,$04,$cb,$04,$ca,$04,$c9,$04,$c8,$00,$0b
@env2:
	db $c1,$c0,$00,$01
@env3:
	db $00,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c8,$c7,$c6,$00,$0a
@env4:
	db $00,$c0,$1c,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env5:
	db $00,$cf,$7f,$00,$02
@env6:
	db $bf,$bf,$c0,$00,$02
@env7:
	db $c0,$7f,$00,$01
@env8:
	db $7f,$00,$00
@env9:
	db $00,$bd,$be,$c0,$00,$03
@env10:
	db $c8,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid)
;@song0ref5:
;	db $ff, $ff, $cf, $47, $ff, $ff, $cf, $47, $ff, $ff, $cf, $47, $ff, $ff, $cf, $47
;	db $41, $0c
;	dw @song0ref5
;	db $47
;	db $41, $0c
;	dw @song0ref5
;	db $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ch1loop:
;@song0ref32:
;	db $ff, $ff, $cf, $ff, $ff, $cf, $ff, $ff, $cf, $ff, $ff, $cf
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch1loop
;@song0ch2:
;@song0ch2loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch2loop
;@song0ch3:
;@song0ch3loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch3loop
;@song0ch4:
;@song0ch4loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch4loop
@song0ch5:
@song0ch5loop:
	db $82
@song0ref94:
	db $40, $4d, $99, $40, $4d, $99, $3d, $99, $00, $99, $3a, $99, $00, $99, $3f, $99, $3f, $99, $3c, $99, $00, $99, $38, $99
	db $00, $99, $3d, $99, $3d, $99, $3a, $99, $00, $99, $36, $99, $00, $99, $3c, $99, $00, $ff, $89
	db $41, $1a
	dw @song0ref94
@song0ref140:
	db $00, $d1, $3f, $99, $00, $99, $3d, $99, $00, $ff, $89
	db $41, $29
	dw @song0ref94
	db $41, $1a
	dw @song0ref94
	db $41, $0b
	dw @song0ref140
@song0ref160:
	db $4d, $01, $40, $52, $99, $40, $52, $97, $4d, $00, $81, $40, $4e, $99, $40, $4e, $99, $3f, $99, $3f, $99
	db $41, $0b
	dw @song0ref160
	db $00
@song0ref185:
	db $99, $4d, $01, $40, $54, $99, $40, $54, $99, $4d, $00, $40, $50, $99, $40, $50, $99, $40, $4d, $99, $40, $4d
	db $41, $0b
	dw @song0ref185
	db $00, $99
	db $41, $0d
	dw @song0ref160
	db $41, $0b
	dw @song0ref160
	db $00, $99, $40, $55, $99, $40, $55, $99, $40, $52, $99, $40, $52, $99, $40, $4e, $99, $40, $4e, $99, $40, $50, $99, $00
	db $ff, $89, $42
	dw @song0ch5loop
@song0ch6:
@song0ch6loop:
	db $7d, $00, $b5, $80, $40, $5e, $b5
@song0ref255:
	db $40, $5e, $b5
@song0ref258:
	db $00, $b5, $40, $5e, $b5, $40, $5e, $b5, $00, $b5, $40, $5e, $b5, $40, $5e, $b5, $00, $b5, $40, $5e, $99, $40, $5e, $99
	db $41, $11
	dw @song0ref255
	db $b5, $40, $5e, $b5, $40, $5e, $ff, $a5
	db $41, $0f
	dw @song0ref258
	db $b5, $40, $5e, $b5, $00, $b5, $40, $5e, $99, $40, $5e, $99
	db $41, $11
	dw @song0ref255
	db $b5, $40, $5e, $b5, $40, $5e, $ff, $a5
	db $41, $0f
	dw @song0ref258
	db $b5, $40, $5e, $b5, $00, $b5, $40, $5e, $99, $40, $5e, $99
	db $41, $11
	dw @song0ref255
	db $b5, $40, $5e, $b5, $40, $5e, $ff, $a5, $42
	dw @song0ch6loop
;@song0ch7:
;@song0ch7loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch7loop
@song0ch8:
@song0ch8loop:
	db $88
@song0ref363:
	db $29, $ed, $2a, $b5, $2c, $ed, $29, $b5, $29, $ed, $25, $b5, $29, $ed, $25, $b5, $29, $ed, $2a, $b5, $2c, $ed, $29, $b5
	db $25, $ed, $27, $b5, $25, $ff, $a5
	db $41, $1f
	dw @song0ref363
@song0ref397:
	db $00, $b5, $27, $b5, $29, $b5, $2a, $b5, $29, $b5, $2a, $b5, $2c, $ed, $29, $b5, $25, $ff, $a5
	db $41, $0e
	dw @song0ref397
	db $2e, $b5, $2c, $ff, $a5, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $86
@song0ref429:
	db $12, $b5, $5a, $ed, $11, $b5, $5a, $ed, $0f, $b5, $5a, $ed, $0d, $b5, $0f, $b5, $11, $b5
	db $41, $0b
	dw @song0ref429
	db $99, $11, $99, $0f, $b5, $0d, $b5, $5a, $ed
	db $41, $12
	dw @song0ref429
	db $41, $0b
	dw @song0ref429
	db $99, $11, $99, $0f, $b5
@song0ref470:
	db $0d, $b5, $5a, $ed, $0b, $b5, $5a, $ed, $0b, $b5, $5a, $ed, $0d, $b5, $5a, $ed
	db $41, $0c
	dw @song0ref470
	db $0f, $b5, $5a, $ed, $14, $b5, $5a, $ed, $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $00, $b5, $8a
@song0ref504:
	db $29, $8b, $5a, $8b, $00, $99, $29, $99, $5a, $99, $00, $b5, $27, $8b, $5a, $8b, $00, $99, $27, $99, $5a, $99
@song0ref526:
	db $00, $b5
@song0ref528:
	db $25, $8b, $5a, $8b, $00, $99, $25, $99, $5a, $99, $24, $b5, $25, $b5, $27, $b5, $00, $b5
	db $41, $16
	dw @song0ref504
@song0ref549:
	db $25, $d1, $27, $99, $25, $b5, $24, $ff, $a5, $00, $b5
	db $41, $2a
	dw @song0ref504
	db $41, $16
	dw @song0ref504
	db $41, $0b
	dw @song0ref549
@song0ref569:
	db $22, $8b, $5a, $8b, $00, $99, $22, $99, $5a, $99, $00, $b5
	db $41, $0c
	dw @song0ref569
@song0ref584:
	db $24, $8b, $5a, $8b, $00, $99, $24, $99, $5a, $99, $00, $b5
	db $41, $0c
	dw @song0ref584
	db $41, $0c
	dw @song0ref569
	db $41, $0c
	dw @song0ref569
	db $41, $0a
	dw @song0ref528
	db $25, $ff, $a5, $42
	dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $00, $b5, $8c
	db $41, $0a
	dw @song0ref528
	db $00, $b5
	db $41, $0c
	dw @song0ref584
	db $41, $0a
	dw @song0ref569
	db $20, $b5, $22, $b5, $24, $b5
	db $41, $0c
	dw @song0ref526
	db $00, $b5
	db $41, $0a
	dw @song0ref584
	db $22, $d1, $24, $99, $22, $b5, $20, $ff, $a5
	db $41, $0c
	dw @song0ref526
	db $00, $b5
	db $41, $0c
	dw @song0ref584
	db $41, $0a
	dw @song0ref569
	db $20, $b5, $22, $b5, $24, $b5
	db $41, $0c
	dw @song0ref526
	db $00, $b5
	db $41, $0a
	dw @song0ref584
	db $22, $d1, $24, $99, $22, $b5, $20, $ff, $a5, $00, $b5, $8e
@song0ref689:
	db $1e, $8b, $5a, $8b, $00, $99, $1e, $99, $5a, $99, $00, $b5
	db $41, $0c
	dw @song0ref689
@song0ref704:
	db $20, $8b, $5a, $8b, $00, $99, $20, $99, $5a, $99, $00, $b5
	db $41, $0c
	dw @song0ref704
	db $41, $0c
	dw @song0ref689
	db $41, $0c
	dw @song0ref689
	db $41, $0a
	dw @song0ref569
	db $22, $ff, $a5, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $00, $b5, $8e
	db $41, $0c
	dw @song0ref569
	db $41, $0c
	dw @song0ref704
	db $41, $0a
	dw @song0ref689
	db $1d, $b5, $1e, $b5, $20, $b5, $00, $b5
	db $41, $0c
	dw @song0ref569
	db $41, $0a
	dw @song0ref704
@song0ref761:
	db $1e, $d1, $20, $99, $1e, $b5, $1d, $ff, $a5, $00, $b5
	db $41, $0c
	dw @song0ref569
	db $41, $0c
	dw @song0ref704
	db $41, $0a
	dw @song0ref689
	db $1d, $b5, $1e, $b5, $20, $b5, $00, $b5
	db $41, $0c
	dw @song0ref569
	db $41, $0a
	dw @song0ref704
	db $41, $0b
	dw @song0ref761
	db $8c
@song0ref799:
	db $1b, $8b, $5a, $8b, $00, $99, $1b, $99, $5a, $99, $00, $b5
	db $41, $0c
	dw @song0ref799
@song0ref814:
	db $1d, $8b, $5a, $8b, $00, $99, $1d, $99, $5a, $99, $00, $b5
	db $41, $0c
	dw @song0ref814
	db $41, $0c
	dw @song0ref799
	db $41, $0c
	dw @song0ref799
	db $41, $0a
	dw @song0ref689
	db $1e, $ff, $a5, $42
	dw @song0ch12loop
;@song0ch13:
;@song0ch13loop:
;	db $84
;@song0ref846:
;	db $35, $ed, $36, $b5, $38, $ed, $35, $b5, $35, $ed, $31, $b5, $35, $ed, $31, $b5, $35, $ed, $36, $b5, $38, $ed, $35, $b5
;	db $31, $ed, $33, $b5, $31, $ff, $a5
;	db $41, $1f
;	dw @song0ref846
;@song0ref880:
;	db $00, $b5, $33, $b5, $35, $b5, $36, $b5, $35, $b5, $36, $b5, $38, $ed, $35, $b5, $31, $ff, $a5
;	db $41, $0e
;	dw @song0ref880
;	db $3a, $b5, $38, $ff, $a5, $42
;	dw @song0ch13loop
;@song0ch14:
;@song0ch14loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;@song0ch15loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;@song0ch16loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;@song0ch17loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;@song0ch18loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;@song0ch19loop:
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $41, $0c
;	dw @song0ref32
;	db $42
;	dw @song0ch19loop
