; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_13_1_up:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 13. 1 - Up

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw 0 ;@song0ch11 ; epsm fm4
	dw 0 ;@song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env2, @env4, @env0 ; 00 : Bass Slap
	dw @env7, @env4
	dw @instrument_epsm_extra_patch1
	db $08,$c0,$09,$25
	dw @env2, @env4, @env6 ; 01 : Trumpet
	dw @env7, @env4
	dw @instrument_epsm_extra_patch2
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch1:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch2:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $bf,$bf,$c0,$00,$02
@env4:
	db $c0,$7f,$00,$01
@env5:
	db $7f,$00,$00
@env6:
	db $00,$bd,$be,$c0,$00,$03
@env7:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ef, $47, $ff, $ef
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $ef, $ff, $ef
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $ef, $ff, $ef
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
;@song0ch3:
;	db $ff, $ef, $ff, $ef
;@song0ch3loop:
;	db $00, $42
;	dw @song0ch3loop
@song0ch4:
	db $02, $d1, $00, $83, $02, $99, $00, $01, $a7, $00, $81, $01, $a7, $00, $01, $99, $00, $02, $99, $00, $01, $99, $00, $02
	db $99, $00, $01, $99, $00, $02, $b5, $00, $bd
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
;@song0ch5:
;	db $ff, $ef, $ff, $ef
;@song0ch5loop:
;	db $00, $42
;	dw @song0ch5loop
;@song0ch6:
;	db $ff, $ef, $ff, $ef
;@song0ch6loop:
;	db $00, $42
;	dw @song0ch6loop
;@song0ch7:
;	db $ff, $ef, $ff, $ef
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $82, $35, $8b, $00, $8d, $35, $8b, $00, $35, $8b, $35, $8b, $00, $8d, $35, $8b, $00, $8d, $37, $a7, $00, $81, $33, $a7
	db $00, $32, $99, $00, $35, $ff, $a5, $00, $c5
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $82, $32, $8b, $00, $8d, $32, $8b, $00, $32, $8b, $32, $8b, $00, $8d, $32, $8b, $00, $8d, $33, $a7, $00, $81, $30, $a7
	db $00, $2e, $99, $00, $32, $ff, $a5, $00, $c5
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $80, $16, $b5, $00, $9f, $16, $99, $00, $14, $a7, $00, $81, $14, $a7, $00, $14, $99, $00, $16, $99, $00, $11, $99, $00
	db $16, $99, $00, $11, $99, $00, $16, $ed, $00, $85
	db $5b ; halt
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
;@song0ch11:
;	db $ff, $ef, $ff, $ef
;@song0ch11loop:
;	db $00, $42
;	dw @song0ch11loop
;@song0ch12:
;	db $ff, $ef, $ff, $ef
;@song0ch12loop:
;	db $00, $42
;	dw @song0ch12loop
;@song0ch13:
;	db $ff, $ef, $ff, $ef
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $ef, $ff, $ef
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $ef, $ff, $ef
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $ef, $ff, $ef
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $ef, $ff, $ef
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $ef, $ff, $ef
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $ef, $ff, $ef
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
