; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_12_ending_theme:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 12. Ending Theme

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env5,@env6,@env7,@env0 ; 00 : Hi hat
	dw @env2,@env6,@env7,@env0 ; 01 : Longer Noise

@instruments_exp:
	dw @env9, @env6, @env0 ; 00 : 1 Long
	dw @env10, @env6
	dw @instrument_epsm_extra_patch3
	db $04,$c0,$00,$20
	dw @env3, @env6, @env0 ; 01 : Bass Rough
	dw @env10, @env6
	dw @instrument_epsm_extra_patch4
	db $20,$c0,$36,$19
	dw @env3, @env6, @env0 ; 02 : Brass 4
	dw @env10, @env6
	dw @instrument_epsm_extra_patch5
	db $35,$c0,$32,$1c
	dw @env3, @env6, @env0 ; 03 : EPSM Custom 33
	dw @env10, @env6
	dw @instrument_epsm_extra_patch6
	db $3a,$c0,$51,$18
	dw @env3, @env6, @env0 ; 04 : EPSM Custom 36
	dw @env10, @env6
	dw @instrument_epsm_extra_patch7
	db $3a,$c0,$51,$17
	dw @env3, @env6, @env8 ; 05 : Trumpet
	dw @env10, @env6
	dw @instrument_epsm_extra_patch8
	db $3a,$c0,$01,$18
	dw @env3, @env6, @env8 ; 06 : Trumpet 1
	dw @env10, @env6
	dw @instrument_epsm_extra_patch9
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch4:
	db $df,$07,$07,$20,$00,$35,$37,$df,$06,$06,$16,$00,$30,$13,$9f,$09,$06,$17,$00,$31,$0f,$9f,$06,$08,$f6,$00,$00
@instrument_epsm_extra_patch5:
	db $50,$00,$01,$4f,$00,$41,$18,$90,$00,$02,$2f,$00,$72,$28,$90,$00,$02,$1f,$00,$72,$18,$90,$80,$01,$0f,$00,$00
@instrument_epsm_extra_patch6:
	db $1e,$1f,$00,$0f,$00,$08,$24,$1e,$1f,$00,$0f,$00,$51,$22,$1e,$1f,$00,$0f,$00,$02,$0f,$10,$0f,$02,$1f,$00,$00
@instrument_epsm_extra_patch7:
	db $1e,$1f,$00,$0f,$00,$08,$23,$1e,$1f,$00,$0f,$00,$51,$22,$1e,$1f,$00,$0f,$00,$02,$22,$10,$0f,$02,$0f,$00,$00
@instrument_epsm_extra_patch8:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch9:
	db $1d,$0d,$08,$15,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c7,$c7,$c6,$c3,$c3,$c2,$c1,$00,$07
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env6:
	db $c0,$7f,$00,$01
@env7:
	db $7f,$00,$00
@env8:
	db $00,$bd,$be,$c0,$00,$03
@env9:
	db $08,$cd,$05,$cc,$02,$cc,$00,$05,$cb,$02,$ca,$03,$c9,$02,$c8,$c8,$00,$0f
@env10:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ef, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
@song0ref28:
	db $ff, $ef, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $41, $12
;	dw @song0ref28
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
@song0ch3:
	db $ff, $ef, $78
@song0ref62:
	db $80, $2e, $8d, $00, $8b, $82, $2e, $9b, $80, $2e, $8d, $00, $8b, $82, $2e, $9b
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $41, $0c
	dw @song0ref62
	db $80, $2e, $8d, $82, $2e, $99, $00, $8d, $2e, $8d, $00, $8b, $2e, $9b, $00, $ff, $ed
@song0ch3loop:
	db $00, $42
	dw @song0ch3loop
@song0ch4:
	db $9d
@song0ref137:
	db $05, $9b
@song0ref139:
	db $04, $9b, $05, $9b, $04, $9b, $05, $9b, $04, $91, $05, $81, $05, $83, $05, $91, $05, $87
	db $41, $09
	dw @song0ref139
	db $9b
	db $41, $0b
	dw @song0ref137
@song0ref164:
	db $9b, $05, $9b, $04, $9b, $05, $9b, $04, $93, $05, $85, $05, $93, $05, $85
	db $41, $09
	dw @song0ref139
	db $9b
	db $41, $0b
	dw @song0ref137
	db $41, $0f
	dw @song0ref164
	db $41, $09
	dw @song0ref139
	db $9b
	db $41, $0b
	dw @song0ref137
	db $41, $0f
	dw @song0ref164
	db $41, $09
	dw @song0ref139
	db $8d, $05, $8b, $00, $9b, $05, $8d, $00, $8b, $04, $9b, $00, $ff, $ed
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
@song0ch5:
	db $41, $0a
	dw @song0ref28
	db $9d, $80, $30, $ab, $00, $8b, $30, $8b, $00, $8d, $2e, $a9, $30, $ab, $2e, $9b, $29, $b9, $2d, $b9, $30, $b9, $33, $b9
	db $00, $9b, $32, $9b, $00, $9b, $32, $9b, $00, $8d, $31, $a9, $32, $8d, $00, $ff, $ff, $99
@song0ch5loop:
	db $00, $42
	dw @song0ch5loop
;@song0ch6:
;	db $41, $12
;	dw @song0ref28
;@song0ch6loop:
;	db $00, $42
;	dw @song0ch6loop
;@song0ch7:
;	db $41, $12
;	dw @song0ref28
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $00, $ff, $ed, $4d, $fe, $9d, $86
@song0ref294:
	db $32, $ad, $00, $89
@song0ref298:
	db $32, $8b, $00, $8d, $33, $a3, $00, $83, $30, $ab, $00, $9b, $32, $8d, $00, $8b, $32, $8b, $00, $8d, $32, $8d, $00, $8b
	db $2e, $8b, $00, $8d, $2c, $9b, $00, $8b, $30, $b9, $00, $8d, $4d, $fe, $9d
	db $41, $28
	dw @song0ref294
	db $ff, $ff, $8d, $8c, $35, $8b, $00, $8d, $3c, $8d, $35, $8b, $00, $9b, $35, $8d, $00, $8b, $3c, $8b, $35, $8d, $00, $b9
	db $9d, $0a, $9b, $00, $9b, $0a, $9b, $00, $d7, $0a, $ff, $ff, $8b
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $00, $ff, $ed, $4d, $00, $82
@song0ref388:
	db $16, $8d, $00, $8b, $16, $8b, $00, $8d, $11, $8d, $00, $8b, $11, $8b, $00, $8d, $14, $a9, $13, $9d, $14, $8b, $13, $9b
	db $41, $10
	dw @song0ref388
	db $1b, $a9, $1a, $9d, $1b, $8b, $1a, $9b, $4d, $00
	db $41, $18
	dw @song0ref388
	db $41, $10
	dw @song0ref388
	db $1b, $a9, $1a, $9d, $1b, $8b, $1a, $9b, $14, $8d, $00
@song0ref442:
	db $8b, $11, $8b, $00, $8d, $12, $8d, $00, $8b, $13, $8b, $00, $8d, $14, $8d, $14
	db $41, $0d
	dw @song0ref442
	db $11, $8d, $00, $8b, $11, $8b, $00, $8d, $15, $8d, $00, $8b, $15, $8b, $00, $8d, $18, $8d, $00, $8b, $18, $8b, $00, $8d
	db $1b, $8d, $00, $8b, $1b, $8b, $00, $8d, $9d, $0a, $9b, $00, $9b, $0a, $9b, $00, $8d, $15, $a9, $16, $8d, $00, $8b, $0a
	db $ff, $ff, $89, $4d, $00, $81
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $00, $ff, $ed, $7c, $4d, $00, $8a
@song0ref527:
	db $35, $8d, $00, $8b, $35, $8b
@song0ref533:
	db $00, $8d, $32, $8d, $00, $8b, $32, $8b, $00, $8d, $33, $a3, $00, $83, $33, $b9, $00, $8d
	db $41, $10
	dw @song0ref527
	db $38, $9b, $00, $8b, $38, $b9, $00, $8d, $4d, $00
	db $41, $18
	dw @song0ref527
	db $41, $10
	dw @song0ref527
	db $38, $9b, $00, $8b, $38, $b9, $00, $8d, $9d, $33, $ab, $00, $8b, $33, $8b, $00, $8d, $32, $a9, $33, $ab, $32, $9b, $2d
	db $b9, $30, $b9, $33, $b9, $39, $b9, $00, $9b, $35, $9b, $00, $9b, $35, $9b, $00, $8d, $34, $a9, $35, $8d, $00, $8b, $77
	db $4d, $01, $82, $0a, $ff, $ff, $8b
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $00, $ff, $ed, $7c, $4d, $00, $8a
@song0ref637:
	db $32, $8d, $00, $8b, $32, $8b, $00, $8d, $2e, $8d, $00, $8b, $2e, $8b, $00, $8d, $30, $a3, $00, $83, $30, $b9
	db $41, $0a
	dw @song0ref533
@song0ref662:
	db $2e, $8d, $00, $8b, $2e, $8b, $00, $8d, $33, $9b, $00, $8b, $33, $b9, $00, $8d, $4d, $00
	db $41, $16
	dw @song0ref637
	db $41, $0a
	dw @song0ref533
	db $41, $10
	dw @song0ref662
	db $7f
@song0ref690:
	db $9d, $84, $38, $9b, $3c, $9b, $3f, $9b, $40, $4f, $9b, $00, $8b, $40, $4f, $9d, $40, $50, $8b, $40, $4f, $9b, $40, $51
	db $ff, $ed, $40, $52, $9b, $00, $9b, $40, $52, $9b, $00, $ab, $40, $51, $a9, $40, $52, $8d, $00, $8b, $77, $4d, $ff, $82
	db $0a, $ff, $ff, $8b
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $00, $ff, $ed, $4d, $fe, $9d, $88, $32, $af, $00, $87
	db $41, $25
	dw @song0ref298
	db $32, $af, $00, $87
	db $41, $24
	dw @song0ref298
	db $7b, $4d, $fd
	db $41, $21
	dw @song0ref690
	db $ff, $ff, $99
	db $5b ; halt
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $41, $12
;	dw @song0ref28
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $41, $12
;	dw @song0ref28
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $41, $12
;	dw @song0ref28
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $41, $12
;	dw @song0ref28
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $41, $12
;	dw @song0ref28
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $41, $12
;	dw @song0ref28
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $41, $12
;	dw @song0ref28
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
