; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_14_game_over:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 14. Game Over

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env2, @env4, @env0 ; 00 : Bass Slap
	dw @env7, @env4
	dw @instrument_epsm_extra_patch1
	db $08,$c0,$09,$25
	dw @env2, @env4, @env0 ; 01 : EPSM Custom 33
	dw @env7, @env4
	dw @instrument_epsm_extra_patch2
	db $3a,$c0,$51,$18
	dw @env2, @env4, @env6 ; 02 : GHZ Trumpet Mid
	dw @env7, @env4
	dw @instrument_epsm_extra_patch3
	db $32,$c0,$71,$17

@instrument_epsm_extra_patch1:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch2:
	db $1e,$1f,$00,$0f,$00,$08,$24,$1e,$1f,$00,$0f,$00,$51,$22,$1e,$1f,$00,$0f,$00,$02,$0f,$10,$0f,$02,$1f,$00,$00
@instrument_epsm_extra_patch3:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $bf,$bf,$c0,$00,$02
@env4:
	db $c0,$7f,$00,$01
@env5:
	db $7f,$00,$00
@env6:
	db $00,$bd,$be,$c0,$00,$03
@env7:
	db $c8,$7f,$00,$00
@env8:
	db $00,$c0,$b9,$b3,$b0,$b1,$b5,$bc,$c4,$cb,$cf,$d0,$cd,$c7,$00,$01

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ff, $ff, $ab, $47, $ff, $ff, $ff, $ab, $47, $ff, $ff, $ff, $ab, $47, $ff, $ff
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ref23:
;	db $ff, $ff, $ff, $ab, $ff, $ff, $ff, $ab, $ff, $ff, $ff, $ab, $ff, $ff
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $41, $0e
;	dw @song0ref23
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
;@song0ch3:
;	db $41, $0e
;	dw @song0ref23
;@song0ch3loop:
;	db $00, $42
;	dw @song0ch3loop
@song0ch4:
@song0ref58:
	db $d5, $00, $93, $04, $fd, $00, $d3, $04, $e7
	db $41, $09
	dw @song0ref58
	db $d5, $00, $ff, $ff, $d3, $ff, $ff
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
;@song0ch5:
;	db $41, $0e
;	dw @song0ref23
;@song0ch5loop:
;	db $00, $42
;	dw @song0ch5loop
;@song0ch6:
;	db $41, $0e
;	dw @song0ref23
;@song0ch6loop:
;	db $00, $42
;	dw @song0ch6loop
;@song0ch7:
;	db $41, $0e
;	dw @song0ref23
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $b7, $7e, $82, $26, $bd, $00, $a7, $26, $a3, $00, $8d, $27, $c7, $00, $89, $24, $df, $00, $99, $81, $7c, $26, $a3, $00
	db $8d, $26, $a3, $00, $8b, $26, $a3, $00, $8d, $22, $a3, $00, $8d, $20, $c7, $00, $89, $24, $af, $00, $c9, $81, $25, $9b
	db $00, $83, $25, $8f, $24, $a3, $00, $8b, $23, $a3, $00, $8d, $22, $a5, $00, $8b, $21, $cd, $48, <(@env8), >(@env8), $ff
	db $83, $c1, $00, $ff, $bb
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $b7, $7e, $82, $26, $a9, $00, $bb, $26, $9d, $00, $93, $27, $b1, $00, $9f, $24, $c9, $00, $af, $81, $7c, $26, $8d, $00
	db $a3, $26, $8d, $00, $a1, $26, $8d, $00, $a3, $22, $8d, $00, $a3, $20, $b1, $00, $9f, $24, $99, $00, $df, $81, $25, $85
	db $00, $99, $25, $87, $00, $85, $24, $8d, $00, $a1, $23, $8d, $00, $a3, $22, $8f, $00, $a1, $21, $cd, $48, <(@env8), >(@env8)
	db $ff, $83, $ab, $00, $ff, $d1
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $81, $84, $35, $00, $7c
@song0ref273:
	db $35, $83, $00, $ab, $35, $83, $00, $ad, $32, $83, $00, $ad, $32, $83, $00, $ab, $33, $83, $00, $c7, $33, $83, $00, $f9
	db $85
	db $41, $10
	dw @song0ref273
	db $3f, $83, $00, $c7, $3f, $83
@song0ref307:
	db $00, $f9, $ff, $ff, $ff, $ab, $ff, $ff
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $81, $7c, $84
@song0ref323:
	db $32, $85, $00, $ab, $32, $85, $00, $a9, $2e, $85, $00, $ab, $2e, $85, $00, $ab, $2c, $85, $00, $c5, $30, $85, $00, $f9
	db $81
	db $41, $10
	dw @song0ref323
	db $38, $85, $00, $c5, $38, $85
	db $41, $08
	dw @song0ref307
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $81, $7c, $80
@song0ref368:
	db $16, $8d, $00, $a3, $16, $8d, $00, $a1, $11, $8d, $00, $a3, $11, $8d, $00, $a3, $14, $ad, $00, $9d, $13, $a5, $00, $97
	db $14, $85, $00, $83, $13, $9d, $00, $91, $81
	db $41, $10
	dw @song0ref368
	db $1b, $ad, $00, $9d, $1a, $a5, $00, $97, $1b, $85, $00, $83, $1a, $9d, $00, $91, $81, $16, $85, $00, $99, $16, $87, $00
	db $85, $15, $8d, $00, $a1, $14, $8d, $00, $a3, $13, $8f, $00, $a1, $13, $ff, $d1, $ab, $00 ; , $ff, $d1
	db $5b ; halt
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $81, $7c, $80
;@song0ref456:
;	db $0a, $8d, $00, $a3, $0a, $8d, $00, $a1, $05, $8d, $00, $a3, $05, $8d, $00, $a3, $08, $ad, $00, $9d, $07, $a5, $00, $97
;	db $08, $85, $00, $83, $07, $9d, $00, $91, $81
;	db $41, $10
;	dw @song0ref456
;	db $0f, $ad, $00, $9d, $0e, $a5, $00, $97, $0f, $85, $00, $83, $0e, $9d, $00, $91, $81, $0a, $85, $00, $99, $0a, $87, $00
;	db $85, $09, $8d, $00, $a1, $08, $8d, $00, $a3, $07, $8f, $00, $a1, $07, $ff, $d1, $ab, $00, $ff, $d1
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $41, $0e
;	dw @song0ref23
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $41, $0e
;	dw @song0ref23
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $41, $0e
;	dw @song0ref23
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $41, $0e
;	dw @song0ref23
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $41, $0e
;	dw @song0ref23
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $41, $0e
;	dw @song0ref23
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
