; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_08b_special_stage_beta_s1_smsgg:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 08B. Special Stage SMS (Original)

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw @song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw 0 ;@song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw @song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env9,@env10,@env16,@env0 ; 00 : blank/DPCM instureme
	dw @env12,@env10,@env14,@env0 ; 01 : Drums 1
	dw @env11,@env18,@env14,@env0 ; 02 : Hi-Hat Noise

@instruments_exp:
	dw @env7, @env10, @env0 ; 00 : 0guitar bass
	dw @env19, @env10
	dw @instrument_epsm_extra_patch3
	db $3c,$f7,$11,$20
	dw @env13, @env10, @env0 ; 01 : 1 Short Soft 1
	dw @env19, @env10
	dw @instrument_epsm_extra_patch4
	db $04,$c0,$00,$20
	dw @env7, @env10, @env0 ; 02 : Accordeon
	dw @env19, @env10
	dw @instrument_epsm_extra_patch5
	db $32,$c0,$31,$1e
	dw @env7, @env10, @env0 ; 03 : BottleBlow
	dw @env19, @env10
	dw @instrument_epsm_extra_patch6
	db $3c,$c0,$75,$00
	dw @env7, @env10, @env0 ; 04 : Celesta
	dw @env19, @env10
	dw @instrument_epsm_extra_patch7
	db $00,$c0,$13,$08
	dw @env7, @env10, @env0 ; 05 : Crash (Animatics)
	dw @env19, @env10
	dw @instrument_epsm_extra_patch8
	db $3c,$c0,$7f,$00
	dw @env5, @env10, @env0 ; 06 : d-Hi-Hat 1
	dw @env19, @env10
	dw @instrument_epsm_extra_patch9
	db $38,$c0,$00,$00
	dw @env7, @env2, @env15 ; 07 : Percusion Snare 2
	dw @env19, @env10
	dw @instrument_epsm_extra_patch10
	db $3a,$c0,$01,$00

@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$09,$00,$20,$00,$00,$00,$00,$0a,$00,$40,$20,$5f,$00,$00,$07,$00,$31,$00,$1f,$00,$00,$07,$0b,$00
@instrument_epsm_extra_patch4:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch5:
	db $12,$05,$00,$17,$00,$37,$15,$0f,$08,$00,$28,$00,$72,$34,$0a,$09,$03,$29,$00,$02,$00,$8b,$16,$00,$19,$00,$00
@instrument_epsm_extra_patch6:
	db $12,$0a,$00,$15,$00,$03,$29,$59,$0d,$00,$35,$00,$32,$18,$8c,$8d,$00,$55,$00,$01,$00,$4c,$84,$00,$25,$00,$00
@instrument_epsm_extra_patch7:
	db $53,$01,$1b,$40,$00,$71,$11,$5b,$03,$1a,$06,$00,$3b,$22,$1d,$0f,$1f,$f8,$00,$71,$00,$1f,$00,$05,$06,$00,$30
@instrument_epsm_extra_patch8:
	db $1f,$07,$00,$40,$00,$13,$00,$1f,$88,$00,$f4,$00,$71,$00,$1f,$14,$06,$33,$00,$07,$00,$9f,$19,$06,$a4,$00,$00
@instrument_epsm_extra_patch9:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$0f,$05,$1f,$13,$0c,$9f,$00,$00
@instrument_epsm_extra_patch10:
	db $9f,$00,$10,$00,$0b,$00,$00,$df,$80,$08,$08,$0f,$00,$00,$5f,$00,$08,$09,$0f,$00,$00,$1f,$10,$10,$08,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $c3,$c9,$c5,$c7,$c6,$00,$04
@env3:
	db $c0,$c4,$c7,$00,$00
@env4:
	db $c0,$c4,$c0,$00,$00
@env5:
	db $00,$cc,$7f,$00,$02
@env6:
	db $c0,$c7,$c0,$00,$00
@env7:
	db $00,$cf,$7f,$00,$02
@env8:
	db $bf,$bf,$c0,$00,$02
@env9:
	db $00,$cf,$ce,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$00,$09
@env10:
	db $c0,$7f,$00,$01
@env11:
	db $00,$c8,$c6,$c5,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$0b
@env12:
	db $00,$ca,$c6,$c4,$c3,$c2,$c1,$c0,$00,$07
@env13:
	db $00,$ce,$cf,$02,$ce,$ce,$cd,$cd,$cc,$00,$08
@env14:
	db $7f,$00,$00
@env15:
	db $80,$c0,$a8,$00,$01
@env16:
	db $c2,$7f,$00,$00
@env17:
	db $00,$c0,$be,$bd,$be,$c0,$c2,$c3,$c2,$00,$01
@env18:
	db $c0,$c1,$00,$01
@env19:
	db $c8,$7f,$00,$00
@env20:
	db $c0,$c3,$c8,$00,$00
@env21:
	db $c0,$c3,$c0,$00,$00
@env22:
	db $c0,$c5,$c0,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ch1loop:
;@song0ref104:
;	db $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
;	db $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
;	db $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $42
;	dw @song0ch1loop
@song0ch2:
@song0ch2loop:
	db $80
@song0ref173:
	db $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $20, $99, $2c, $99, $20, $99, $2c, $99
	db $20, $99, $2c, $99, $20, $99, $2c, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99, $1b, $99, $27, $99
	db $20, $99, $2c, $99, $20, $99, $2c, $99, $20, $99, $2c, $99, $20, $99, $2c, $99
	db $41, $40
	dw @song0ref173
@song0ref240:
	db $1f, $99, $2b, $99, $1f, $99, $2b, $99, $1f, $99, $2b, $99, $1f, $99, $2b, $99, $18, $99, $24, $99, $18, $99, $24, $99
	db $18, $99, $24, $99, $18, $99, $24, $99, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29, $99, $1d, $99, $29, $99
	db $22, $99, $2e, $99, $23, $99, $2f, $99, $24, $99, $30, $99, $26, $99, $32, $99
	db $41, $40
	dw @song0ref173
	db $41, $40
	dw @song0ref173
	db $41, $40
	dw @song0ref240
	db $41, $40
	dw @song0ref173
	db $41, $30
	dw @song0ref173
	db $22, $8b, $00, $fb, $22, $99, $22, $99, $22, $99, $42
	dw @song0ch2loop
@song0ch3:
@song0ch3loop:
	db $84
@song0ref334:
	db $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b
	db $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b, $82, $2a, $8b, $84
	db $2f, $8b
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $41, $28
	dw @song0ref334
	db $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b
	db $82, $2a, $8b, $84, $2f, $8b, $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $00, $ff, $89, $82, $2a, $8b, $84, $2f
	db $8b, $2f, $8b, $2f, $8b, $82, $2a, $8b, $84, $2f, $8b, $42
	dw @song0ch3loop
;@song0ch4:
;@song0ch4loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch4loop
;@song0ch5:
;@song0ch5loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch5loop
;@song0ch6:
;@song0ch6loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch6loop
@song0ch7:
@song0ch7loop:
	db $82
	db $41, $40
	dw @song0ref173
	db $41, $40
	dw @song0ref173
	db $41, $40
	dw @song0ref240
	db $41, $40
	dw @song0ref173
	db $41, $40
	dw @song0ref173
	db $41, $40
	dw @song0ref240
	db $41, $40
	dw @song0ref173
	db $41, $30
	dw @song0ref173
	db $22, $8b, $00, $fb, $22, $99, $22, $99, $22, $99, $42
	dw @song0ch7loop
@song0ch8:
@song0ch8loop:
@song0ref576:
	db $7f
@song0ref577:
	db $50, $f8, $80, $8a, $29, $99, $7b
@song0ref584:
	db $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c
	db $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $29, $8b
	db $29, $8b
	db $41, $28
	dw @song0ref584
	db $41, $28
	dw @song0ref584
	db $8e, $29, $8b, $8c, $29, $8b
	db $41, $2a
	dw @song0ref576
	db $41, $28
	dw @song0ref584
	db $41, $28
	dw @song0ref584
	db $8e, $29, $8b, $8c, $29, $8b
	db $41, $2a
	dw @song0ref576
@song0ref664:
	db $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c
	db $29, $8b, $7f, $50, $f8, $80, $8a, $29, $99, $7b, $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c
	db $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $7f, $50
	db $f8, $80, $8a, $29, $99, $7f, $8e, $29, $8b, $8c, $29, $8b, $50, $f8, $80, $8a, $29, $99, $7f, $8e, $29, $8b, $8c, $29
	db $8b, $50, $f8, $80, $8a, $29, $99, $7f, $8e, $29, $8b, $8c, $29, $8b, $50, $f8, $80, $8a, $29, $99, $7f, $8e, $29, $8b
	db $8c, $29, $8b
	db $41, $2a
	dw @song0ref577
	db $41, $28
	dw @song0ref584
	db $41, $28
	dw @song0ref584
	db $8e, $29, $8b, $8c, $29, $8b
	db $41, $2a
	dw @song0ref576
	db $41, $28
	dw @song0ref584
	db $41, $28
	dw @song0ref584
	db $8e, $29, $8b, $8c, $29, $8b
	db $41, $2a
	dw @song0ref576
	db $41, $4a
	dw @song0ref664
	db $41, $2a
	dw @song0ref577
	db $41, $28
	dw @song0ref584
	db $41, $28
	dw @song0ref584
	db $8e, $29, $8b, $8c, $29, $8b
	db $41, $2a
	dw @song0ref576
	db $41, $28
	dw @song0ref584
	db $8e, $29, $8b, $8c, $29, $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $00, $ff, $89, $8e, $29, $8b, $8c, $29
	db $8b, $29, $8b, $29, $8b, $8e, $29, $8b, $8c, $29, $8b, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $7a, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $88
@song0ref901:
	db $26, $b5, $23, $b5, $24, $b5, $26, $b5, $24, $99, $24, $99, $2b, $8b, $2c, $8b, $2b, $8b, $27, $8b, $00, $8b, $27, $8b
	db $24, $8b, $00, $8b, $1f, $8b, $00, $8b, $1b, $8b, $00, $8b, $29, $b5, $1d, $b5, $1f, $b5, $21, $b5, $22, $b5, $20, $b5
	db $1f, $8b, $20, $8b, $1f, $8b, $1d, $8b, $1d, $8b, $1b, $8b, $1d, $8b, $1b, $8b, $00, $ff, $dd, $ff, $df, $ff, $df, $ff
	db $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df
	db $41, $51
	dw @song0ref901
	db $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $79, $84
@song0ref991:
	db $3a, $b5, $48, <(@env17), >(@env17), $d3, $48, <(@env0), >(@env0), $49, $37, $8b, $3a, $8b, $3a, $8b, $37, $8b, $3c, $8b
	db $3a, $8b, $33, $8b, $00, $8b, $33, $8b, $00, $8b, $33, $8b, $30, $8b, $00, $8b, $33, $8b, $00, $99, $30, $8b, $00, $8b
	db $33, $8b, $00, $8b, $35, $8b, $00, $8b, $3a, $b5, $48, <(@env17), >(@env17), $d3, $48, <(@env0), >(@env0), $49, $37, $8b
	db $3a, $8b, $3a, $8b, $37, $8b, $3c, $8b, $3a, $8b, $3f, $8b, $00, $a7, $3c, $8b, $00, $99, $38, $8b, $3a, $8b, $38, $8b
	db $00, $8b, $3c, $8b, $00, $99, $37, $8b, $00, $8b
	db $41, $44
	dw @song0ref991
@song0ref1092:
	db $40, $4e, $8b, $00, $8b, $40, $4e, $8b, $40, $4d, $8b, $00, $8b, $3f, $8b, $3c, $8b, $00, $99, $9b, $37, $99, $38, $8b
	db $37, $8b, $37, $8b, $38, $8b, $3b, $8b, $37, $8b, $3b, $8b, $37, $8b, $3c, $8b, $3b, $8b, $3e, $8b, $3b, $8b, $3f, $8b
	db $00, $a7, $3e, $8b, $00, $99, $3c, $8b, $00, $8b, $3c, $8b, $00, $8b, $3e, $8b, $3c, $8b, $00, $8b, $37, $8b, $00, $8b
	db $9b, $35, $99, $37, $8b, $00, $8b, $35, $8b, $00, $8b, $3c, $8b, $00, $8b, $3c, $8b, $00, $8b, $3e, $8b, $00, $8b, $3c
	db $8b, $00, $8b, $3a, $b5, $48, <(@env17), >(@env17), $d3, $48, <(@env0), >(@env0), $49, $3a, $8b, $37, $8b, $3c, $8b, $3a
	db $8b, $3e, $8b, $3c, $8b
	db $41, $54
	dw @song0ref991
	db $41, $44
	dw @song0ref991
	db $41, $6f
	dw @song0ref1092
@song0ref1222:
	db $3f, $8b, $00, $8b, $3f, $8b, $00, $8b, $3f, $8b, $00, $b5, $40, $57, $81, $40, $59, $40, $57, $81, $40, $59, $81, $00
	db $8b, $40, $57, $81, $40, $59, $40, $57, $81, $40, $59, $81, $40, $57, $81, $40, $59, $81, $40, $57, $40, $59, $81, $00
	db $8b, $40, $57, $81, $40, $59, $81, $00, $40, $57, $81, $40, $59, $83, $00, $85, $3f, $8b, $00, $8b, $3f, $8b, $00, $8b
	db $3f, $8b, $00, $99, $40, $54, $81, $40, $52, $40, $54, $81, $40, $52, $81, $00, $8b, $40, $59, $81, $40, $57, $40, $59
	db $81, $40, $57, $81, $00, $8b, $40, $59, $81, $40, $57, $40, $59, $81, $40, $57, $81, $40, $59, $81, $40, $57, $81, $40
	db $59, $40, $57, $81, $00, $8b, $40, $54, $81, $40, $52, $81, $40, $54, $40, $52, $81, $00, $8b
	db $41, $67
	dw @song0ref1222
	db $41, $67
	dw @song0ref1222
	db $3f, $8b, $00, $8b, $3f, $8b, $00, $8b, $3f, $8b, $00, $ed, $30, $8b, $2f, $8b, $2e, $8b, $00, $99, $4f, $ed, $46, $41
	db $99, $4f, $f2, $41, $3c, $99, $4f, $f5, $3c, $37, $99, $00, $ed, $42
	dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $78, $86
@song0ref1410:
	db $2b, $99, $27, $8b, $2b, $8b, $33, $8b, $27, $8b, $32, $8b, $33, $8b, $32, $8b, $27, $8b, $33, $8b, $27, $8b, $2b, $8b
	db $27, $8b, $2b, $99, $2b, $99, $27, $8b, $2b, $8b, $30, $8b, $24, $8b, $2e, $8b, $2c, $8b, $2e, $8b, $2c, $8b, $00, $8b
	db $2c, $8b, $24, $8b, $2c, $8b, $24, $8b, $2c, $8b
	db $41, $3a
	dw @song0ref1410
	db $41, $3a
	dw @song0ref1410
	db $41, $3a
	dw @song0ref1410
	db $41, $40
	dw @song0ref901
	db $41, $3a
	dw @song0ref1410
	db $41, $3a
	dw @song0ref1410
	db $41, $3a
	dw @song0ref1410
	db $41, $3a
	dw @song0ref1410
	db $41, $40
	dw @song0ref901
@song0ref1495:
	db $7c, $1b, $8b, $1f, $8b, $22, $8b, $27, $8b, $33, $8b, $2e, $8b, $32, $8b, $33, $8b, $78, $33, $8b, $2e, $8b, $32, $8b
	db $33, $8b, $73, $33, $8b, $2e, $8b, $32, $8b, $33, $8b, $7c, $20, $8b, $24, $8b, $27, $8b, $2b, $8b, $2c, $8b, $27, $8b
	db $2b, $8b, $2c, $8b, $78, $2c, $8b, $27, $8b, $2b, $8b, $2c, $8b, $73, $2c, $8b, $27, $8b, $2b, $8b, $2c, $8b
	db $41, $40
	dw @song0ref1495
	db $41, $40
	dw @song0ref1495
	db $7c, $1b, $8b, $1f, $8b, $22, $8b, $27, $8b, $33, $8b, $2e, $8b, $32, $8b, $33, $8b, $78, $33, $8b, $2e, $8b, $32, $8b
	db $33, $8b, $73, $33, $8b, $2e, $8b, $32, $8b, $33, $8b, $7c, $22, $8b, $26, $8b, $2b, $8b, $2d, $8b, $2e, $8b, $22, $8b
	db $2d, $8b, $2e, $8b, $77, $2e, $8b, $22, $8b, $2d, $8b, $2e, $8b, $73, $2e, $8b, $22, $8b, $2d, $8b, $00, $8b, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $7c, $80
@song0ref1647:
	db $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $14, $99, $20, $99, $14, $99, $20, $99
	db $14, $99, $20, $99, $14, $99, $20, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99, $0f, $99, $1b, $99
	db $14, $99, $20, $99, $14, $99, $20, $99, $14, $99, $20, $99, $14, $99, $20, $99
	db $41, $40
	dw @song0ref1647
@song0ref1714:
	db $13, $99, $1f, $99, $13, $99, $1f, $99, $13, $99, $1f, $99, $13, $99, $1f, $99, $0c, $99, $18, $99, $0c, $99, $18, $99
	db $0c, $99, $18, $99, $0c, $99, $18, $99, $11, $99, $1d, $99, $11, $99, $1d, $99, $11, $99, $1d, $99, $11, $99, $1d, $99
	db $16, $99, $22, $99, $17, $99, $23, $99, $18, $99, $24, $99, $1a, $99, $26, $99
	db $41, $40
	dw @song0ref1647
	db $41, $40
	dw @song0ref1647
	db $41, $40
	dw @song0ref1714
	db $41, $40
	dw @song0ref1647
	db $41, $30
	dw @song0ref1647
	db $16, $8b, $00, $fb, $16, $99, $16, $99, $16, $99, $42
	dw @song0ch12loop
;@song0ch13:
;@song0ch13loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;@song0ch14loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;@song0ch15loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;@song0ch16loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;@song0ch17loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;@song0ch18loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;@song0ch19loop:
;	db $41, $40
;	dw @song0ref104
;	db $42
;	dw @song0ch19loop
