; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_07_scrap_brain_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 07. Scrap Brain Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env8,@env9,@env11,@env0 ; 00 : Hi hat
	dw @env2,@env9,@env11,@env0 ; 01 : Longer Noise

@instruments_exp:
	dw @env10, @env9, @env0 ; 00 : 1 Fade
	dw @env14, @env9
	dw @instrument_epsm_extra_patch3
	db $04,$c0,$00,$20
	dw @env13, @env9, @env0 ; 01 : 1 Long
	dw @env14, @env9
	dw @instrument_epsm_extra_patch4
	db $04,$c0,$00,$20
	dw @env3, @env9, @env0 ; 02 : 1 short
	dw @env14, @env9
	dw @instrument_epsm_extra_patch5
	db $04,$c0,$00,$20
	dw @env5, @env9, @env6 ; 03 : 1-Organ 2 L
	dw @env14, @env9
	dw @instrument_epsm_extra_patch6
	db $34,$80,$11,$21
	dw @env5, @env9, @env6 ; 04 : 1-Organ 2 R
	dw @env14, @env9
	dw @instrument_epsm_extra_patch7
	db $34,$40,$11,$21
	dw @env5, @env9, @env4 ; 05 : 1-Synth Voice
	dw @env14, @env9
	dw @instrument_epsm_extra_patch8
	db $04,$c0,$72,$26
	dw @env5, @env9, @env0 ; 06 : Bass 3
	dw @env14, @env9
	dw @instrument_epsm_extra_patch9
	db $00,$c0,$00,$7f
	dw @env5, @env9, @env0 ; 07 : Bass Slap
	dw @env14, @env9
	dw @instrument_epsm_extra_patch10
	db $08,$c0,$09,$25
	dw @env5, @env9, @env12 ; 08 : Trumpet 1
	dw @env14, @env9
	dw @instrument_epsm_extra_patch11
	db $3a,$c0,$01,$18
	dw @env5, @env9, @env0 ; 09 : Trumpet 2 R
	dw @env14, @env9
	dw @instrument_epsm_extra_patch12
	db $3a,$41,$12,$1d
	dw @env5, @env9, @env12 ; 0a : Trumpet 3 L
	dw @env14, @env9
	dw @instrument_epsm_extra_patch13
	db $32,$80,$01,$17
	dw @env5, @env9, @env12 ; 0b : Trumpet 3 R
	dw @env14, @env9
	dw @instrument_epsm_extra_patch14
	db $32,$40,$01,$17

@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch4:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch5:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch6:
	db $42,$04,$05,$58,$00,$21,$12,$1c,$80,$03,$08,$00,$32,$1f,$06,$04,$00,$58,$08,$71,$18,$03,$80,$03,$08,$00,$08
@instrument_epsm_extra_patch7:
	db $42,$04,$05,$58,$00,$21,$12,$1c,$80,$03,$08,$00,$32,$1f,$06,$04,$00,$58,$08,$71,$18,$03,$80,$03,$08,$00,$08
@instrument_epsm_extra_patch8:
	db $5f,$02,$00,$51,$00,$72,$14,$1f,$80,$03,$03,$00,$12,$26,$1f,$04,$00,$51,$00,$12,$14,$1a,$8e,$03,$03,$00,$08
@instrument_epsm_extra_patch9:
	db $1f,$00,$00,$23,$00,$70,$20,$1f,$00,$04,$23,$00,$10,$1f,$5f,$05,$04,$23,$00,$20,$0b,$5f,$0a,$03,$25,$00,$00
@instrument_epsm_extra_patch10:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch11:
	db $1d,$0d,$08,$15,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch12:
	db $1b,$00,$00,$3f,$00,$01,$27,$19,$04,$00,$0f,$00,$01,$26,$0f,$00,$00,$0f,$00,$02,$0d,$16,$03,$03,$4f,$00,$0b
@instrument_epsm_extra_patch13:
	db $12,$1f,$08,$14,$00,$01,$16,$1f,$0d,$02,$05,$00,$02,$3c,$12,$00,$00,$05,$00,$02,$12,$19,$07,$02,$65,$00,$00
@instrument_epsm_extra_patch14:
	db $12,$1f,$08,$14,$00,$01,$16,$1f,$0d,$02,$05,$00,$02,$3c,$12,$00,$00,$05,$00,$02,$12,$19,$07,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c7,$c7,$c6,$c3,$c3,$c2,$c1,$00,$07
@env3:
	db $00,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c8,$c7,$c6,$00,$0a
@env4:
	db $00,$c0,$1c,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env5:
	db $00,$cf,$7f,$00,$02
@env6:
	db $00,$c0,$1c,$c0,$c2,$c4,$c5,$c4,$c2,$c0,$be,$bc,$bb,$bc,$be,$00,$03
@env7:
	db $bf,$bf,$c0,$00,$02
@env8:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env9:
	db $c0,$7f,$00,$01
@env10:
	db $00,$cd,$02,$cc,$02,$cb,$02,$ca,$00,$07
@env11:
	db $7f,$00,$00
@env12:
	db $00,$bd,$be,$c0,$00,$03
@env13:
	db $08,$cd,$05,$cc,$02,$cc,$00,$05,$cb,$02,$ca,$03,$c9,$02,$c8,$c8,$00,$0f
@env14:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid)
;@song0ref5:
;	db $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df
;	db $47, $ff, $ff, $ff, $df, $47
;	db $41, $18
;	dw @song0ref5
;	db $47
;	db $41, $18
;	dw @song0ref5
;	db $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ch1loop:
@song0ref46:
	db $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch1loop
;@song0ch2:
;@song0ch2loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch2loop
@song0ch3:
@song0ch3loop:
	db $80, $32, $8d, $32, $8b, $00, $ab, $32, $8b, $00, $8b, $32, $8d, $00, $b9, $32, $8d, $00, $a9, $32, $8d, $00, $a9, $32
	db $8d, $00, $a9, $32, $8d, $00, $e5
@song0ref124:
	db $32, $8d, $32, $8b, $82, $32, $9b, $80, $32, $8d, $32, $8b, $82, $32, $9b, $80, $32, $8d, $32, $8b, $82, $32, $9b, $80
	db $32, $8d, $32, $8b, $82, $32, $9b, $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $80
	db $41, $18
	dw @song0ref124
	db $42
	dw @song0ch3loop
@song0ch4:
@song0ch4loop:
	db $05, $8d, $05, $8b, $00, $8b, $05, $8d, $00, $8d, $05, $8b, $05, $8b, $05, $8d, $00, $b9, $04, $8d, $00, $e5, $04, $8d
	db $00, $a9, $04, $8d, $00, $8b, $05, $8b, $00, $8d, $05, $8d, $00, $8b
@song0ref329:
	db $05, $8b, $05, $8d
@song0ref333:
	db $04, $9b, $00, $9b, $05, $9b, $00, $9b, $04, $9b, $00, $9b, $05, $9b, $00, $9b, $04, $9b, $00, $9b, $04, $81, $03, $97
	db $02, $9b, $04, $81, $03, $97, $02, $9b, $04, $81, $03, $97, $02, $9b
	db $41, $26
	dw @song0ref333
@song0ref374:
	db $04, $9b, $00, $9b, $05, $9b, $00, $9b, $04, $9b, $00, $9b, $05, $9b, $00, $9b, $04, $9b, $00, $9b, $05, $9b, $00, $9b
	db $04, $9b, $00, $9b, $05, $9b, $02, $8b, $02, $8d, $04, $9b, $00, $9b, $05, $9b, $00, $9b, $04, $9b, $00, $9b, $05, $9b
	db $00, $9b, $04, $9b, $02, $9b, $04, $81, $03, $97, $02, $9b, $04, $81, $03, $97, $02, $9b, $04, $81, $03, $97
	db $41, $2a
	dw @song0ref329
	db $41, $26
	dw @song0ref333
	db $41, $46
	dw @song0ref374
@song0ref453:
	db $05, $8b, $05, $8d, $05, $8d, $05, $8b, $04, $8b, $04, $8d, $04, $8d, $04, $8b, $05, $8b, $05, $8d, $04, $8d, $04, $8b
	db $04, $8b, $04, $8d, $05, $8d, $05, $8b
	db $41, $20
	dw @song0ref453
	db $05, $8b, $05, $8d
@song0ref492:
	db $04, $8d, $00, $a9, $05, $8d, $00, $99, $04, $8d, $00, $8d, $04, $8b, $02, $8b, $03, $8d, $02, $9b, $00, $9b, $04, $8d
	db $00, $99, $05, $8d, $05, $8d, $00, $99, $04, $8d, $00, $8d, $04, $8b, $02, $8b, $03, $8d, $02, $9b, $00, $9b
	db $41, $19
	dw @song0ref492
	db $a9, $05, $8d, $00, $99, $04, $8d, $00, $8d, $02, $8b, $03, $9b, $02, $9b, $03, $9b
	db $41, $2e
	dw @song0ref492
	db $41, $19
	dw @song0ref492
	db $a9, $05, $8d, $00, $99, $04, $8d, $00, $8d, $02, $8b, $03, $9b, $02, $9b, $03, $9b
	db $41, $2e
	dw @song0ref492
	db $41, $19
	dw @song0ref492
	db $a9, $05, $8d, $00, $99, $04, $8d, $00, $8d, $02, $8b, $03, $9b, $02, $9b, $03, $9b
	db $41, $2e
	dw @song0ref492
	db $41, $19
	dw @song0ref492
	db $a9, $05, $8d, $00, $99, $04, $8d, $00, $8d, $02, $8b, $03, $9b, $02, $9b, $03, $9b, $42
	dw @song0ch4loop
@song0ch5:
@song0ch5loop:
	db $80, $29, $8d, $29, $8b, $00, $8b, $29, $8d, $00, $8d, $29, $8b, $29, $8b, $27, $ff, $ff, $f5, $00, $ff, $ff, $ff, $dd
	db $41, $18
	dw @song0ref46
	db $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $00, $b9, $82
@song0ref669:
	db $29, $9b, $00, $8b, $29, $8d, $00, $ff, $b1, $2f, $9b, $00, $8b, $2f, $8d, $00, $f5, $bb, $2e, $9b, $00, $8b, $2e, $8d
	db $00, $ff, $b1, $2a, $b9, $00, $8d, $2a, $8b, $00, $9b, $2a, $8d, $00, $a9, $00, $b9
	db $41, $19
	dw @song0ref669
	db $f5, $2a, $b9, $00, $9b, $2a, $ff, $93, $00, $b9
	db $41, $29
	dw @song0ref669
	db $41, $19
	dw @song0ref669
	db $f5, $2a, $b9, $00, $9b, $2a, $ff, $93, $42
	dw @song0ch5loop
@song0ch6:
@song0ch6loop:
	db $80, $25, $8d, $25, $8b, $00, $8b, $25, $8d, $00, $8d, $25, $8b, $25, $8b, $24, $ff, $ff, $f5, $84
@song0ref761:
	db $3a, $85, $00, $85, $3a, $83, $00, $85, $40, $4d, $83, $00, $85, $3a, $85, $00, $85, $3f, $85, $00, $85, $3a, $83, $00
	db $85, $3d, $83, $00, $85, $3a, $85, $00, $85
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
@song0ref803:
	db $38, $85, $00, $85, $38, $83, $00, $85, $3f, $85, $00, $83, $38, $85, $00, $85, $3d, $85, $00, $85, $38, $83, $00, $85
	db $3c, $85, $00, $83, $38, $85, $00, $85
	db $41, $20
	dw @song0ref803
	db $41, $20
	dw @song0ref803
	db $41, $20
	dw @song0ref803
@song0ref844:
	db $3a, $85, $00, $85, $3a, $83, $00, $85, $40, $4c, $85, $00, $83, $3a, $85, $00, $85, $3f, $85, $00, $85, $3a, $83, $00
	db $85, $3d, $85, $00, $83, $3a, $85, $00, $85
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref803
	db $41, $20
	dw @song0ref803
	db $41, $20
	dw @song0ref803
	db $41, $20
	dw @song0ref803
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref844
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $41, $20
	dw @song0ref761
	db $ff, $ff, $ff, $df
@song0ref950:
	db $3d, $85, $00, $85, $3d, $83, $00, $85, $40, $50, $85, $00, $83, $3d, $85, $00, $85, $40, $4e, $85, $00, $85, $3d, $83
	db $00, $85, $40, $4d, $85, $00, $83, $3d, $85, $00, $85
	db $41, $20
	dw @song0ref950
@song0ref988:
	db $3b, $85, $00, $85, $3b, $83, $00, $85, $40, $4e, $85, $00, $83, $3b, $85, $00, $85, $40, $4c, $85, $00, $85, $3b, $83
	db $00, $85, $3e, $85, $00, $83, $3b, $85, $00, $85
	db $41, $20
	dw @song0ref988
@song0ref1025:
	db $3a, $85, $00, $85, $3a, $83, $00, $85, $40, $4d, $85, $00, $83, $3a, $85, $00, $85, $3f, $85, $00, $85, $3a, $83, $00
	db $85, $3d, $85, $00, $83, $3a, $85, $00, $85
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref950
	db $41, $20
	dw @song0ref950
	db $41, $20
	dw @song0ref988
	db $41, $20
	dw @song0ref988
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref950
	db $41, $20
	dw @song0ref950
	db $41, $20
	dw @song0ref988
	db $41, $20
	dw @song0ref988
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref950
	db $41, $20
	dw @song0ref950
	db $41, $20
	dw @song0ref988
	db $41, $20
	dw @song0ref988
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $41, $20
	dw @song0ref1025
	db $42
	dw @song0ch6loop
;@song0ch7:
;@song0ch7loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch7loop
@song0ch8:
@song0ch8loop:
	db $00, $ff, $b1, $90, $35, $8d, $33, $8b, $31, $8b, $30, $8d, $36, $8d, $35, $8b, $33, $8b, $31, $8d, $38, $8d, $36, $8b
	db $35, $8b, $33, $8d, $3a, $8d, $38, $8b, $36, $8b, $35, $8d, $3c, $8d, $3a, $8b, $38, $8b, $36, $8d, $4d, $fd, $86
@song0ref1203:
	db $3a, $ff, $93, $38, $9b, $36, $9b, $38, $9b, $35, $ff, $ed, $38, $ff, $93, $36, $9b, $35, $9b, $36, $9b, $33, $ff, $ed
	db $36, $ff, $93, $34, $9b, $33, $9b, $34, $9b, $31, $f5, $33, $f5, $35, $8d, $36, $8b, $35, $ff, $ff, $ff, $bf, $4d, $fd
	db $41, $2e
	dw @song0ref1203
	db $8c, $16, $8d, $16, $8b, $15, $8b, $15, $8d, $14, $8d, $14, $8b, $16, $8b, $16, $8d, $15, $8d, $15, $8b, $14, $8b, $14
	db $c9, $16, $8d, $16, $8b, $15, $8b, $15, $8d, $14, $8d, $14, $8b, $16, $8b, $16, $8d, $15, $8d, $15, $8b, $14, $8b, $14
	db $8d, $00, $b9, $86
@song0ref1306:
	db $38, $ff, $93, $35, $9b, $31, $9b, $3d, $9b, $3b, $b9, $3d, $9b, $3b, $b9, $38, $9b, $3b, $9b, $3a, $9b, $ff, $95, $35
	db $9b, $36, $9b, $38, $d7, $3a, $9b, $38, $d7, $35, $b9
	db $41, $1c
	dw @song0ref1306
	db $ff, $ff, $8b
	db $41, $23
	dw @song0ref1306
	db $41, $1c
	dw @song0ref1306
	db $ff, $ff, $8b, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $8e, $16, $8d, $18, $8b, $00, $8b, $19, $8d, $00, $8d, $1b, $8b, $1d, $8b, $20, $ab, $14, $9b, $20, $9b, $14, $9b, $20
	db $9b, $14, $9b, $20, $9b, $14, $9b, $20, $9b, $14, $9b, $20, $9b, $14, $9b
@song0ref1399:
	db $22, $8d, $22, $8b, $1d, $8b, $1d, $8d, $20, $8d, $20, $8b, $1d, $8b, $1d, $8d, $22, $8d, $22, $8b, $1d, $8b, $1d, $8d
	db $20, $8d, $20, $8b, $1d, $8b, $1d, $8d
	db $41, $20
	dw @song0ref1399
@song0ref1434:
	db $20, $8d, $20, $8b, $1b, $8b, $1b, $8d, $1e, $8d, $1e, $8b, $1b, $8b, $1b, $8d, $20, $8d, $20, $8b, $1b, $8b, $1b, $8d
	db $1e, $8d, $1e, $8b, $1b, $8b, $1b, $8d
	db $41, $20
	dw @song0ref1434
@song0ref1469:
	db $1e, $8d, $1e, $8b, $19, $8b, $19, $8d, $1c, $8d, $1c, $8b, $19, $8b, $19, $8d, $1e, $8d, $1e, $8b, $19, $8b, $19, $8d
	db $1c, $8d, $1c, $8b, $19, $8b, $19, $8d
	db $41, $20
	dw @song0ref1469
	db $41, $20
	dw @song0ref1399
	db $41, $20
	dw @song0ref1399
	db $41, $20
	dw @song0ref1399
	db $41, $20
	dw @song0ref1399
	db $41, $20
	dw @song0ref1434
	db $41, $20
	dw @song0ref1434
	db $41, $20
	dw @song0ref1469
	db $41, $20
	dw @song0ref1469
	db $41, $20
	dw @song0ref1399
	db $41, $20
	dw @song0ref1399
@song0ref1534:
	db $22, $8d, $22, $8b, $21, $8b, $21, $8d, $20, $8d, $20, $8b, $22, $8b, $22, $8d, $21, $8d, $21, $8b, $20, $8b, $20, $8d
	db $20, $8d, $20, $8b, $00, $9b
	db $41, $18
	dw @song0ref1534
	db $00, $b9
@song0ref1569:
	db $19, $8d, $19, $8b, $14, $8b, $14, $8d, $16, $8d, $16, $8b, $14, $8b, $14, $8d, $19, $8d, $19, $8b, $14, $8b, $14, $8d
	db $16, $8d, $16, $8b, $14, $8b, $14, $8d, $1f, $8d, $1f, $8b, $1a, $8b, $1a, $8d, $1c, $8d, $1c, $8b, $1a, $8b, $1a, $8d
	db $1f, $8d, $1f, $8b, $1a, $8b, $1a, $8d, $1c, $8d, $1c, $8b, $1a, $8b, $1a, $8d, $1e, $8d, $1e, $8b, $19, $8b, $19, $8d
	db $1b, $8d, $1b, $8b, $19, $8b, $19, $8d, $1e, $8d, $1e, $8b, $19, $8b, $19, $8d, $1b, $8d, $1b, $8b, $19, $8b, $19, $8d
	db $20, $8d, $20, $8b, $1b, $8b, $1b, $8d, $1d, $8d, $1d, $8b, $1b, $8b, $1b, $8d, $20, $8d, $20, $8b, $1b, $8b, $1b, $8d
	db $1d, $8d, $1d, $8b, $1b, $8b, $1b, $8d
	db $41, $80
	dw @song0ref1569
	db $41, $80
	dw @song0ref1569
	db $41, $80
	dw @song0ref1569
	db $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $8a, $2e, $8d, $30, $8b, $00, $8b, $31, $8d, $00, $8d, $33, $8b, $35, $8b, $38, $ab, $5a, $d7, $00, $ff, $ed, $4d, $03
	db $88
	db $41, $2e
	dw @song0ref1203
	db $4d, $03
	db $41, $2e
	dw @song0ref1203
	db $00, $ff, $ff, $ff, $dd
	db $41, $23
	dw @song0ref1306
	db $41, $1c
	dw @song0ref1306
	db $ff, $ff, $8b
	db $41, $23
	dw @song0ref1306
	db $41, $1c
	dw @song0ref1306
	db $ff, $ff, $8b, $42
	dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $4b, $94, $29, $8d, $29, $8b, $00, $8b, $29, $8d, $00, $8d, $29, $8b, $29, $8b, $27, $ff, $ff, $f5, $00, $ff, $ff, $ff
	db $dd
	db $41, $18
	dw @song0ref46
	db $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
@song0ref1806:
	db $00, $b9, $4a, <(@env7), >(@env7)
@song0ref1811:
	db $2c, $9b, $00, $8b, $4a, <(@env9), >(@env9), $4b, $2c, $8d, $00, $ff, $b1, $4a, <(@env7), >(@env7), $32, $9b, $00, $8b
	db $4a, <(@env9), >(@env9), $4b, $32, $8d, $00, $f5, $bb, $4a, <(@env7), >(@env7), $31, $9b, $00, $8b, $4a, <(@env9), >(@env9)
	db $4b, $31, $8d, $00, $ff, $b1, $4a, <(@env7), >(@env7), $2e, $b9, $00, $8d, $4a, <(@env9), >(@env9), $4b, $2e, $8b, $00
	db $9b, $2e, $8d, $00, $a9
	db $41, $1b
	dw @song0ref1806
	db $f5, $4a, <(@env7), >(@env7), $2e, $b9, $00, $9b, $4c, $2e, $ff, $93, $00, $b9, $4c
	db $41, $27
	dw @song0ref1811
	db $41, $1b
	dw @song0ref1806
	db $f5, $4a, <(@env7), >(@env7), $2e, $b9, $00, $9b, $4c, $2e, $ff, $93, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $96, $25, $8d, $25, $8b, $00, $8b, $25, $8d, $00, $8d, $25, $8b, $25, $8b, $24, $ff, $ff, $f5, $00, $ff, $ff, $ff, $dd
	db $41, $18
	dw @song0ref46
	db $ff, $ff, $ff, $df, $ff, $ff, $ff, $df, $7b, $00, $8d, $92
@song0ref1954:
	db $35, $8b, $31, $b9, $2c, $9b, $31, $a9, $35, $ab, $00, $ab, $36, $8b, $32, $b9, $2f, $9b, $32, $a9, $36, $ab, $00, $9b
	db $8f, $35, $8b, $31, $b9, $2e, $9b, $31, $a9, $35, $c9, $33, $b9, $35, $b9, $36, $b9, $38, $b9, $00, $8d
	db $41, $25
	dw @song0ref1954
	db $38, $b9, $36, $b9, $35, $b9, $00, $8d
	db $41, $2d
	dw @song0ref1954
	db $41, $25
	dw @song0ref1954
	db $38, $b9, $36, $b9, $35, $b9, $42
	dw @song0ch12loop
;@song0ch13:
;@song0ch13loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;@song0ch14loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;@song0ch15loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;@song0ch16loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;@song0ch17loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;@song0ch18loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;@song0ch19loop:
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch19loop
