; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_02_green_hill_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 02. Green Hill Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env7,@env8,@env11,@env0 ; 00 : Hi hat

@instruments_exp:
	dw @env10, @env8, @env0 ; 00 : 1 Fade
	dw @env14, @env8
	dw @instrument_epsm_extra_patch2
	db $04,$c0,$00,$20
	dw @env13, @env8, @env0 ; 01 : 1 Long
	dw @env14, @env8
	dw @instrument_epsm_extra_patch3
	db $04,$c0,$00,$20
	dw @env5, @env8, @env0 ; 02 : 1 Short Soft
	dw @env14, @env8
	dw @instrument_epsm_extra_patch4
	db $04,$c0,$00,$20
	dw @env4, @env8, @env0 ; 03 : 1-Intro Lead
	dw @env14, @env8
	dw @instrument_epsm_extra_patch5
	db $39,$80,$04,$0c
	dw @env4, @env8, @env0 ; 04 : 1-Intro Lead1
	dw @env14, @env8
	dw @instrument_epsm_extra_patch6
	db $39,$40,$04,$0c
	dw @env4, @env8, @env2 ; 05 : 1-Synth Voice
	dw @env14, @env8
	dw @instrument_epsm_extra_patch7
	db $04,$c0,$72,$26
	dw @env4, @env8, @env0 ; 06 : Bass Rough
	dw @env14, @env8
	dw @instrument_epsm_extra_patch8
	db $20,$c0,$36,$19
	dw @env4, @env8, @env0 ; 07 : Bass Slap
	dw @env14, @env8
	dw @instrument_epsm_extra_patch9
	db $08,$c0,$09,$25
	dw @env4, @env8, @env9 ; 08 : Brass 1 L
	dw @env14, @env8
	dw @instrument_epsm_extra_patch10
	db $1d,$80,$21,$18
	dw @env4, @env8, @env0 ; 09 : Brass 1 R
	dw @env14, @env8
	dw @instrument_epsm_extra_patch11
	db $1d,$40,$21,$18
	dw @env4, @env8, @env3 ; 0a : GHZ Trumpet Left
	dw @env14, @env8
	dw @instrument_epsm_extra_patch12
	db $32,$80,$71,$17
	dw @env4, @env8, @env12 ; 0b : GHZ Trumpet Mid
	dw @env14, @env8
	dw @instrument_epsm_extra_patch13
	db $32,$c0,$71,$17
	dw @env4, @env8, @env15 ; 0c : GHZ Trumpet Right
	dw @env14, @env8
	dw @instrument_epsm_extra_patch14
	db $32,$40,$71,$17

@instrument_epsm_extra_patch2:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch4:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch5:
	db $df,$1b,$02,$34,$00,$12,$0f,$5f,$10,$00,$04,$00,$14,$3c,$1f,$0d,$0b,$07,$00,$00,$11,$5f,$0a,$00,$16,$00,$00
@instrument_epsm_extra_patch6:
	db $df,$1b,$02,$34,$00,$12,$0f,$5f,$10,$00,$04,$00,$14,$3c,$1f,$0d,$0b,$07,$00,$00,$11,$5f,$0a,$00,$16,$00,$00
@instrument_epsm_extra_patch7:
	db $5f,$02,$00,$51,$00,$72,$14,$1f,$80,$03,$03,$00,$12,$26,$1f,$04,$00,$51,$00,$12,$14,$1a,$8e,$03,$03,$00,$08
@instrument_epsm_extra_patch8:
	db $df,$07,$07,$20,$00,$35,$37,$df,$06,$06,$16,$00,$30,$13,$9f,$09,$06,$17,$00,$31,$0f,$9f,$06,$08,$f6,$00,$00
@instrument_epsm_extra_patch9:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch10:
	db $8e,$00,$01,$47,$00,$71,$22,$9b,$00,$02,$36,$00,$60,$2b,$95,$00,$02,$17,$00,$54,$24,$94,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch11:
	db $8e,$00,$01,$47,$00,$71,$22,$9b,$00,$02,$36,$00,$60,$2b,$95,$00,$02,$17,$00,$54,$24,$94,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch12:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch13:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch14:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c0,$1c,$c0,$c1,$c2,$c3,$c2,$c1,$c0,$bf,$be,$bd,$be,$bf,$00,$03
@env3:
	db $00,$be,$bf,$c1,$00,$03
@env4:
	db $00,$cf,$7f,$00,$02
@env5:
	db $00,$cb,$cc,$02,$cb,$cb,$ca,$ca,$c9,$00,$08
@env6:
	db $bf,$bf,$c0,$00,$02
@env7:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env8:
	db $c0,$7f,$00,$01
@env9:
	db $00,$c4,$7f,$00,$02
@env10:
	db $00,$cd,$02,$cc,$02,$cb,$02,$ca,$00,$07
@env11:
	db $7f,$00,$00
@env12:
	db $00,$bd,$be,$c0,$00,$03
@env13:
	db $08,$cd,$05,$cc,$02,$cc,$00,$05,$cb,$02,$ca,$03,$c9,$02,$c8,$c8,$00,$0f
@env14:
	db $c8,$7f,$00,$00
@env15:
	db $00,$bc,$bd,$bf,$00,$03

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $bf
;@song0ref3:
;	db $47
;@song0ref4:
;	db $ff, $ff, $ff, $47, $ff, $ff, $ff, $47, $ff, $ff, $ff, $47, $ff, $ff, $ff
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid)
;	db $41, $0c
;	dw @song0ref4
;	db $41, $0c
;	dw @song0ref3
;	db $41, $0c
;	dw @song0ref3
;	db $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ref35:
;	db $ff, $bf
@song0ref37:
	db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff
;@song0ch1loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch1loop
;@song0ch2:
;	db $41, $0e
;	dw @song0ref35
;@song0ch2loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch2loop
@song0ch3:
	db $80, $33, $89, $00, $a1, $33, $89, $00, $a1, $33, $89, $00, $a1, $33, $89, $00, $a1
@song0ref95:
	db $33, $89, $00, $89, $33, $89, $00, $89, $33, $89, $00, $89
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $33, $89, $00, $89
@song0ch3loop:
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $41, $0c
	dw @song0ref95
	db $42
	dw @song0ch3loop
@song0ch4:
	db $97, $04, $95, $05, $95, $00, $95, $04, $95
@song0ref376:
	db $05, $95, $05, $95, $05
@song0ref381:
	db $95
@song0ref382:
	db $04, $95, $00, $95, $05, $95, $04, $95, $00, $95, $04, $95, $05, $95, $00
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $0b
	dw @song0ref381
	db $05, $95, $05, $95, $05, $95
@song0ch4loop:
	db $41, $0f
	dw @song0ref382
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $0b
	dw @song0ref381
	db $41, $15
	dw @song0ref376
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $0b
	dw @song0ref381
	db $41, $15
	dw @song0ref376
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $10
	dw @song0ref381
	db $41, $0b
	dw @song0ref381
	db $05, $95, $05, $95, $05, $95, $42
	dw @song0ch4loop
@song0ch5:
	db $ff, $bf, $84, $29, $a1, $00, $a1, $27, $a1, $00, $a1, $29, $a1, $00, $a1, $27, $a1, $00, $a1, $29, $a1, $00, $89, $27
	db $a1, $00, $89, $2a, $a1, $00, $a1, $29, $a1, $00, $a1, $27, $ff, $ed
@song0ref544:
	db $27, $a1, $00, $a1, $29, $a1, $00, $a1, $2a, $a1, $00, $89
	db $41, $0c
	dw @song0ref544
	db $2a, $95, $00, $ad, $29, $ff, $ff, $b5
@song0ch5loop:
	db $00, $ad, $80
@song0ref571:
	db $35, $89, $00, $b9, $35, $ad, $00, $c5, $33, $89, $00, $b9, $33, $ad, $00, $95, $00, $ad
	db $41, $12
	dw @song0ref571
	db $41, $10
	dw @song0ref571
@song0ref595:
	db $af
@song0ref596:
	db $31, $89, $00, $b9, $31, $ad, $00, $c5, $30, $89, $00, $b9, $30, $ad, $00, $95, $00, $ad
	db $41, $12
	dw @song0ref571
	db $41, $12
	dw @song0ref571
	db $41, $10
	dw @song0ref571
	db $41, $11
	dw @song0ref595
	db $4d, $01, $82, $3b, $c5, $3a, $c5, $38, $c5, $4d, $00, $36, $c5, $35, $95, $00, $95, $33, $95, $00, $95, $2e, $c5, $30
	db $c5, $31, $c5, $33, $c5, $35, $95, $00, $95, $4d, $01, $3a, $95, $00, $95, $39, $c5, $38, $c5, $4d, $00, $36, $c5, $34
	db $c5, $33, $ad, $31, $95, $00, $95, $97, $4d, $02, $38, $95, $3a, $95, $38, $ad, $38, $95, $3a, $95, $4d, $00, $00, $ad
	db $7b, $80, $2e, $c5, $2e, $95, $00, $95, $2e, $95, $7f, $00, $95, $42
	dw @song0ch5loop
@song0ch6:
	db $ff, $bf, $84
@song0ref717:
	db $3d, $89, $00, $89, $3c, $89, $00, $89, $3a, $89, $00, $89, $38, $89, $00, $89
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
	db $41, $10
	dw @song0ref717
@song0ch6loop:
	db $af, $80
	db $41, $10
	dw @song0ref596
	db $41, $11
	dw @song0ref595
	db $41, $11
	dw @song0ref595
@song0ref790:
	db $af, $2e, $89, $00, $b9, $2e, $ad, $00, $c5, $2c, $89, $00, $b9, $2c, $ad, $00, $95
	db $41, $11
	dw @song0ref595
	db $41, $11
	dw @song0ref595
	db $41, $11
	dw @song0ref595
	db $41, $11
	dw @song0ref790
	db $33, $ff, $ff, $b5, $31, $95, $33, $95, $35, $95, $35, $ff, $ff, $b5, $31, $95, $31, $95, $35, $95, $34, $ff, $ff, $b5
	db $31, $95, $34, $95, $33, $95, $25, $c5, $25, $c5, $25, $c5, $25, $c5, $25, $95, $00, $95, $25, $95, $00, $95, $42
	dw @song0ch6loop
;@song0ch7:
;	db $41, $0e
;	dw @song0ref35
;@song0ch7loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch7loop
@song0ch8:
	db $88
@song0ref885:
	db $40, $52, $89, $40, $4e, $89, $40, $52, $89, $40, $4e, $89, $40, $54, $89, $40, $50, $89, $40, $54, $89, $40, $50, $89
	db $40, $55, $89, $40, $52, $89, $40, $55, $89, $40, $52, $89, $40, $57, $89, $40, $54, $89, $40, $57, $89, $40, $54, $89
	db $50, $ff, $60
@song0ref936:
	db $86, $40, $59, $89, $88, $40, $55, $89, $86, $40, $59, $89, $88, $40, $55, $89, $86, $40, $59, $89, $88, $40, $55, $89
	db $41, $0c
	dw @song0ref936
	db $41, $0c
	dw @song0ref936
	db $41, $0c
	dw @song0ref936
	db $00, $dd
	db $41, $09
	dw @song0ref37
@song0ch8loop:
	db $7f, $00, $dd, $8a
@song0ref979:
	db $31, $95, $2e
@song0ref982:
	db $ad, $31, $95, $30, $ad, $31, $95, $30, $ad, $2c, $c5, $c7, $2e, $95, $35, $95, $33
	db $41, $0b
	dw @song0ref982
	db $df
	db $41, $11
	dw @song0ref979
@song0ref1006:
	db $2e, $95, $2a, $ad, $2e, $95, $2c, $ad, $2e, $95, $2c, $ad, $25, $c5, $5a, $dd
	db $41, $14
	dw @song0ref979
	db $41, $0b
	dw @song0ref982
	db $df
	db $41, $11
	dw @song0ref979
	db $41, $0d
	dw @song0ref1006
	db $95, $25, $95, $29, $95, $27, $ff, $ff, $b5, $25, $95, $27, $95, $29, $95, $ff, $ff, $b7, $25, $95, $25, $95, $29, $95
	db $28, $ff, $ff, $b5, $25, $95, $28, $95, $27, $95, $ff, $a7, $96, $40, $4d, $95, $00, $95, $40, $4d, $95, $40, $4e, $95
	db $40, $4d, $95, $40, $50, $95, $40, $4d, $95, $40, $4d, $95, $3d, $95, $42
	dw @song0ch8loop
@song0ch9:
	db $86
	db $41, $20
	dw @song0ref885
	db $4a, <(@env1), >(@env1), $96, $30, $b9, $00, $89, $4c, $2e, $b9, $00, $89, $4c, $30, $b9, $00, $89, $4c, $2e, $b9, $00
	db $89, $4c, $30, $a1, $00, $89, $4c, $2e, $a1, $00, $89, $4c, $31, $b9, $00, $89, $4c, $30, $b9, $00, $89, $4c, $2e, $ff
	db $ed
@song0ref1151:
	db $4c, $2e, $b9, $00, $89, $4c, $30, $b9, $00, $89, $4c, $31, $ad
	db $41, $0a
	dw @song0ref1151
	db $4c, $31, $b9, $00, $89, $4c, $30, $ff, $ff, $b5
@song0ch9loop:
	db $4b, $00, $ff, $ff, $b5, $96, $38, $89, $3a, $89, $3d, $95, $3a
@song0ref1191:
	db $95, $00, $ff, $ff, $b5, $38, $89, $3a, $89, $3d, $95, $40, $4d
	db $41, $0b
	dw @song0ref1191
	db $3a, $95, $00, $ff, $d5, $3d, $89, $00, $a1, $3a, $ad, $38
@song0ref1219:
	db $95, $3a, $89, $00, $89, $3d, $89, $00, $89
@song0ref1228:
	db $29, $95, $25, $89, $00, $e9, $29, $95, $25, $89, $00, $89, $27, $95, $24, $89, $00, $d1, $38, $89, $3a, $89, $3d, $95
	db $3a, $95
	db $41, $18
	dw @song0ref1228
	db $40, $4d, $95
	db $41, $1a
	dw @song0ref1228
	db $25, $95, $22, $89, $00, $ff, $81, $40, $4d, $95, $00, $95, $3d, $95, $00, $95, $3a, $95, $3a
	db $41, $09
	dw @song0ref1219
	db $40, $4d, $89, $00, $89, $92
@song0ref1291:
	db $40, $53, $95, $40, $4e, $95, $40, $57, $95, $40, $4e, $95, $40, $53, $95, $40, $4e, $95, $40, $57, $95, $40, $4e, $95
	db $41, $10
	dw @song0ref1291
@song0ref1318:
	db $40, $52, $95, $40, $4d, $95, $40, $55, $95, $40, $4d, $95, $40, $52, $95, $40, $4d, $95, $40, $55, $95, $40, $4d, $95
	db $41, $10
	dw @song0ref1318
@song0ref1345:
	db $40, $51, $95, $40, $4c, $95, $40, $55, $95, $40, $4c, $95, $40, $51, $95, $40, $4c, $95, $40, $55, $95, $40, $4c, $95
	db $41, $10
	dw @song0ref1345
@song0ref1372:
	db $40, $55, $95, $40, $52, $95, $40, $59, $95, $40, $52, $95, $40, $55, $95, $40, $52, $95, $40, $59, $95, $40, $52, $95
	db $41, $10
	dw @song0ref1372
	db $42
	dw @song0ch9loop
@song0ch10:
	db $ff, $bf, $4a, <(@env1), >(@env1), $94, $2c, $b9, $00, $89, $4c, $2a, $b9, $00, $89, $4c, $2c, $b9, $00, $89, $4c, $2a
	db $b9, $00, $89, $4c, $2c, $a1, $00, $89, $4c, $2a, $a1, $00, $89, $4c, $2e, $b9, $00, $89, $4c, $2c, $b9, $00, $89, $4c
	db $2a, $ff, $ed
@song0ref1451:
	db $4c, $2a, $b9, $00, $89, $4c, $2c, $b9, $00, $89, $4c, $2e, $ad
	db $41, $0a
	dw @song0ref1451
	db $4c, $2e, $b9, $00, $89, $4c, $2c, $ff, $ff, $b5
@song0ch10loop:
	db $4b, $7c, $94
@song0ref1481:
	db $29, $95, $29, $95
@song0ref1485:
	db $25, $95, $25, $95, $22, $95, $22, $95, $1e, $95, $1e, $95, $27, $95, $27, $95, $24, $95, $24, $95, $20, $95, $20, $95
	db $1d, $95, $1d, $95
	db $41, $1c
	dw @song0ref1481
	db $27, $95, $27, $95
	db $41, $20
	dw @song0ref1481
	db $41, $0c
	dw @song0ref1485
	db $1b, $95, $1b, $95, $24, $95, $24, $95, $90
@song0ref1535:
	db $40, $50, $ad, $40, $52
@song0ref1540:
	db $ad, $40, $54, $ad, $40, $55, $ff, $ed, $40, $57, $ad, $40, $54, $ad, $40, $50, $ad, $40, $55, $ff, $ed, $40, $54, $ad
	db $40, $50
	db $41, $0e
	dw @song0ref1540
	db $ff, $fd, $7f, $96, $2a, $ad
@song0ref1575:
	db $5a, $95, $2a, $ad, $5a, $95, $2a, $ad, $5a, $95, $2a
@song0ref1586:
	db $ad, $5a, $95, $2a, $95, $5a, $95, $2a, $95, $5a, $95, $29, $ad, $5a, $95, $29, $ad, $5a, $95, $29, $ad, $5a, $95, $29
	db $ad, $5a, $95, $29, $95, $5a, $95, $29, $95, $5a, $95, $28, $ad, $5a, $95, $28, $ad, $5a, $95, $28, $ad, $5a, $95, $28
	db $ad, $5a, $95, $28, $95, $5a, $95, $28, $95, $5a, $95, $2e, $ad, $5a, $95, $2e, $ad, $5a, $95, $2e, $ad, $5a, $95, $2e
	db $ad, $5a, $95, $2e, $95, $5a, $95, $2e, $95, $5a, $95, $42
	dw @song0ch10loop
@song0ch11:
	db $ff, $bf, $4a, <(@env1), >(@env1), $98, $29, $b9, $00, $89, $4c, $27, $b9, $00, $89, $4c, $29, $b9, $00, $89, $4c, $27
	db $b9, $00, $89, $4c, $29, $a1, $00, $89, $4c, $27, $a1, $00, $89, $4c, $2a, $b9, $00, $89, $4c, $29, $b9, $00, $89, $4c
	db $27, $ff, $ed
@song0ref1721:
	db $4c, $27, $b9, $00, $89, $4c, $29, $b9, $00, $89, $4c, $2a, $ad
	db $41, $0a
	dw @song0ref1721
	db $4c, $2a, $b9, $00, $89, $4c, $29, $ff, $ff, $b5
@song0ch11loop:
	db $4b, $7c, $98
	db $41, $20
	dw @song0ref1481
	db $41, $1c
	dw @song0ref1481
	db $27, $95, $27, $95
	db $41, $20
	dw @song0ref1481
	db $41, $0c
	dw @song0ref1485
	db $1b, $95, $1b, $95, $24, $95, $24, $95, $92
	db $41, $15
	dw @song0ref1535
	db $41, $0e
	dw @song0ref1540
	db $ff, $fd, $96, $27, $ad, $5a, $95, $27, $ad, $5a, $95, $27, $ad, $5a, $95, $27, $ad, $5a, $95, $27, $95, $5a, $95, $27
@song0ref1806:
	db $95, $5a, $95, $25, $ad, $5a, $95, $25, $ad, $5a, $95, $25, $ad, $5a, $95, $25, $ad, $5a, $95, $25, $95, $5a, $95, $25
	db $41, $18
	dw @song0ref1806
	db $95
	db $41, $0f
	dw @song0ref1575
	db $41, $0b
	dw @song0ref1586
	db $42
	dw @song0ch11loop
@song0ch12:
	db $7b, $97, $8e, $16, $95, $22, $95, $16, $95, $17, $95, $23, $95, $18, $95, $24, $95, $8c
@song0ref1861:
	db $19, $89, $00, $89, $19, $89, $00, $89, $19, $89, $00, $89
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $19, $89, $00, $89, $19, $95, $16, $89, $00, $89, $16, $95, $17, $89, $00, $89, $17, $95, $18, $89, $00, $89, $18, $95
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $0c
	dw @song0ref1861
	db $41, $09
	dw @song0ref1861
	db $95, $1b, $95, $1d, $95
@song0ch12loop:
	db $8c
@song0ref1955:
	db $1e, $89, $00, $89, $1e, $89, $00, $89, $1e, $89, $00, $89
	db $41, $0c
	dw @song0ref1955
@song0ref1970:
	db $1e, $89, $00, $89, $1e, $95
@song0ref1976:
	db $1d, $89, $00, $89, $1d, $89, $00, $89, $1d, $89, $00, $89, $1d, $89, $00, $89, $1d, $89, $00, $89, $19, $95, $1b, $95
	db $1d, $95
	db $41, $0c
	dw @song0ref1955
	db $41, $0c
	dw @song0ref1955
	db $41, $20
	dw @song0ref1970
	db $41, $0c
	dw @song0ref1955
	db $41, $0c
	dw @song0ref1955
	db $41, $1a
	dw @song0ref1970
	db $41, $09
	dw @song0ref1976
@song0ref2023:
	db $95
@song0ref2024:
	db $1b, $89, $00, $89, $1b, $89, $00, $89, $1b, $89, $00, $89
	db $41, $0c
	dw @song0ref2024
	db $1b, $89, $00, $89, $1b, $95
	db $41, $0c
	dw @song0ref1861
	db $41, $09
	dw @song0ref1861
	db $95, $1b, $95, $1d, $95
	db $41, $0c
	dw @song0ref1955
	db $41, $0c
	dw @song0ref1955
	db $41, $20
	dw @song0ref1970
	db $41, $0c
	dw @song0ref1955
	db $41, $0c
	dw @song0ref1955
	db $41, $20
	dw @song0ref1970
	db $41, $0c
	dw @song0ref1955
	db $41, $0c
	dw @song0ref1955
	db $41, $1a
	dw @song0ref1970
	db $41, $09
	dw @song0ref1976
	db $41, $0d
	dw @song0ref2023
	db $41, $0c
	dw @song0ref2024
	db $1b, $89, $00, $89, $1b, $95
	db $41, $0c
	dw @song0ref1861
	db $41, $09
	dw @song0ref1861
	db $95, $1b, $95, $1d, $95, $8e, $17, $c5, $16, $c5, $14, $c5, $12, $c5, $11, $95, $00, $95, $0f, $95, $00, $95, $16, $c5
	db $18, $c5, $19, $c5, $1b, $c5, $1d, $95, $00, $95, $22, $95, $00, $95, $21, $c5, $20, $c5, $1e, $c5, $1c, $c5, $1b, $95
	db $00, $95, $19, $95, $00, $95, $14, $c5, $1b, $c5, $14, $c5, $20, $95, $11, $95, $1d, $95, $12, $95, $1e, $95, $14, $95
	db $20, $95, $42
	dw @song0ch12loop
;@song0ch13:
;	db $41, $0e
;	dw @song0ref35
;@song0ch13loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $41, $0e
;	dw @song0ref35
;@song0ch14loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $41, $0e
;	dw @song0ref35
;@song0ch15loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $41, $0e
;	dw @song0ref35
;@song0ch16loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $41, $0e
;	dw @song0ref35
;@song0ch17loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $41, $0e
;	dw @song0ref35
;@song0ch18loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $41, $0e
;	dw @song0ref35
;@song0ch19loop:
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $41, $0c
;	dw @song0ref37
;	db $42
;	dw @song0ch19loop
