; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_01_title_theme:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 01. Title Theme

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env5,@env6,@env7,@env0 ; 00 : Hi hat
	dw @env2,@env6,@env7,@env0 ; 01 : Longer Noise

@instruments_exp:
	dw @env3, @env6, @env0 ; 00 : Bass Rough
	dw @env9, @env6
	dw @instrument_epsm_extra_patch3
	db $20,$c0,$36,$19
	dw @env3, @env6, @env0 ; 01 : Marble L
	dw @env9, @env6
	dw @instrument_epsm_extra_patch4
	db $02,$80,$04,$1f
	dw @env3, @env6, @env0 ; 02 : Marble R
	dw @env9, @env6
	dw @instrument_epsm_extra_patch5
	db $02,$40,$04,$1f
	dw @env3, @env6, @env8 ; 03 : Trumpet
	dw @env9, @env6
	dw @instrument_epsm_extra_patch6
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch3:
	db $df,$07,$07,$20,$00,$35,$37,$df,$06,$06,$16,$00,$30,$13,$9f,$09,$06,$17,$00,$31,$0f,$9f,$06,$08,$f6,$00,$00
@instrument_epsm_extra_patch4:
	db $16,$03,$0d,$af,$00,$74,$47,$1f,$82,$07,$af,$08,$11,$15,$14,$00,$07,$1f,$00,$03,$14,$14,$05,$07,$af,$00,$08
@instrument_epsm_extra_patch5:
	db $16,$03,$0d,$af,$00,$74,$47,$1f,$82,$07,$af,$08,$11,$15,$14,$00,$07,$1f,$00,$03,$14,$14,$05,$07,$af,$00,$08
@instrument_epsm_extra_patch6:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c7,$c7,$c6,$c3,$c3,$c2,$c1,$00,$07
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env6:
	db $c0,$7f,$00,$01
@env7:
	db $7f,$00,$00
@env8:
	db $00,$bd,$be,$c0,$00,$03
@env9:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $d9, $47, $ff, $ff, $ff, $df, $47, $ff, $ff, $ff, $df
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ref17:
;	db $d9, $ff, $ff, $ff, $df, $ff, $ff, $ff, $df
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $41, $09
;	dw @song0ref17
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
@song0ch3:
	db $d9, $78
@song0ref41:
	db $80, $2e, $8d, $00, $8b, $82, $2e, $9b, $80, $2e, $8d, $00, $8b, $82, $2e, $9b
	db $41, $0c
	dw @song0ref41
	db $41, $0c
	dw @song0ref41
	db $41, $0c
	dw @song0ref41
	db $41, $0c
	dw @song0ref41
	db $80, $2e, $8d, $82, $2e, $99, $00, $8d, $2e, $8d, $00, $8b, $2e, $9b, $00, $ff, $ed
@song0ch3loop:
	db $00, $42
	dw @song0ch3loop
@song0ch4:
	db $05, $9b, $05
@song0ref94:
	db $9b, $05, $9b, $04, $9b, $05, $9b, $04
	db $41, $08
	dw @song0ref94
	db $41, $08
	dw @song0ref94
	db $41, $08
	dw @song0ref94
	db $93, $05, $85, $05, $93, $05, $85, $04
	db $41, $08
	dw @song0ref94
	db $8d, $05, $8b, $00, $9b, $05, $8d, $00, $8b, $04, $9b, $00, $ff, $ed
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
;@song0ch5:
;	db $41, $09
;	dw @song0ref17
;@song0ch5loop:
;	db $00, $42
;	dw @song0ch5loop
;@song0ch6:
;	db $41, $09
;	dw @song0ref17
;@song0ch6loop:
;	db $00, $42
;	dw @song0ch6loop
;@song0ch7:
;	db $41, $09
;	dw @song0ref17
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $d9, $9d, $82
@song0ref168:
	db $32, $ab, $00, $8b, $32, $8b, $00, $8d, $33, $a3, $00, $83, $30, $ab, $00, $9b
@song0ref184:
	db $32, $8d, $00, $8b, $32, $8b, $00, $8d, $32, $8d, $00, $8b, $2e, $8b, $00, $8d, $2c, $9b, $00, $8b, $30, $b9, $00, $8d
	db $2e, $8d, $00, $8b, $32, $8b, $00, $8d, $4d, $ff, $3a, $8d, $00, $8b, $4d, $00, $35, $8b, $00, $9d, $39, $a9, $4d, $ff
	db $3a, $8d, $4d, $00, $00, $ff, $ff, $99
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $d9, $80
@song0ref247:
	db $16, $8d, $00, $8b, $16, $8b, $00, $8d, $11, $8d, $00, $8b, $11, $8b, $00, $8d, $14, $a9, $13, $9d, $14, $8b, $13, $9b
	db $41, $10
	dw @song0ref247
	db $1b, $a9, $1a, $9d, $1b, $8b, $1a, $9b, $00, $9b, $0a, $9b, $00, $9b, $0a, $9b, $00, $8d, $15, $a9, $16, $8d, $00, $8b
	db $0a, $ff, $ff, $89, $4d, $00, $81
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $d9, $7c, $86
@song0ref313:
	db $35, $8d, $00, $8b, $35, $8b, $00, $8d
	db $41, $08
	dw @song0ref184
	db $33, $a3, $00, $83, $33, $b9, $00, $8d
	db $41, $08
	dw @song0ref313
	db $41, $08
	dw @song0ref184
	db $38, $9b, $00, $8b, $38, $b9, $00, $8d, $35, $9b, $00, $9b, $35, $9b, $00, $ab, $34, $a9, $35, $8d, $00, $8b, $77, $4d
	db $01, $80, $0a, $ff, $ff, $8b
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $d9, $7c, $86
	db $41, $08
	dw @song0ref184
@song0ref379:
	db $2e, $8d, $00, $8b, $2e, $8b, $00, $8d, $30, $a3, $00, $83, $30, $b9, $00, $8d
	db $41, $08
	dw @song0ref184
	db $41, $08
	dw @song0ref379
	db $33, $9b, $00, $8b, $33, $b9, $00, $8d, $32, $9b, $00, $9b, $32, $9b, $00, $ab, $31, $a9, $32, $8d, $00, $8b, $77, $4d
	db $ff, $80, $0a, $ff, $ff, $89, $4d, $00, $81
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $d9, $4d, $fe, $9d, $84
	db $41, $30
	dw @song0ref168
	db $3a, $8d, $00, $8b, $35, $8b, $00, $9d, $39, $a9, $3a, $8d, $00, $ff, $ff, $99
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $41, $09
;	dw @song0ref17
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $41, $09
;	dw @song0ref17
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $41, $09
;	dw @song0ref17
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $41, $09
;	dw @song0ref17
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $41, $09
;	dw @song0ref17
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $41, $09
;	dw @song0ref17
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $41, $09
;	dw @song0ref17
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
