; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_10_final_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 10. Final Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env2, @env4, @env0 ; 00 : Bass Rough
	dw @env7, @env4
	dw @instrument_epsm_extra_patch1
	db $20,$c0,$36,$19
	dw @env2, @env4, @env0 ; 01 : Brass 4
	dw @env7, @env4
	dw @instrument_epsm_extra_patch2
	db $35,$c0,$32,$1c
	dw @env2, @env4, @env0 ; 02 : Electric
	dw @env7, @env4
	dw @instrument_epsm_extra_patch3
	db $3a,$c0,$01,$18
	dw @env2, @env4, @env6 ; 03 : Trumpet
	dw @env7, @env4
	dw @instrument_epsm_extra_patch4
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch1:
	db $df,$07,$07,$20,$00,$35,$37,$df,$06,$06,$16,$00,$30,$13,$9f,$09,$06,$17,$00,$31,$0f,$9f,$06,$08,$f6,$00,$00
@instrument_epsm_extra_patch2:
	db $50,$00,$01,$4f,$00,$41,$18,$90,$00,$02,$2f,$00,$72,$28,$90,$00,$02,$1f,$00,$72,$18,$90,$80,$01,$0f,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$03,$08,$1f,$00,$01,$09,$1f,$08,$02,$00,$00,$02,$1b,$1f,$00,$00,$00,$00,$02,$15,$1b,$07,$02,$6f,$00,$00
@instrument_epsm_extra_patch4:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $bf,$bf,$c0,$00,$02
@env4:
	db $c0,$7f,$00,$01
@env5:
	db $7f,$00,$00
@env6:
	db $00,$bd,$be,$c0,$00,$03
@env7:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $df
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47
;	db $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $47, $ff, $df, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $df
;@song0ch1loop:
;@song0ref42:
;	db $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $ff, $df, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $df
;@song0ch2loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch2loop
;@song0ch3:
;	db $ff, $df
;@song0ch3loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch3loop
@song0ch4:
	db $02, $99, $01, $99, $01, $99, $02, $8b, $02, $8b, $00, $99, $05, $8b, $05, $8b, $05, $8b, $05, $8b, $02, $8b, $02, $8b
@song0ch4loop:
@song0ref108:
	db $05, $8b, $00, $a7, $05, $8b, $00
@song0ref115:
	db $99, $05, $8b, $05, $8b, $00, $8b, $05, $8b, $00, $8b, $02, $99
@song0ref128:
	db $01, $99
@song0ref130:
	db $05, $8b, $00
@song0ref133:
	db $8b, $05, $8b, $00, $a7, $05, $8b, $00, $8b, $05, $8b, $00, $a7, $05, $8b, $00, $a7
	db $41, $13
	dw @song0ref108
	db $8b, $02, $8b
	db $41, $11
	dw @song0ref128
	db $41, $10
	dw @song0ref133
	db $41, $23
	dw @song0ref115
	db $41, $13
	dw @song0ref108
	db $8b, $02, $8b
	db $41, $11
	dw @song0ref128
	db $41, $10
	dw @song0ref133
	db $99, $05, $8b
	db $41, $0c
	dw @song0ref130
	db $02, $99, $01, $99, $02, $99, $01, $99, $02, $99, $01, $99, $02, $99, $01, $99, $42
	dw @song0ch4loop
;@song0ch5:
;	db $ff, $df
;@song0ch5loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch5loop
;@song0ch6:
;	db $ff, $df
;@song0ch6loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch6loop
;@song0ch7:
;	db $ff, $df
;@song0ch7loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch7loop
@song0ch8:
@song0ref229:
	db $82, $40, $54, $8b, $00, $8b, $40, $51, $8b, $00, $8b, $40, $51, $8b, $00, $8b, $40, $54, $8b, $40, $54, $8b, $00, $ed
@song0ch8loop:
@song0ref254:
	db $00, $b5, $3a, $b5, $3c, $b5, $3d, $b5, $3f, $b5, $3d, $b5, $3c, $b5, $3d, $b5, $40, $4d, $ff, $dd, $ff, $df
	db $41, $10
	dw @song0ref254
@song0ref279:
	db $40, $4e, $ff, $dd, $40, $50, $ed, $40, $51, $ed, $3a, $b5, $3a, $b5, $3a, $b5, $3a, $b5, $3c, $b5, $3c, $b5, $3c, $b5
	db $3c, $b5, $42
	dw @song0ch8loop
@song0ch9:
	db $80, $1d, $8b, $00, $8b, $11, $8b, $00, $8b, $11, $8b, $00, $8b, $1d, $8b, $1d, $8b, $00, $d1, $19, $8b, $18, $8b
@song0ch9loop:
@song0ref332:
	db $16, $b5, $16, $a7, $16, $8b, $16, $99, $16, $b5, $11, $99, $16, $8b, $11, $8b, $16, $b5, $11, $99, $16, $b5, $14, $b5
@song0ref356:
	db $12, $b5, $12, $a7, $12, $8b, $12, $99, $12, $b5, $0d, $99, $14, $99, $14, $b5, $14, $99, $15, $99, $15, $b5, $19, $8b
	db $18, $8b
	db $41, $2e
	dw @song0ref332
	db $15, $99
	db $41, $12
	dw @song0ref356
	db $11, $99, $11, $b5, $19, $8b, $18, $8b, $42
	dw @song0ch9loop
@song0ch10:
	db $4d, $fd
@song0ref403:
	db $82, $40, $4d, $8b, $00, $8b, $35, $8b, $00, $8b, $35, $8b, $00, $8b, $40, $4d, $8b, $40, $4d, $8b, $00, $eb, $4d, $00
	db $81
@song0ch10loop:
	db $00, $ff, $89, $86
@song0ref433:
	db $22, $8b, $00, $8b, $25, $8b, $00, $8b, $29, $8b, $00, $8b, $2e, $8b, $2c, $8b, $2e, $ff, $c1, $9b, $3d, $99, $00, $99
	db $3a, $8b, $00, $8b, $36, $8b, $00, $8b, $33, $d1, $9b, $3f, $99, $00, $99, $3d, $8b, $00, $8b, $3c, $8b, $00, $8b, $39
	db $d1, $00, $ff, $89
	db $41, $31
	dw @song0ref433
	db $2e, $ed, $30, $b5, $31, $b5, $30, $ed, $31, $b5, $33, $99, $43, $33, $99, $42
	dw @song0ch10loop
@song0ch11:
	db $41, $11
	dw @song0ref403
	db $ed
@song0ch11loop:
	db $84
@song0ref512:
	db $22, $99, $1d, $99, $24, $99, $1d, $99, $25, $99, $1d, $99, $24, $99, $1d, $99
	db $41, $0c
	dw @song0ref512
	db $22, $99, $1d, $99
	db $41, $0c
	dw @song0ref512
@song0ref538:
	db $22, $99, $1d, $99, $24, $99, $1d, $99, $27, $99, $1d, $99, $25, $99, $1d, $99, $24, $99, $1d, $99
	db $41, $10
	dw @song0ref512
	db $41, $0c
	dw @song0ref512
	db $22, $99, $1d, $99
	db $41, $0c
	dw @song0ref512
	db $41, $14
	dw @song0ref538
@song0ref574:
	db $3d, $8b, $3c, $8b, $3b, $8b, $3a, $8b, $3d, $8b, $3c, $8b, $3b, $8b, $3a, $8b
	db $41, $10
	dw @song0ref574
@song0ref593:
	db $3f, $8b, $3e, $8b, $3d, $8b, $3c, $8b, $3f, $8b, $3e, $8b, $3d, $8b, $3c, $8b
	db $41, $10
	dw @song0ref593
	db $42
	dw @song0ch11loop
@song0ch12:
	db $4d, $fe
	db $41, $12
	dw @song0ref229
@song0ch12loop:
	db $41, $15
	dw @song0ref254
	db $41, $10
	dw @song0ref254
	db $41, $17
	dw @song0ref279
	db $42
	dw @song0ch12loop
;@song0ch13:
;	db $ff, $df
;@song0ch13loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $df
;@song0ch14loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $df
;@song0ch15loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $df
;@song0ch16loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $df
;@song0ch17loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $df
;@song0ch18loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $df
;@song0ch19loop:
;	db $41, $14
;	dw @song0ref42
;	db $42
;	dw @song0ch19loop
