; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_17_running_out_of_air_beta:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 17. Running Out of Air! (Beta)

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env2, @env4, @env0 ; 00 : Bass Slap
	dw @env7, @env4
	dw @instrument_epsm_extra_patch1
	db $08,$c0,$09,$25
	dw @env2, @env4, @env0 ; 01 : Electric
	dw @env7, @env4
	dw @instrument_epsm_extra_patch2
	db $3a,$c0,$01,$18
	dw @env2, @env4, @env0 ; 02 : Spiky
	dw @env7, @env4
	dw @instrument_epsm_extra_patch3
	db $3a,$c0,$01,$18
	dw @env2, @env4, @env6 ; 03 : Trumpet
	dw @env7, @env4
	dw @instrument_epsm_extra_patch4
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch1:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch2:
	db $1f,$03,$08,$1f,$00,$01,$09,$1f,$08,$02,$00,$00,$02,$1b,$1f,$00,$00,$00,$00,$02,$15,$1b,$07,$02,$6f,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$0d,$08,$1f,$00,$01,$09,$1f,$0d,$02,$00,$00,$02,$18,$1f,$00,$00,$00,$00,$02,$15,$19,$0a,$02,$6f,$00,$00
@instrument_epsm_extra_patch4:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $bf,$bf,$c0,$00,$02
@env4:
	db $c0,$7f,$00,$01
@env5:
	db $7f,$00,$00
@env6:
	db $00,$bd,$be,$c0,$00,$03
@env7:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ff, $ff, $47, $ff, $ff, $bf, $47, $ff, $ff, $9f, $47, $ff, $ff, $47, $ff, $e1, $47, $ff, $b1, $47, $97
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ref28:
;	db $ff, $ff, $ff, $ff, $ff, $bf, $ff, $ff, $9f, $ff, $ff, $ff, $e1, $ff, $b1, $97
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $41, $10
;	dw @song0ref28
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
;@song0ch3:
;	db $41, $10
;	dw @song0ref28
;@song0ch3loop:
;	db $00, $42
;	dw @song0ch3loop
@song0ch4:
	db $05, $ad, $05, $ad, $05, $ad, $05, $ad, $05, $ad, $05, $ad, $05, $ad, $05, $ad, $05, $a5, $05, $a5, $05, $a5, $05, $a5
	db $05, $a5, $05, $a5, $05, $a5, $05, $a5, $05, $a1, $05, $a1, $05, $a1, $05, $a1, $05, $a1, $05, $a1, $05, $a1, $05, $a1
	db $05, $9d, $05, $9d, $05, $9d, $05, $9d, $05, $9d, $05, $9d, $05, $9d, $05, $9d, $81, $05, $99, $05, $99, $05, $99, $05
	db $99, $05, $99, $05, $99, $05, $99, $05, $99, $81, $05, $93, $05, $93, $05, $93, $05, $93, $05, $93, $05, $93, $05, $93
	db $05, $93, $05, $95
@song0ch4loop:
	db $00, $42
	dw @song0ch4loop
;@song0ch5:
;	db $41, $10
;	dw @song0ref28
;@song0ch5loop:
;	db $00, $42
;	dw @song0ch5loop
;@song0ch6:
;	db $41, $10
;	dw @song0ref28
;@song0ch6loop:
;	db $00, $42
;	dw @song0ch6loop
;@song0ch7:
;	db $41, $10
;	dw @song0ref28
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $7c, $86
@song0ref196:
	db $25, $95, $31, $95, $25, $95, $31, $95, $26, $95, $32, $95, $26, $95, $32, $95
	db $41, $10
	dw @song0ref196
@song0ref215:
	db $25, $91, $31, $91, $25, $91, $31, $91, $26, $91, $32, $91, $26, $91, $32, $91
	db $41, $10
	dw @song0ref215
@song0ref234:
	db $25, $8f, $31, $8f, $25, $8f, $31, $8f, $26, $8f, $32, $8f, $26, $8f, $32, $8f
	db $41, $10
	dw @song0ref234
@song0ref253:
	db $25, $8d, $31, $8d, $25, $8d, $31, $8d, $26, $8d, $32, $8d, $26, $8d, $32, $8d
	db $41, $10
	dw @song0ref253
	db $81
@song0ref273:
	db $25, $8b, $31, $8b, $25, $8b, $31, $8b, $26, $8b, $32, $8b, $26, $8b, $32, $8b
	db $41, $10
	dw @song0ref273
	db $81
@song0ref293:
	db $25, $89, $31, $87, $25, $89, $31, $87, $26, $89, $32, $87, $26, $89, $32, $87
	db $41, $10
	dw @song0ref293
	db $31, $95
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $7c, $86
@song0ref321:
	db $31, $95, $3d, $95, $31, $95, $3d, $95, $32, $95, $3e, $95, $32, $95, $3e, $95
	db $41, $10
	dw @song0ref321
@song0ref340:
	db $31, $91, $3d, $91, $31, $91, $3d, $91, $32, $91, $3e, $91, $32, $91, $3e, $91
	db $41, $10
	dw @song0ref340
@song0ref359:
	db $31, $8f, $3d, $8f, $31, $8f, $3d, $8f, $32, $8f, $3e, $8f, $32, $8f, $3e, $8f
	db $41, $10
	dw @song0ref359
@song0ref378:
	db $31, $8d, $3d, $8d, $31, $8d, $3d, $8d, $32, $8d, $3e, $8d, $32, $8d, $3e, $8d
	db $41, $10
	dw @song0ref378
	db $81
@song0ref398:
	db $31, $8b, $3d, $8b, $31, $8b, $3d, $8b, $32, $8b, $3e, $8b, $32, $8b, $3e, $8b
	db $41, $10
	dw @song0ref398
	db $81
@song0ref418:
	db $31, $89, $3d, $87, $31, $89, $3d, $87, $32, $89, $3e, $87, $32, $89, $3e, $87
	db $41, $10
	dw @song0ref418
	db $3d, $95
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $7c, $80
@song0ref446:
	db $0d, $95, $19, $95, $0d, $95, $19, $95, $0e, $95, $1a, $95, $0e, $95, $1a, $95
	db $41, $10
	dw @song0ref446
@song0ref465:
	db $0d, $91, $19, $91, $0d, $91, $19, $91, $0e, $91, $1a, $91, $0e, $91, $1a, $91
	db $41, $10
	dw @song0ref465
@song0ref484:
	db $0d, $8f, $19, $8f, $0d, $8f, $19, $8f, $0e, $8f, $1a, $8f, $0e, $8f, $1a, $8f
	db $41, $10
	dw @song0ref484
@song0ref503:
	db $0d, $8d, $19, $8d, $0d, $8d, $19, $8d, $0e, $8d, $1a, $8d, $0e, $8d, $1a, $8d
	db $41, $10
	dw @song0ref503
	db $81
@song0ref523:
	db $0d, $8b, $19, $8b, $0d, $8b, $19, $8b, $0e, $8b, $1a, $8b, $0e, $8b, $1a, $8b
	db $41, $10
	dw @song0ref523
	db $81
@song0ref543:
	db $0d, $89, $19, $87, $0d, $89, $19, $87, $0e, $89, $1a, $87, $0e, $89, $1a, $87
	db $41, $10
	dw @song0ref543
	db $19, $95
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $7c, $80
@song0ref571:
	db $01, $95, $0d, $95, $01, $95, $0d, $95, $02, $95, $0e, $95, $02, $95, $0e, $95
	db $41, $10
	dw @song0ref571
@song0ref590:
	db $01, $91, $0d, $91, $01, $91, $0d, $91, $02, $91, $0e, $91, $02, $91, $0e, $91
	db $41, $10
	dw @song0ref590
@song0ref609:
	db $01, $8f, $0d, $8f, $01, $8f, $0d, $8f, $02, $8f, $0e, $8f, $02, $8f, $0e, $8f
	db $41, $10
	dw @song0ref609
@song0ref628:
	db $01, $8d, $0d, $8d, $01, $8d, $0d, $8d, $02, $8d, $0e, $8d, $02, $8d, $0e, $8d
	db $41, $10
	dw @song0ref628
	db $81
@song0ref648:
	db $01, $8b, $0d, $8b, $01, $8b, $0d, $8b, $02, $8b, $0e, $8b, $02, $8b, $0e, $8b
	db $41, $10
	dw @song0ref648
	db $81
@song0ref668:
	db $01, $89, $0d, $87, $01, $89, $0d, $87, $02, $89, $0e, $87, $02, $89, $0e, $87
	db $41, $10
	dw @song0ref668
	db $0d, $95
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $7c, $82
@song0ref696:
	db $25, $89, $2b, $89, $31, $89, $37, $89, $25, $89, $2b, $89, $31, $89, $37, $89, $26, $89, $2c, $89, $32, $89, $38, $89
	db $26, $89, $2c, $89, $32, $89, $38, $89
	db $41, $20
	dw @song0ref696
@song0ref731:
	db $25, $87, $2b, $87, $31, $87, $37, $87, $25, $87, $2b, $87, $31, $87, $37, $87, $26, $87, $2c, $87, $32, $87, $38, $87
	db $26, $87, $2c, $87, $32, $87, $38, $87
	db $41, $20
	dw @song0ref731
@song0ref766:
	db $25, $87, $2b, $85, $31, $87, $37, $85, $25, $87, $2b, $85, $31, $87, $37, $85, $26, $87, $2c, $85, $32, $87, $38, $85
	db $26, $87, $2c, $85, $32, $87, $38, $85
	db $41, $20
	dw @song0ref766
@song0ref801:
	db $25, $85, $2b, $85, $31, $85, $37, $85, $25, $85, $2b, $85, $31, $85, $37, $85, $26, $85, $2c, $85, $32, $85, $38, $85
	db $26, $85, $2c, $85, $32, $85, $38, $85
	db $41, $20
	dw @song0ref801
	db $81
@song0ref837:
	db $25, $85, $2b, $83, $31, $85, $37, $83, $25, $85, $2b, $83, $31, $85, $37, $83, $26, $85, $2c, $83, $32, $85, $38, $83
	db $26, $85, $2c, $83, $32, $85, $38, $83
	db $41, $20
	dw @song0ref837
	db $81
@song0ref873:
	db $25, $83, $2b, $83, $31, $81, $37, $83, $25, $83, $2b, $83, $31, $81, $37, $83, $26, $83, $2c, $83, $32, $81, $38, $83
	db $26, $83, $2c, $83, $32, $81, $38, $83
	db $41, $20
	dw @song0ref873
	db $31, $95
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $41, $0b
;	dw @song0ref28
;	db $81, $71, $50, $03, $f0, $84
;@song0ref924:
;	db $3d, $81, $3e, $81, $3d, $3e, $81, $3d, $81, $3e, $81, $3d, $3e, $81
;	db $41, $0e
;	dw @song0ref924
;	db $41, $0e
;	dw @song0ref924
;	db $41, $0e
;	dw @song0ref924
;	db $41, $0e
;	dw @song0ref924
;	db $41, $0e
;	dw @song0ref924
;	db $41, $0e
;	dw @song0ref924
;	db $41, $0e
;	dw @song0ref924
;@song0ref959:
;	db $81, $3d, $3e, $81, $3d, $3e, $81, $3d, $3e, $3d, $3e
;	db $41, $0b
;	dw @song0ref959
;	db $41, $0b
;	dw @song0ref959
;	db $41, $0b
;	dw @song0ref959
;	db $41, $0b
;	dw @song0ref959
;	db $41, $0b
;	dw @song0ref959
;	db $41, $0b
;	dw @song0ref959
;	db $41, $0b
;	dw @song0ref959
;	db $81, $3d, $95
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $41, $10
;	dw @song0ref28
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $41, $10
;	dw @song0ref28
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $41, $10
;	dw @song0ref28
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $41, $10
;	dw @song0ref28
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $41, $10
;	dw @song0ref28
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $41, $10
;	dw @song0ref28
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
