; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_09_robotnik:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 09. Robotnik

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ; @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env1, @env5, @env0 ; 00 : 1 Longer
	dw @env8, @env5
	dw @instrument_epsm_extra_patch1
	db $04,$c0,$00,$20
	dw @env3, @env5, @env0 ; 01 : Bass Slap
	dw @env8, @env5
	dw @instrument_epsm_extra_patch2
	db $08,$c0,$09,$25
	dw @env3, @env5, @env0 ; 02 : Brass 3
	dw @env8, @env5
	dw @instrument_epsm_extra_patch3
	db $3d,$c0,$32,$1c
	dw @env3, @env5, @env0 ; 03 : Brass 3 R
	dw @env8, @env5
	dw @instrument_epsm_extra_patch4
	db $3d,$40,$32,$1c
	dw @env3, @env5, @env0 ; 04 : Spiky
	dw @env8, @env5
	dw @instrument_epsm_extra_patch5
	db $3a,$c0,$01,$18
	dw @env3, @env5, @env7 ; 05 : Trumpet L
	dw @env8, @env5
	dw @instrument_epsm_extra_patch6
	db $3a,$80,$01,$18

@instrument_epsm_extra_patch1:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch2:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch3:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$3e,$94,$00,$02,$17,$00,$72,$18,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch4:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$3e,$94,$00,$02,$17,$00,$72,$18,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch5:
	db $1f,$0d,$08,$1f,$00,$01,$09,$1f,$0d,$02,$00,$00,$02,$18,$1f,$00,$00,$00,$00,$02,$15,$19,$0a,$02,$6f,$00,$00
@instrument_epsm_extra_patch6:
	db $10,$0a,$08,$1f,$00,$01,$12,$1f,$01,$02,$0f,$00,$02,$3b,$12,$01,$01,$0f,$00,$02,$12,$19,$01,$02,$6f,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$cd,$04,$cc,$04,$cb,$04,$ca,$04,$c9,$04,$c8,$00,$0b
@env2:
	db $c1,$c0,$00,$01
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $00,$bd,$be,$c0,$00,$03
@env8:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47
;	db $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $47, $ff, $ff, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ch1loop:
;@song0ref38:
;	db $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $ff, $42
;	dw @song0ch1loop
;@song0ch2:
;@song0ch2loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch2loop
;@song0ch3:
;@song0ch3loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref76:
	db $02, $9d, $01, $9d, $02, $9d, $01, $9d, $02, $9d, $01, $9d, $02, $9d, $01
@song0ref91:
	db $9d, $05, $9d, $00, $9d, $05, $93, $05, $91, $05, $93, $05, $9d, $00, $dd, $05, $9d, $00, $bd, $05, $9d, $05, $9d, $00
	db $9d, $05, $9d, $00
	db $41, $1c
	dw @song0ref91
	db $41, $1c
	dw @song0ref91
	db $41, $11
	dw @song0ref91
	db $05, $9d, $00, $9d, $05, $9d, $05, $9d, $05, $9d, $00, $9d, $05, $9d
	db $41, $10
	dw @song0ref76
	db $42
	dw @song0ch4loop
@song0ch5:
@song0ch5loop:
	db $00, $ff, $fd, $4d, $ff, $80
@song0ref155:
	db $3c, $93, $3a, $91, $3d, $93, $3c, $ff, $bd, $00, $bd, $37, $bd, $3c, $bd, $3e, $bd, $3f, $ff, $fd, $40, $4d, $ff, $fd
	db $4d, $ff
	db $41, $15
	dw @song0ref155
	db $fd, $40, $4e, $fd, $40, $4f, $ff, $fd, $42
	dw @song0ch5loop
@song0ch6:
@song0ch6loop:
	db $00, $ff, $fd, $4d, $02, $00, $ff, $9d, $80
@song0ref205:
	db $2b, $8d, $00, $8d, $30, $8d, $00, $8d, $32, $8d, $00, $8d, $33, $ff, $fd, $00, $dd, $30, $8d, $00, $8d, $2c, $8d, $00
	db $8d, $29, $dd, $00, $dd, $33, $8d, $00, $8d, $32, $8d, $00, $8d, $2e, $dd, $4d, $02, $00, $ff, $9d
	db $41, $1a
	dw @song0ref205
@song0ref252:
	db $bd, $30, $8d, $00, $8d, $35, $8d, $00, $8d, $35, $bd, $35, $8d, $00, $8d, $36, $8d, $00, $8d, $36, $bd, $36, $8d, $00
	db $8d, $37, $ff, $fd, $42
	dw @song0ch6loop
;@song0ch7:
;@song0ch7loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch7loop
@song0ch8:
@song0ch8loop:
	db $00, $ff, $fd, $7b, $84
	db $41, $17
	dw @song0ref155
	db $41, $15
	dw @song0ref155
	db $fd, $40, $4e, $fd, $40, $4f, $ff, $fd, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $82, $13, $9d, $1f, $9d, $13, $9d, $1f, $9d, $13, $9d, $1f, $9d, $13, $9d, $1f
@song0ref330:
	db $9d, $0d, $9d, $0d, $9d, $0f, $9d, $0f, $9d, $0e, $9d, $0e, $9d, $0d, $9d, $0d, $9d, $0c, $dd, $13, $9d, $18, $bd, $16
	db $bd, $14, $9d, $14, $bd, $0f, $9d, $14, $9d, $14, $bd, $13, $9d, $11, $9d, $11, $bd, $0d, $9d, $11, $9d, $11, $bd, $0d
	db $41, $29
	dw @song0ref330
	db $11, $9d, $0f, $9d, $0f, $bd, $0f, $9d, $0e, $ff, $fd, $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $00, $ff, $fd, $00, $ff, $9d, $8a
	db $41, $27
	dw @song0ref205
	db $00, $ff, $9d
	db $41, $1a
	dw @song0ref205
	db $41, $1c
	dw @song0ref252
	db $42
	dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $00, $ff, $fd, $7b, $4d, $04, $86
	db $41, $17
	dw @song0ref155
	db $4d, $04
	db $41, $15
	dw @song0ref155
	db $fd, $40, $4e, $fd, $40, $4f, $ff, $fd, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $88, $37, $bd, $37, $bd, $37, $bd, $37, $bd, $30, $9d, $2b, $9d, $33, $9d, $2b, $9d, $30
@song0ref464:
	db $9d, $2b, $9d
@song0ref467:
	db $29, $9d, $2b, $9d, $30, $9d, $2b, $9d, $33, $9d, $2b, $9d, $30, $9d, $2b, $9d, $2e, $9d, $2b, $9d, $2c, $9d, $2b, $9d
	db $2e, $9d, $2b, $9d, $2c, $9d, $2b, $9d, $29, $9d, $2b, $9d, $2e, $9d, $2b, $9d, $2c, $9d, $2b, $9d, $32
	db $41, $13
	dw @song0ref464
	db $41, $18
	dw @song0ref467
	db $30, $9d, $2b, $9d, $2e, $9d, $2b, $9d, $2c, $9d, $2b, $9d, $2c, $9d, $2b, $9d, $30, $9d, $2b, $9d, $32, $9d, $30, $9d
	db $36, $9d, $32, $9d
@song0ref546:
	db $37, $8d, $33, $8d, $37, $8d, $33, $8d, $37, $8d, $33, $8d, $37, $8d, $33, $8d
	db $41, $10
	dw @song0ref546
	db $42
	dw @song0ch12loop
;@song0ch13:
;@song0ch13loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;@song0ch14loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;@song0ch15loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;@song0ch16loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;@song0ch17loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;@song0ch18loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;@song0ch19loop:
;	db $41, $14
;	dw @song0ref38
;	db $42
;	dw @song0ch19loop
