; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_s3k_invincibility:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : S3K Invincibility

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw 0 ;@song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw 0 ;@song0ch11 ; epsm fm4
	dw 0 ;@song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env3,@env5,@env6,@env0 ; 00 : DPCM Instrument
	dw @env4,@env5,@env6,@env0 ; 01 : noise kick
	dw @env1,@env5,@env6,@env0 ; 02 : noise snare

@instruments_exp:
	dw @env3, @env5, @env0 ; 00 : Bass Slap
	dw @env8, @env5
	dw @instrument_epsm_extra_patch3
	db $08,$c0,$09,$25
	dw @env3, @env5, @env7 ; 01 : Trumpet
	dw @env8, @env5
	dw @instrument_epsm_extra_patch4
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch3:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch4:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env2:
	db $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@env3:
	db $00,$cf,$7f,$00,$02
@env4:
	db $00,$c8,$c6,$c4,$c2,$c0,$00,$05
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $00,$bd,$be,$c0,$00,$03
@env8:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $cf
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $cf
;@song0ch1loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $cf
;@song0ch2loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch2loop
@song0ch3:
	db $7a, $84, $1c, $91, $1c, $91, $1c, $87, $1c, $87, $1c, $87, $1c, $87
@song0ch3loop:
	db $7f, $50, $f9, $60, $80, $1c, $a9, $7a, $84, $1c
@song0ref62:
	db $a7
@song0ref63:
	db $82, $16, $93, $16, $93, $84, $1c, $a7, $82, $16, $a9, $84, $1c, $9d, $1c, $87
	db $41, $09
	dw @song0ref63
	db $41, $0c
	dw @song0ref62
	db $9d, $1c, $93, $1c, $93, $1c, $87, $1c, $87, $42
	dw @song0ch3loop
@song0ch4:
	db $05, $91, $05, $91, $05, $87, $05, $87, $05, $87, $05, $87
@song0ch4loop:
@song0ref110:
	db $04, $a9, $05, $a7, $04, $93, $04, $93, $05, $a7
	db $41, $0a
	dw @song0ref110
	db $41, $0a
	dw @song0ref110
	db $41, $09
	dw @song0ref110
	db $93, $05, $91, $42
	dw @song0ch4loop
;@song0ch5:
;	db $cf
;@song0ch5loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch5loop
@song0ch6:
	db $cf
@song0ch6loop:
	db $7e, $50, $e5, $40, $82
@song0ref153:
	db $35
@song0ref154:
	db $89, $7e, $50, $dc, $30, $32, $87, $7e, $50, $e5, $40, $30, $89, $7e, $50, $dc, $30, $2e, $87, $7e, $50, $e5, $40, $35
	db $89, $7e, $50, $dc, $30, $32, $87, $7e, $50, $e0, $40, $30, $87, $7e, $50, $dc, $30, $2e, $87, $7e, $50, $e5, $40
	db $41, $10
	dw @song0ref153
	db $7e, $50, $e5, $40, $33
	db $41, $0f
	dw @song0ref154
	db $7e, $50, $e5, $40
	db $41, $10
	dw @song0ref153
	db $7e, $50, $e5, $40
	db $41, $10
	dw @song0ref153
	db $7e, $50, $e5, $40
	db $41, $10
	dw @song0ref153
	db $7e, $50, $e5, $40, $33, $89, $7e, $50, $dc, $30, $32, $87, $7e, $50, $e5, $40, $30, $89, $7e, $50, $dc, $30, $2e, $87
	db $7e, $50, $e5, $40, $33, $89, $7e, $50, $dc, $30, $32, $87, $7e, $50, $e0, $40, $30, $87, $7e, $50, $dc, $30, $2e, $87
	db $7e, $50, $e5, $40, $3f, $89, $7e, $50, $dc, $30, $3e, $87, $7e, $50, $e5, $40, $3c, $89, $7e, $50, $dc, $30, $3a, $87
	db $7e, $50, $e5, $40, $3f, $89, $7e, $50, $dc, $30, $3e, $87, $7e, $50, $e0, $40, $3c, $87, $7e, $50, $dc, $30, $3a, $87
	db $42
	dw @song0ch6loop
;@song0ch7:
;	db $cf
;@song0ch7loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch7loop
@song0ch8:
	db $48, <(@env2), >(@env2), $cf
@song0ch8loop:
	db $7d, $82, $2e, $a9, $2b, $93, $29, $91, $2e, $93, $2b, $93, $27, $93, $29, $d3, $33, $9d, $00, $87, $33, $89, $00, $87
	db $33, $89, $00, $87, $33, $87, $00, $87, $32, $a9, $2e, $93, $29, $91, $2b, $89, $00, $87, $2e, $a9, $30, $ff, $a9, $00
	db $91, $42
	dw @song0ch8loop
;@song0ch9:
;	db $cf
;@song0ch9loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch9loop
@song0ch10:
	db $cf
@song0ch10loop:
	db $7c, $80
@song0ref415:
	db $16, $89, $16, $87, $00, $89, $16, $87, $00, $89, $16, $87, $16, $87, $00, $87, $13, $93, $13, $a9, $11, $91, $11, $89
	db $11, $87, $00, $89, $11, $87, $00, $93, $11, $87, $0f, $87, $00, $89, $0f, $93, $0f, $87, $1b, $89, $0f, $87, $0f, $87
	db $0f, $87
	db $41, $14
	dw @song0ref415
	db $14, $91, $14, $89, $14, $87, $00, $89, $14, $87, $00, $93, $14, $87, $11, $87, $00, $89, $11, $93, $11, $87, $1d, $89
	db $11, $87, $11, $87, $11, $87, $42
	dw @song0ch10loop
;@song0ch11:
;	db $cf
;@song0ch11loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch11loop
;@song0ch12:
;	db $cf
;@song0ch12loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch12loop
;@song0ch13:
;	db $cf
;@song0ch13loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $cf
;@song0ch14loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $cf
;@song0ch15loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $cf
;@song0ch16loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $cf
;@song0ch17loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $cf
;@song0ch18loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $cf
;@song0ch19loop:
;	db $ff, $ff, $ff, $ff, $ff, $af, $42
;	dw @song0ch19loop
