; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_s3k_invincibility:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : S3K Invincibility

	dw @song0ch0 ; 2a03 sq1
	dw @song0ch1 ; 2a03 sq2
	dw @song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw 0 ;@song0ch11 ; epsm fm4
	dw 0 ;@song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env6,@env8,@env10,@env0 ; 00 : blank/DPCM
	dw @env7,@env8,@env9,@env0 ; 01 : noise kick
	dw @env2,@env8,@env9,@env0 ; 02 : noise snare

@instruments_exp:
	dw @env4, @env8, @env0 ; 00 : Hydrocity Bass
	dw @env11, @env8
	dw @instrument_epsm_extra_patch4
	db $3c,$c0,$01,$1a
	dw @env4, @env8, @env0 ; 01 : S3 Trumpet
	dw @env11, @env8
	dw @instrument_epsm_extra_patch5
	db $3a,$c0,$01,$18
	dw @env4, @env8, @env0 ; 02 : S3 Xylophone
	dw @env11, @env8
	dw @instrument_epsm_extra_patch6
	db $3c,$c0,$36,$33

@instrument_epsm_extra_patch4:
	db $1f,$0e,$1f,$05,$00,$00,$12,$1f,$04,$1f,$3a,$00,$00,$07,$1f,$12,$09,$25,$00,$00,$0d,$1f,$00,$00,$5a,$00,$00
@instrument_epsm_extra_patch5:
	db $8e,$0e,$00,$1f,$00,$07,$28,$8e,$0e,$00,$ff,$00,$31,$27,$8d,$0e,$00,$1f,$00,$71,$0b,$53,$03,$07,$0f,$00,$00
@instrument_epsm_extra_patch6:
	db $94,$12,$02,$4f,$00,$31,$19,$9f,$00,$00,$af,$00,$76,$1a,$96,$14,$04,$4f,$00,$71,$0b,$1f,$0f,$02,$df,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$00,$09
@env3:
	db $00,$c0,$bf,$03,$c0,$c0,$c1,$02,$c1,$00,$01
@env4:
	db $00,$cf,$7f,$00,$02
@env5:
	db $bf,$bf,$c0,$00,$02
@env6:
	db $00,$cf,$ce,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$00,$09
@env7:
	db $00,$c8,$c6,$c4,$c2,$c0,$00,$05
@env8:
	db $c0,$7f,$00,$01
@env9:
	db $7f,$00,$00
@env10:
	db $c2,$7f,$00,$00
@env11:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

@song0ch0:
	db $d5
@song0ch0loop:
	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $4e, $00, $ab, $7f, $80, $1d, $bd, $1d, $e9, $1d, $bd, $1b, $bd, $4e, $01
	db $ab, $1d, $bd, $1d, $bd, $1b, $93, $1b, $a9, $18, $e7, $42
	dw @song0ch0loop
@song0ch1:
	db $d5
@song0ch1loop:
	db $4e, $00, $ab, $7f, $80, $22, $bd, $22, $e9, $24, $bd, $22, $bd, $4e, $01, $ab, $22, $bd, $22, $bd, $20, $93, $20, $a9
	db $1d, $e7, $42
	dw @song0ch1loop
@song0ch2:
	db $d5
@song0ch2loop:
	db $80
@song0ref69:
	db $22, $89, $22, $93, $22, $93, $22, $87, $22, $91, $1f, $93, $1f, $a9, $1d, $91, $1d, $89, $1d, $93, $1d, $9d, $1d, $87
	db $1b, $93, $1b, $93, $1b, $87, $27, $89, $1b, $87, $1b, $87, $1b, $87
	db $41, $0e
	dw @song0ref69
	db $20, $91, $20, $89, $20, $93, $20, $9d, $20, $87, $1d, $93, $1d, $93, $1d, $87, $29, $89, $1d, $87, $1d, $87, $1d, $87
	db $42
	dw @song0ch2loop
@song0ch3:
	db $84, $1c, $93, $1c, $93, $1c, $89, $1c, $87, $1c, $87, $1c, $87
@song0ch3loop:
	db $7f, $50, $f9, $60, $80, $1c, $a9, $7f, $84, $1c
@song0ref161:
	db $a7
@song0ref162:
	db $82, $16, $93, $16, $93, $84, $1c, $a7, $82, $16, $a9, $84, $1c, $9d, $1c, $87
	db $41, $09
	dw @song0ref162
	db $41, $0c
	dw @song0ref161
	db $9d, $1c, $93, $1c, $93, $1c, $87, $1c, $87, $42
	dw @song0ch3loop
@song0ch4:
	db $05, $d3
@song0ch4loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch4loop
@song0ch5:
	db $d5
@song0ch5loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch5loop
@song0ch6:
	db $d5
@song0ch6loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch6loop
@song0ch7:
	db $d5
@song0ch7loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch7loop
@song0ch8:
	db $48, <(@env3), >(@env3), $d5
@song0ch8loop:
	db $7f, $82, $2e, $a9, $2b, $93, $29, $91, $2e, $93, $2b, $93, $27, $93, $29, $d3, $33, $a7, $33, $93, $33, $93, $33, $91
	db $32, $a9, $2e, $93, $29, $91, $2b, $93, $2e, $a9, $30, $ff, $a9, $00, $91, $42
	dw @song0ch8loop
@song0ch9:
	db $d5
@song0ch9loop:
	db $7f, $50, $e2, $40, $84
@song0ref295:
	db $35
@song0ref296:
	db $89, $7f, $50, $d9, $30, $32, $87, $7f, $50, $e2, $40, $30, $89, $7f, $50, $d9, $30, $2e, $87, $7f, $50, $e2, $40, $35
	db $89, $7f, $50, $d9, $30, $32, $87, $7f, $50, $dc, $40, $30, $87, $7f, $50, $d9, $30, $2e, $87, $7f, $50, $e2, $40
	db $41, $10
	dw @song0ref295
	db $7f, $50, $e2, $40, $33
	db $41, $0f
	dw @song0ref296
	db $7f, $50, $e2, $40
	db $41, $10
	dw @song0ref295
	db $7f, $50, $e2, $40
	db $41, $10
	dw @song0ref295
	db $7f, $50, $e2, $40
	db $41, $10
	dw @song0ref295
	db $7f, $50, $e2, $40, $33, $89, $7f, $50, $d9, $30, $32, $87, $7f, $50, $e2, $40, $30, $89, $7f, $50, $d9, $30, $2e, $87
	db $7f, $50, $e2, $40, $33, $89, $7f, $50, $d9, $30, $32, $87, $7f, $50, $dc, $40, $30, $87, $7f, $50, $d9, $30, $2e, $87
	db $7f, $50, $e2, $40, $3f, $89, $7f, $50, $d9, $30, $3e, $87, $7f, $50, $e2, $40, $3c, $89, $7f, $50, $d9, $30, $3a, $87
	db $7f, $50, $e2, $40, $3f, $89, $7f, $50, $d9, $30, $3e, $87, $7f, $50, $dc, $40, $3c, $87, $7f, $50, $d9, $30, $3a, $87
	db $42
	dw @song0ch9loop
@song0ch10:
	db $d5
@song0ch10loop:
	db $7f, $80
@song0ref478:
	db $16, $89, $16, $93, $16, $93, $16, $87, $16, $91, $13, $93, $13, $a9, $11, $91, $11, $89, $11, $93, $11, $9d, $11, $87
	db $0f, $93, $0f, $93, $0f, $87, $1b, $89, $0f, $87, $0f, $87, $0f, $87
	db $41, $0e
	dw @song0ref478
	db $14, $91, $14, $89, $14, $93, $14, $9d, $14, $87, $11, $93, $11, $93, $11, $87, $1d, $89, $11, $87, $11, $87, $11, $87
	db $42
	dw @song0ch10loop
@song0ch11:
	db $d5
@song0ch11loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch11loop
@song0ch12:
	db $d5
@song0ch12loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch12loop
@song0ch13:
	db $d5
@song0ch13loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch13loop
@song0ch14:
	db $d5
@song0ch14loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch14loop
@song0ch15:
	db $d5
@song0ch15loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch15loop
@song0ch16:
	db $d5
@song0ch16loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch16loop
@song0ch17:
	db $d5
@song0ch17loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch17loop
@song0ch18:
	db $d5
@song0ch18loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch18loop
@song0ch19:
	db $d5
@song0ch19loop:
	db $ff, $ff, $ff, $ff, $ff, $af, $42
	dw @song0ch19loop
