; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_05_labyrinth_zone:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 05. Labyrinth Zone

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env8,@env9,@env11,@env0 ; 00 : Hi hat
	dw @env2,@env9,@env11,@env0 ; 01 : Longer Noise

@instruments_exp:
	dw @env10, @env9, @env0 ; 00 : 1 Fade
	dw @env13, @env9
	dw @instrument_epsm_extra_patch3
	db $04,$c0,$00,$20
	dw @env3, @env9, @env0 ; 01 : 1 short
	dw @env13, @env9
	dw @instrument_epsm_extra_patch4
	db $04,$c0,$00,$20
	dw @env6, @env9, @env0 ; 02 : 1 Short Soft
	dw @env13, @env9
	dw @instrument_epsm_extra_patch5
	db $04,$c0,$00,$20
	dw @env5, @env9, @env0 ; 03 : Bass 4
	dw @env13, @env9
	dw @instrument_epsm_extra_patch6
	db $20,$c0,$36,$27
	dw @env5, @env9, @env0 ; 04 : Brass 3 L
	dw @env13, @env9
	dw @instrument_epsm_extra_patch7
	db $3d,$80,$32,$1c
	dw @env5, @env9, @env0 ; 05 : Brass 3 R
	dw @env13, @env9
	dw @instrument_epsm_extra_patch8
	db $3d,$40,$32,$1c
	dw @env5, @env9, @env4 ; 06 : GHZ Trumpet Left
	dw @env13, @env9
	dw @instrument_epsm_extra_patch9
	db $32,$80,$71,$17
	dw @env5, @env9, @env14 ; 07 : GHZ Trumpet Right
	dw @env13, @env9
	dw @instrument_epsm_extra_patch10
	db $32,$40,$71,$17
	dw @env5, @env9, @env0 ; 08 : Plucky
	dw @env13, @env9
	dw @instrument_epsm_extra_patch11
	db $28,$c0,$33,$1f
	dw @env5, @env9, @env12 ; 09 : Trumpet
	dw @env13, @env9
	dw @instrument_epsm_extra_patch12
	db $3a,$c0,$01,$18
	dw @env5, @env9, @env0 ; 0a : Trumpet 2
	dw @env13, @env9
	dw @instrument_epsm_extra_patch13
	db $3a,$c1,$12,$1d

@instrument_epsm_extra_patch3:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch4:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch5:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch6:
	db $1f,$0e,$07,$20,$00,$35,$2c,$1f,$10,$06,$16,$00,$30,$16,$1f,$0c,$06,$17,$00,$31,$10,$1f,$0b,$08,$f6,$00,$00
@instrument_epsm_extra_patch7:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$3e,$94,$00,$02,$17,$00,$72,$18,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch8:
	db $5f,$00,$01,$47,$00,$41,$14,$90,$00,$02,$26,$00,$72,$3e,$94,$00,$02,$17,$00,$72,$18,$90,$80,$01,$08,$00,$00
@instrument_epsm_extra_patch9:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch10:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch11:
	db $5c,$10,$08,$ff,$00,$34,$2a,$5f,$05,$06,$1f,$00,$30,$16,$1f,$12,$06,$1f,$00,$31,$0f,$1f,$0c,$08,$7f,$00,$00
@instrument_epsm_extra_patch12:
	db $12,$0d,$08,$14,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch13:
	db $1b,$00,$00,$34,$00,$01,$27,$19,$04,$00,$04,$00,$01,$26,$0f,$00,$00,$04,$00,$02,$0d,$16,$03,$03,$44,$00,$0b

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$c7,$c7,$c6,$c3,$c3,$c2,$c1,$00,$07
@env3:
	db $00,$cd,$cc,$cc,$cb,$cb,$ca,$c9,$c8,$c7,$c6,$00,$0a
@env4:
	db $00,$be,$bf,$c1,$00,$03
@env5:
	db $00,$cf,$7f,$00,$02
@env6:
	db $00,$cb,$cc,$02,$cb,$cb,$ca,$ca,$c9,$00,$08
@env7:
	db $bf,$bf,$c0,$00,$02
@env8:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env9:
	db $c0,$7f,$00,$01
@env10:
	db $00,$cd,$02,$cc,$02,$cb,$02,$ca,$00,$07
@env11:
	db $7f,$00,$00
@env12:
	db $00,$bd,$be,$c0,$00,$03
@env13:
	db $c8,$7f,$00,$00
@env14:
	db $00,$bc,$bd,$bf,$00,$03

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $df
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47
;	db $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf, $47, $ff, $ff, $ff, $bf
;	db $47, $ff, $ff, $ff, $bf, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $df
;@song0ch1loop:
;@song0ref57:
;	db $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf
;	db $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $df
;@song0ch2loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch2loop
@song0ch3:
	db $d3, $82, $20, $b5, $80, $20, $99, $20, $99, $00, $99
@song0ch3loop:
@song0ref117:
	db $82, $20, $b5, $80, $20, $99, $20, $99, $20, $99, $20, $99, $20, $99, $20, $99, $82, $20, $b5, $80, $20, $99, $20, $99
	db $20, $99, $20, $99, $20, $99, $20, $8b, $20, $8b
	db $41, $15
	dw @song0ref117
	db $8b, $20, $8b, $20, $99, $20, $8b, $20, $8b, $20, $99
	db $41, $1e
	dw @song0ref117
	db $41, $1b
	dw @song0ref117
	db $99
	db $41, $1b
	dw @song0ref117
	db $99, $00, $8b
@song0ref178:
	db $20, $8b, $00, $8b, $20, $8b, $00, $8b, $20
@song0ref187:
	db $8b, $82, $20, $99, $80
@song0ref192:
	db $20, $8b, $00, $8b, $20, $8b, $00, $8b, $20, $8b, $00, $8b, $20, $8b, $00, $8b, $20, $8b, $00, $8b
	db $41, $14
	dw @song0ref192
	db $20, $8b, $00
	db $41, $17
	dw @song0ref187
	db $41, $14
	dw @song0ref192
	db $20, $8b, $00, $8b, $20, $8b, $00, $8b, $20, $8b, $20, $8b, $82, $20, $99, $80, $20, $8b, $20, $8b, $82, $20, $99, $00
	db $8b, $80
	db $41, $20
	dw @song0ref178
	db $41, $14
	dw @song0ref192
	db $20, $8b, $00
	db $41, $17
	dw @song0ref187
	db $41, $14
	dw @song0ref192
	db $20, $8b, $00, $8b, $20, $8b, $00, $8b, $82, $20, $99, $00, $99, $20, $99, $00, $99, $42
	dw @song0ch3loop
@song0ch4:
	db $05, $99, $05, $99, $05, $99, $04, $99, $00, $99, $05, $99, $05, $99, $00, $99
@song0ch4loop:
@song0ref302:
	db $04, $99, $00, $b5, $04, $99, $04, $99, $00, $99, $05, $99, $00, $99, $04, $99, $00, $b5, $04, $99, $04, $99, $00, $99
	db $05, $99, $00, $99
	db $41, $1c
	dw @song0ref302
	db $41, $1c
	dw @song0ref302
	db $41, $1c
	dw @song0ref302
	db $41, $16
	dw @song0ref302
	db $05, $99, $05, $99
@song0ref346:
	db $05
@song0ref347:
	db $99, $04, $99, $00, $99, $05, $99, $04, $99, $04, $99, $00, $99, $05, $99, $00, $99, $04, $99, $00, $99, $05, $99, $04
	db $99, $04, $99, $00, $99, $05, $99, $00
	db $41, $1f
	dw @song0ref347
	db $41, $21
	dw @song0ref346
	db $41, $1b
	dw @song0ref347
	db $05, $99, $05, $99, $05, $99, $42
	dw @song0ch4loop
@song0ch5:
	db $80, $3a, $8b, $84, $3a, $8b, $80, $36, $8b, $84, $36, $8b, $80, $33, $8b, $84, $33, $8b, $00, $ff, $89
@song0ch5loop:
	db $00, $99, $82, $35, $99
@song0ref424:
	db $00, $99, $35
@song0ref427:
	db $99, $00, $99, $35, $99, $00, $99, $35, $99, $00, $99, $35, $99, $00, $99, $35, $99, $00, $99, $35, $8b, $35, $8b
	db $41, $17
	dw @song0ref424
	db $99, $00, $99, $35
@song0ref457:
	db $99, $00, $99, $35, $8b, $35, $8b, $00, $99, $35, $99
@song0ref468:
	db $00, $99, $3a, $99, $00, $99, $3a, $99, $00, $99, $3a, $99, $00, $99, $3a, $99, $00, $99, $3a, $99, $00, $99, $3a, $99
	db $00, $99, $3a, $8b, $3a, $8b
	db $41, $1b
	dw @song0ref468
	db $99, $00, $99, $3a, $8b, $3a, $8b, $00, $99, $3a
	db $41, $17
	dw @song0ref427
	db $00, $99, $35, $99, $00, $99, $3b, $99, $00, $99, $3b
@song0ref525:
	db $99, $00, $99, $3a, $99, $00, $99, $3a, $99, $00, $99, $38, $8b, $38, $8b, $00, $99, $38, $99, $00, $99, $36, $99, $00
	db $99, $36
	db $41, $15
	dw @song0ref457
	db $38, $8b, $38, $8b, $00, $99, $38, $99, $00, $99, $3c, $99, $00, $99, $3c, $99, $00, $99, $3c, $8b, $3c, $8b, $00, $99
	db $3c
	db $41, $1a
	dw @song0ref525
	db $41, $15
	dw @song0ref457
	db $3b, $8b, $3b, $8b, $00, $99, $3b, $99, $00, $99, $35, $99, $00, $99, $35, $99, $33, $99, $36, $99, $3a, $99, $00, $99
	db $42
	dw @song0ch5loop
@song0ch6:
	db $80, $3d, $8b, $84, $3d, $8b, $80, $3a, $8b, $84, $3a, $8b, $80, $36, $8b, $84, $36, $8b, $00, $ff, $89
@song0ch6loop:
	db $00, $99, $82, $38, $99
@song0ref639:
	db $00, $99, $38
@song0ref642:
	db $99, $00, $99, $38, $99, $00, $99, $38, $99, $00, $99, $38, $99, $00, $99, $38, $99, $00, $99, $38, $8b, $38, $8b
	db $41, $17
	dw @song0ref639
	db $99, $00, $99, $38, $99, $00, $99, $38, $8b, $38, $8b, $00, $99, $38, $99
@song0ref683:
	db $00, $99, $3d, $99, $00, $99, $3d, $99, $00, $99, $3d, $99, $00, $99, $3d, $99, $00, $99, $3d, $99, $00, $99, $3d, $99
	db $00, $99, $3d, $8b, $3d, $8b
	db $41, $1b
	dw @song0ref683
	db $99, $00, $99, $3d, $8b, $3d, $8b, $00, $99, $3d
	db $41, $17
	dw @song0ref642
	db $00, $99, $38, $99, $00, $99, $3e, $99
@song0ref737:
	db $00, $99, $3e, $99, $00, $99, $3d, $99, $00, $99, $3d, $99, $00, $99, $3c, $8b, $3c, $8b, $00, $99, $3c
	db $41, $15
	dw @song0ref525
	db $3d, $99, $00, $99, $3d, $99, $00, $99, $3c, $8b, $3c, $8b, $00, $99, $3c, $99, $00, $99, $3f, $99, $00, $99, $3f, $99
	db $00, $99, $3e, $8b, $3e, $8b
	db $41, $15
	dw @song0ref737
	db $41, $15
	dw @song0ref525
	db $3d, $99, $00, $99, $3d, $99, $00, $99, $3f, $8b, $3f, $8b, $00, $99, $3f, $99, $00, $99, $38, $99, $00, $99, $38, $99
	db $36, $99, $3a, $99, $3d, $99, $00, $99, $42
	dw @song0ch6loop
;@song0ch7:
;	db $ff, $df
;@song0ch7loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch7loop
@song0ch8:
	db $ff, $df
@song0ch8loop:
	db $00, $99, $90
@song0ref847:
	db $29, $99, $2c, $99, $29, $99, $2c, $a7, $2e, $a7, $30, $b5, $31, $99, $30, $99, $2e, $99, $2c, $a7, $2e, $99, $2c, $8b
	db $29, $99, $00, $99
	db $41, $1c
	dw @song0ref847
@song0ref878:
	db $2e, $99, $31, $99, $2e, $99, $31, $a7, $33, $a7, $35, $b5, $36, $99, $35, $99, $33, $99, $31, $a7, $33, $99, $31, $8b
	db $2e, $99, $00, $99
	db $41, $13
	dw @song0ref878
	db $b5, $2e, $b5, $33, $8f, $31, $91, $33, $8f, $31, $ff, $a5, $00, $ff, $dd
@song0ref924:
	db $31, $b5, $31, $99, $31, $99, $33, $a7, $31, $a7, $36, $b5, $35, $99, $33, $99, $31, $99, $33, $a7, $35, $c3, $31, $b5
	db $31, $99, $31, $99, $33, $a7, $31, $a7, $35, $ff, $f9
	db $41, $16
	dw @song0ref924
	db $36, $99, $35, $99, $33, $99, $31, $99, $2f, $99, $2e, $99, $2c, $99, $2a, $99, $29, $99, $31, $ff, $c1, $42
	dw @song0ch8loop
@song0ch9:
	db $8c
@song0ref987:
	db $3a, $8b, $00, $8b, $36, $8b, $00, $8b, $33, $8b, $00, $8b, $38, $a7, $00, $8b, $38, $8b, $00, $8b, $38, $8b, $00, $a7
@song0ch9loop:
@song0ref1012:
	db $00, $ff, $ff, $ff, $bd, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $ff, $ff, $ff, $bf, $7b, $88
@song0ref1035:
	db $35, $ff, $ff, $cd, $36, $b5, $38, $b5, $31, $ff, $c1, $00, $ff, $f9, $35, $ff, $ff, $cd, $36, $b5, $38, $b5, $31, $ed
	db $33, $ed, $35, $ed, $38, $ed, $42
	dw @song0ch9loop
@song0ch10:
	db $8e
	db $41, $18
	dw @song0ref987
@song0ch10loop:
	db $41, $15
	dw @song0ref1012
	db $7b, $8a
	db $41, $1e
	dw @song0ref1035
	db $42
	dw @song0ch10loop
@song0ch11:
	db $92, $31, $8b, $00, $8b, $2e, $8b, $00, $8b, $2a, $8b, $00, $8b, $31, $a7, $00, $8b, $31, $8b, $00, $8b, $31, $8b, $00
	db $a7
@song0ch11loop:
	db $7c, $ff, $ff, $eb, $94, $20, $8b, $22, $8b, $25, $8b, $00, $8b, $22, $8b, $00, $8b, $ff, $ff, $eb, $29, $8b, $25, $8b
	db $22, $8b, $00, $8b, $25, $8b, $00, $8b, $ff, $ff, $eb, $25, $8b, $27, $8b, $2a, $8b, $00, $8b, $27, $8b, $00, $8b, $ff
	db $ff, $eb, $2e, $8b, $2a, $8b, $25, $8b, $00, $8b, $2a, $8b, $00, $8b, $ff, $fb, $20, $99, $00, $99, $22, $99, $00, $99
	db $23, $8b, $00, $8b, $23, $8b, $00, $8b, $26, $8b
@song0ref1192:
	db $00, $8b
@song0ref1194:
	db $29, $8f, $00, $bf, $29, $8f, $00, $87, $27, $8f, $00, $bf, $27, $8f, $00, $87, $25, $8f, $00, $bf, $25, $8f, $00, $87
	db $24, $8f, $00, $87, $25, $8f, $00, $87, $27, $a7
	db $41, $11
	dw @song0ref1192
	db $a3, $22, $8f, $00, $a3, $24, $8f, $00, $a3, $26, $8f, $00, $87, $26, $8f, $00, $87, $29, $8f, $00, $87
	db $41, $22
	dw @song0ref1194
	db $41, $11
	dw @song0ref1192
	db $a3, $20, $87, $00, $81, $22
@song0ref1264:
	db $87, $00, $81, $25, $87, $00, $81, $25, $87, $00, $81, $22, $87, $00, $81, $20, $87, $00, $81, $25, $87, $00, $81, $25
	db $87, $00, $81, $22, $87, $00, $81, $20
	db $41, $13
	dw @song0ref1264
	db $42
	dw @song0ch11loop
@song0ch12:
	db $d3, $86, $0f, $b5, $14, $8b, $00, $8b, $14, $8b, $00, $a7
@song0ch12loop:
@song0ref1315:
	db $0d, $b5, $00, $99, $11, $8b, $00, $8b, $14, $a7, $00, $8b, $16, $a7, $00, $8b, $18, $b5, $00, $99, $16, $8b, $00, $8b
	db $14, $b5, $11, $b5
	db $41, $1c
	dw @song0ref1315
@song0ref1346:
	db $12, $b5, $00, $99, $16, $8b, $00, $8b, $19, $a7, $00, $8b, $1b, $a7, $00, $8b, $1d, $b5, $00, $99, $1b, $8b, $00, $8b
	db $19, $b5, $16, $a7, $00, $8b
	db $41, $1e
	dw @song0ref1346
	db $0d, $b5, $00, $99, $11, $8b, $00, $8b, $14, $a7, $00, $8b, $11, $a7, $00, $8b, $19, $8b, $00, $8b, $19, $8b, $00, $8b
	db $14, $99, $19, $8b, $00, $8b, $13, $df, $00, $8b
@song0ref1413:
	db $12, $99, $00, $b5, $12, $99, $11, $99, $00, $b5, $11, $99, $0f, $99, $00, $b5, $0f, $99, $0d, $99, $0f, $99, $11, $b5
	db $12, $99, $00, $b5, $12, $99, $11, $99, $00, $b5, $11, $99, $16, $99, $00, $b5, $16, $99, $16, $d1, $00, $99
	db $41, $1e
	dw @song0ref1413
	db $17, $99, $00, $b5, $17, $99, $19, $99, $00, $b5, $19, $99, $14, $b5, $14, $b5, $42
	dw @song0ch12loop
;@song0ch13:
;	db $ff, $df
;@song0ch13loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $df
;@song0ch14loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $df
;@song0ch15loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $df
;@song0ch16loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $df
;@song0ch17loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $df
;@song0ch18loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $df
;@song0ch19loop:
;	db $41, $24
;	dw @song0ref57
;	db $42
;	dw @song0ch19loop
