; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_21_invincibility_beta:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 21. Invincibility (Beta)

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw @song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw 0 ;@song0ch5 ; epsm sq1
	dw 0 ;@song0ch6 ; epsm sq1
	dw 0 ;@song0ch7 ; epsm sq2
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm
	
	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:
	dw @env4,@env5,@env6,@env0 ; 00 : Hi hat

@instruments_exp:
	dw @env2, @env5, @env0 ; 00 : Bass Slap
	dw @env8, @env5
	dw @instrument_epsm_extra_patch2
	db $08,$c0,$09,$25
	dw @env2, @env5, @env0 ; 01 : EPSM Custom 36
	dw @env8, @env5
	dw @instrument_epsm_extra_patch3
	db $3a,$c0,$51,$17
	dw @env2, @env5, @env0 ; 02 : EPSM Custom 39
	dw @env8, @env5
	dw @instrument_epsm_extra_patch4
	db $3a,$c0,$51,$18
	dw @env2, @env5, @env7 ; 03 : Trumpet 1
	dw @env8, @env5
	dw @instrument_epsm_extra_patch5
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch2:
	db $1f,$12,$00,$2f,$00,$70,$30,$1f,$0e,$04,$2f,$00,$30,$13,$5f,$0a,$04,$2f,$00,$00,$0f,$5f,$0a,$03,$2f,$00,$00
@instrument_epsm_extra_patch3:
	db $1e,$1f,$00,$0f,$00,$08,$23,$1e,$1f,$00,$0f,$00,$51,$22,$1e,$1f,$00,$0f,$00,$02,$22,$10,$0f,$02,$0f,$00,$00
@instrument_epsm_extra_patch4:
	db $1e,$1f,$00,$0f,$00,$08,$24,$1e,$1f,$00,$0f,$00,$51,$22,$1e,$1f,$00,$0f,$00,$02,$14,$10,$0f,$02,$1f,$00,$00
@instrument_epsm_extra_patch5:
	db $1d,$0d,$08,$15,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $bf,$bf,$c0,$00,$02
@env4:
	db $00,$c7,$c7,$c6,$c2,$c1,$c0,$00,$06
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $00,$bd,$be,$c0,$00,$03
@env8:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $f1
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47
;	db $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $47, $ff, $e1, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $f1
;@song0ch1loop:
;@song0ref46:
;	db $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1, $ff, $e1
;	db $42
;	dw @song0ch1loop
;@song0ch2:
;	db $f1
;@song0ch2loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch2loop
@song0ch3:
	db $f1
@song0ch3loop:
	db $81, $80
@song0ref85:
	db $21, $8d, $00, $89, $21, $8d, $00, $89, $21, $8d, $00, $89, $21, $8d, $00, $89, $21, $8d, $00, $89, $21, $8d, $00, $89
	db $21, $8d, $00, $89, $21, $8d, $00, $89, $81
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $21
	dw @song0ref85
	db $41, $20
	dw @song0ref85
	db $42
	dw @song0ch3loop
@song0ch4:
	db $81, $05, $85, $00, $83, $05, $85, $00, $83, $05, $85, $00, $83, $05, $85, $00, $83, $05, $00, $83, $05, $00, $81, $04
	db $85, $00, $9f
@song0ch4loop:
@song0ref182:
	db $81, $04, $8d, $00, $89, $05, $8d, $00, $89, $04, $8d, $00, $89, $05, $8d, $00, $89, $04, $8d, $00, $89, $05, $8d, $00
	db $89, $04, $8d, $00, $89, $05, $8d, $00, $89
	db $41, $1a
	dw @song0ref182
	db $89, $00, $87, $05, $81, $00, $05, $8d, $00, $89
	db $41, $21
	dw @song0ref182
	db $41, $1a
	dw @song0ref182
@song0ref234:
	db $89, $00, $87, $05, $81, $00
@song0ref240:
	db $05, $8d, $00, $89, $81, $05, $85, $00, $83, $04, $95, $00, $8f, $04, $8d, $00, $89, $05, $8d, $00, $89, $05, $85, $00
	db $83, $04, $95, $00, $8f, $04, $8d, $00, $89
	db $41, $16
	dw @song0ref240
@song0ref276:
	db $83, $00, $81, $05, $83, $00, $83, $05, $81, $00, $05, $83, $00, $81, $05, $83, $00, $83, $05, $81, $00, $05, $83, $00
	db $81, $05, $83, $00, $83, $05, $81, $00, $05, $81, $00, $81, $05, $85, $00, $83, $05, $81, $00
	db $41, $21
	dw @song0ref182
	db $41, $1a
	dw @song0ref182
	db $89, $00, $87, $05, $81, $00, $05, $8d, $00, $89
	db $41, $21
	dw @song0ref182
	db $41, $1a
	dw @song0ref182
	db $41, $27
	dw @song0ref234
	db $41, $16
	dw @song0ref240
	db $41, $2b
	dw @song0ref276
	db $42
	dw @song0ch4loop
;@song0ch5:
;	db $f1
;@song0ch5loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch5loop
;@song0ch6:
;	db $f1
;@song0ch6loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch6loop
;@song0ch7:
;	db $f1
;@song0ch7loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch7loop
@song0ch8:
	db $f1
@song0ch8loop:
	db $81, $00, $99, $7f, $84
@song0ref384:
	db $32, $b5, $32, $99, $33, $a7, $30, $c3, $81, $32, $99, $32, $99, $32, $99, $2e, $99, $2c, $a7, $30, $c3, $81, $00, $99
	db $41, $15
	dw @song0ref384
@song0ref411:
	db $ff, $91, $00, $cd, $81, $2e, $87, $30, $89, $32, $83, $33, $87, $35, $89, $37, $83, $30, $87, $32, $89, $34, $83, $35
	db $87, $37, $89, $39, $83, $32, $87, $34, $89, $36, $83, $37, $87, $39, $89, $3b, $83, $36, $87, $37, $89, $39, $83, $3b
	db $87, $3d, $89, $3e, $83, $81, $00, $99
	db $41, $18
	dw @song0ref384
	db $41, $15
	dw @song0ref384
	db $41, $35
	dw @song0ref411
	db $42
	dw @song0ch8loop
@song0ch9:
	db $f1
@song0ch9loop:
	db $81, $00, $99, $7f, $82
	db $41, $18
	dw @song0ref384
	db $41, $15
	dw @song0ref384
	db $41, $38
	dw @song0ref411
	db $41, $18
	dw @song0ref384
	db $41, $15
	dw @song0ref384
	db $41, $35
	dw @song0ref411
	db $42
	dw @song0ch9loop
@song0ch10:
	db $f1
@song0ch10loop:
	db $81, $7f, $86
@song0ref512:
	db $29, $99, $29, $99, $26, $99, $26, $99, $27, $a7, $2b, $c3, $81, $29, $99, $29, $99, $26, $99, $26, $99, $2c, $a7, $2c
	db $c3, $81
	db $41, $19
	dw @song0ref512
@song0ref541:
	db $8f, $24, $a7, $26, $c3, $24, $a7, $26, $b5, $8f, $24, $a7, $26, $c3, $24, $a7, $26, $b5, $81
	db $41, $1a
	dw @song0ref512
	db $41, $19
	dw @song0ref512
	db $41, $12
	dw @song0ref541
	db $42
	dw @song0ch10loop
@song0ch11:
	db $f1
@song0ch11loop:
	db $81, $7f, $86
@song0ref577:
	db $26, $99, $26, $99, $22, $99, $22, $99, $24, $a7, $27, $c3, $81, $26, $99, $26, $99, $22, $99, $22, $99, $27, $a7, $27
	db $c3, $81
	db $41, $19
	dw @song0ref577
@song0ref606:
	db $8f, $20, $a7, $22, $c3, $20, $a7, $22, $b5, $8f, $20, $a7, $22, $c3, $20, $a7, $22, $b5, $81
	db $41, $1a
	dw @song0ref577
	db $41, $19
	dw @song0ref577
	db $41, $12
	dw @song0ref606
	db $42
	dw @song0ch11loop
@song0ch12:
	db $f1
@song0ch12loop:
	db $7f, $80
@song0ref641:
	db $16, $99, $16, $99, $11, $99, $11, $99, $14, $a7, $13, $99, $14, $8b, $13, $9b, $16, $99, $16, $99, $11, $99, $11, $99
	db $1b, $a7, $1a, $99, $1b, $8b, $1a, $9b
	db $41, $20
	dw @song0ref641
@song0ref676:
	db $18, $8b, $14, $a7, $16, $99, $18, $99, $18, $8b, $14, $a7, $16, $99, $18, $9b, $16, $99, $18, $99, $1a, $99, $1c, $99
	db $18, $8b, $1a, $8b, $1c, $8f, $1e, $87, $1a, $8b, $1c, $8b, $1e, $8b, $1f, $8d
	db $41, $20
	dw @song0ref641
	db $41, $20
	dw @song0ref641
	db $41, $28
	dw @song0ref676
	db $42
	dw @song0ch12loop
;@song0ch13:
;	db $f1
;@song0ch13loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;	db $f1
;@song0ch14loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;	db $f1
;@song0ch15loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;	db $f1
;@song0ch16loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;	db $f1
;@song0ch17loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;	db $f1
;@song0ch18loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;	db $f1
;@song0ch19loop:
;	db $41, $18
;	dw @song0ref46
;	db $42
;	dw @song0ch19loop
