; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_sonic_2_super_sonic:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : Sonic 2 Super Sonic

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw @song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq2
	dw 0 ;@song0ch7 ; epsm sq3
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env2, @env3, @env0 ; 00 : 1 Short Soft
	dw @env6, @env3
	dw @instrument_epsm_extra_patch1
	db $04,$c0,$00,$20
	dw @env1, @env3, @env0 ; 01 : Bass 3
	dw @env6, @env3
	dw @instrument_epsm_extra_patch2
	db $00,$c0,$00,$7f
	dw @env1, @env3, @env0 ; 02 : Bass 4
	dw @env6, @env3
	dw @instrument_epsm_extra_patch3
	db $20,$c0,$36,$27
	dw @env1, @env3, @env0 ; 03 : Bass Rough
	dw @env6, @env3
	dw @instrument_epsm_extra_patch4
	db $20,$c0,$36,$19
	dw @env1, @env3, @env5 ; 04 : GHZ Trumpet Mid
	dw @env6, @env3
	dw @instrument_epsm_extra_patch5
	db $32,$c0,$71,$17
	dw @env1, @env3, @env0 ; 05 : Marble L
	dw @env6, @env3
	dw @instrument_epsm_extra_patch6
	db $02,$80,$04,$1f
	dw @env1, @env3, @env0 ; 06 : Marble R
	dw @env6, @env3
	dw @instrument_epsm_extra_patch7
	db $02,$40,$04,$1f
	dw @env1, @env3, @env5 ; 07 : Trumpet 1
	dw @env6, @env3
	dw @instrument_epsm_extra_patch8
	db $3a,$c0,$01,$18

@instrument_epsm_extra_patch1:
	db $1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00,$20,$1f,$00,$00,$07,$00,$00,$00,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch2:
	db $1f,$00,$00,$23,$00,$70,$20,$1f,$00,$04,$23,$00,$10,$1f,$5f,$05,$04,$23,$00,$20,$0b,$5f,$0a,$03,$25,$00,$00
@instrument_epsm_extra_patch3:
	db $1f,$0e,$07,$20,$00,$35,$2c,$1f,$10,$06,$16,$00,$30,$16,$1f,$0c,$06,$17,$00,$31,$10,$1f,$0b,$08,$f6,$00,$00
@instrument_epsm_extra_patch4:
	db $df,$07,$07,$20,$00,$35,$37,$df,$06,$06,$16,$00,$30,$13,$9f,$09,$06,$17,$00,$31,$0f,$9f,$06,$08,$f6,$00,$00
@instrument_epsm_extra_patch5:
	db $16,$18,$06,$15,$00,$02,$1a,$1a,$0a,$02,$05,$00,$02,$3c,$1e,$0a,$01,$05,$00,$72,$17,$1d,$05,$02,$65,$00,$00
@instrument_epsm_extra_patch6:
	db $16,$03,$0d,$af,$00,$74,$47,$1f,$82,$07,$af,$08,$11,$15,$14,$00,$07,$1f,$00,$03,$14,$14,$05,$07,$af,$00,$08
@instrument_epsm_extra_patch7:
	db $16,$03,$0d,$af,$00,$74,$47,$1f,$82,$07,$af,$08,$11,$15,$14,$00,$07,$1f,$00,$03,$14,$14,$05,$07,$af,$00,$08
@instrument_epsm_extra_patch8:
	db $1d,$0d,$08,$15,$00,$01,$12,$1f,$0d,$02,$05,$00,$02,$3b,$12,$0a,$01,$05,$00,$02,$12,$19,$05,$02,$65,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $00,$cf,$7f,$00,$02
@env2:
	db $00,$cb,$cc,$02,$cb,$cb,$ca,$ca,$c9,$00,$08
@env3:
	db $c0,$7f,$00,$01
@env4:
	db $7f,$00,$00
@env5:
	db $00,$bd,$be,$c0,$00,$03
@env6:
	db $c8,$7f,$00,$00

@samples:
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0e,$40 ; 00 Drum 1 (Pitch:14)
	db $10+<(FAMISTUDIO_DPCM_PTR),$42,$0f,$40 ; 01 Drum 1 (Pitch:15)
	db $21+<(FAMISTUDIO_DPCM_PTR),$39,$0f,$40 ; 02 Drum 1 lower (Pitch:15)
	db $00+<(FAMISTUDIO_DPCM_PTR),$17,$0f,$40 ; 03 Kick Sonic (Pitch:15)
	db $06+<(FAMISTUDIO_DPCM_PTR),$26,$0f,$40 ; 04 Snare Sonic (Pitch:15)

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;@song0ch0loop:
;	db $46, <(@tempo_env_1_mid), >(@tempo_env_1_mid), $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47
;	db $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $47, $ff, $bf, $42
;	dw @song0ch0loop
;@song0ch1:
;@song0ch1loop:
;@song0ref44:
;	db $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf
;	db $42
;	dw @song0ch1loop
;@song0ch2:
;@song0ch2loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch2loop
;@song0ch3:
;@song0ch3loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref86:
	db $04, $95, $05, $95, $04, $95, $05, $95, $04, $95, $05, $95, $04, $95, $05, $95
	db $41, $10
	dw @song0ref86
	db $41, $10
	dw @song0ref86
	db $41, $10
	dw @song0ref86
	db $41, $10
	dw @song0ref86
	db $41, $10
	dw @song0ref86
	db $41, $10
	dw @song0ref86
	db $41, $0f
	dw @song0ref86
	db $89, $05, $89
	db $41, $10
	dw @song0ref86
	db $41, $0f
	dw @song0ref86
	db $89, $05, $89
	db $41, $10
	dw @song0ref86
	db $41, $10
	dw @song0ref86
	db $42
	dw @song0ch4loop
@song0ch5:
@song0ch5loop:
	db $ff, $bf, $ff, $bf, $80, $33
@song0ref151:
	db $89, $00, $89, $33, $89, $00, $89, $33, $89, $00, $89
@song0ref162:
	db $33, $89, $00, $89, $35, $89, $00, $89, $35, $89, $00, $89, $35, $89, $00, $89, $35
	db $41, $0f
	dw @song0ref151
@song0ref182:
	db $33
@song0ref183:
	db $89, $00, $89, $31, $89, $00, $89, $31, $89, $00, $89, $31, $89, $00, $89, $31
	db $41, $0f
	dw @song0ref151
	db $41, $11
	dw @song0ref162
	db $41, $0f
	dw @song0ref151
	db $41, $11
	dw @song0ref182
@song0ref211:
	db $89, $00, $89, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $ff, $bf, $42
	dw @song0ch5loop
@song0ch6:
@song0ch6loop:
	db $ff, $bf, $ff, $bf, $80, $30, $89, $00, $89, $30, $89, $00, $89, $30, $89, $00, $89, $30
	db $41, $10
	dw @song0ref183
@song0ref251:
	db $89, $00, $89
@song0ref254:
	db $30, $89, $00, $89, $30, $89
@song0ref260:
	db $00, $89, $30, $89, $00, $89, $30, $89, $00, $89, $2e, $89, $00, $89, $2e, $89, $00, $89, $2e, $89, $00, $89, $2e
	db $41, $13
	dw @song0ref251
	db $31
	db $41, $0f
	dw @song0ref183
	db $41, $1d
	dw @song0ref254
	db $41, $0f
	dw @song0ref211
	db $42
	dw @song0ch6loop
;@song0ch7:
;@song0ch7loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch7loop
@song0ch8:
@song0ch8loop:
	db $8e, $2c, $a1, $2d, $a1, $2e, $95, $2d, $a1, $2e, $a1, $2f, $95, $2e, $a1, $2f, $a1, $30, $95, $2f, $a1, $30, $a1, $31
	db $95, $00, $ff, $bd, $ff, $bf, $ff, $bf, $ff, $bf, $30, $a1, $00, $89, $30, $a1, $00, $89, $2e, $a1, $00, $89, $2e, $a1
	db $41, $0e
	dw @song0ref260
	db $30, $89, $00, $e9, $33, $a1, $00, $89, $33, $a1, $00, $89, $35, $a1, $00, $89, $35, $a1, $00, $89, $33, $89, $00, $89
	db $33, $89, $00, $89, $31, $89, $00, $89, $33, $89, $00, $e9, $31, $dd, $35, $dd, $38, $ff, $bd, $42
	dw @song0ch8loop
@song0ch9:
@song0ch9loop:
	db $8e, $30, $a1, $31, $a1, $32, $95, $31, $a1, $32, $a1, $33, $95, $32, $a1, $33, $a1, $34, $95, $33, $a1, $34, $a1, $35
	db $95, $00, $ff, $bd, $ff, $bf, $ff, $bf, $ff, $bf, $2c, $a1, $00, $89, $2c, $a1, $00, $89, $2a, $a1, $00, $89, $2a, $a1
	db $00, $89, $2c, $89, $00, $89, $2c, $89, $00, $89, $2a, $89, $00, $89, $2c, $89, $00, $e9, $30, $a1, $00, $89, $30, $a1
	db $00, $89, $31, $a1, $00, $89, $31, $a1
	db $41, $0e
	dw @song0ref260
	db $30, $89, $00, $e9, $2a, $dd, $2e, $dd, $31, $ff, $bd, $42
	dw @song0ch9loop
@song0ch10:
@song0ch10loop:
	db $8e, $3c, $a1, $3d, $a1, $3e, $95, $3d, $a1, $3e, $a1, $3f, $95, $3e, $a1, $3f, $a1, $40, $4c, $95, $3f, $a1, $40, $4c
	db $a1, $40, $4d, $95, $00, $95, $8a
@song0ref534:
	db $30, $a1, $00, $89, $30, $89, $00, $89, $31, $95, $00, $89, $33, $95, $00, $89, $35, $95, $33, $89, $00, $89, $33, $89
	db $00, $89, $33, $89, $00, $89, $30, $89, $00, $89, $31, $95, $00, $89, $2e, $a1, $00, $95, $00, $95
	db $41, $2a
	dw @song0ref534
	db $ff, $bf, $f7, $82, $31, $89, $33, $89, $30, $95, $2c, $95, $00, $ff, $bd, $f7, $31, $89, $33, $89, $30, $95, $2c, $95
	db $00, $ff, $bd, $ff, $bf, $42
	dw @song0ch10loop
@song0ch11:
@song0ch11loop:
	db $ff, $bf, $ff, $bf, $97, $8c
	db $41, $2a
	dw @song0ref534
	db $97
	db $41, $2a
	dw @song0ref534
	db $8b, $88
@song0ref629:
	db $3c, $a1, $38, $89, $00, $89, $33, $89, $00, $89, $36, $89, $00, $89, $35, $89, $00, $89, $36, $89, $38, $95, $00, $89
	db $8b, $3c, $a1, $38, $89, $00, $89, $33, $89, $00, $89, $36, $95, $00, $c5, $8b
	db $41, $27
	dw @song0ref629
	db $ff, $bf, $ff, $bf, $42
	dw @song0ch11loop
@song0ch12:
@song0ch12loop:
	db $ff, $bf, $ff, $bf, $84
@song0ref685:
	db $20, $89, $00, $89, $20, $89, $00, $89, $1b, $89, $00, $89, $1b, $89, $00, $89, $1e, $89, $00, $89, $1e, $89, $00, $89
	db $1d, $89, $00, $89, $1d, $89, $00, $89
	db $41, $20
	dw @song0ref685
	db $41, $20
	dw @song0ref685
	db $41, $20
	dw @song0ref685
	db $ff, $bf, $f7, $25, $89, $27, $89, $24, $95, $20, $95, $00, $ff, $bd, $f7, $25, $89, $27, $89, $24, $95, $20, $95, $86
	db $12, $dd, $16, $dd, $19, $ff, $bd, $42
	dw @song0ch12loop
;@song0ch13:
;@song0ch13loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch13loop
;@song0ch14:
;@song0ch14loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch14loop
;@song0ch15:
;@song0ch15loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch15loop
;@song0ch16:
;@song0ch16loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch16loop
;@song0ch17:
;@song0ch17loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch17loop
;@song0ch18:
;@song0ch18loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch18loop
;@song0ch19:
;@song0ch19loop:
;	db $41, $18
;	dw @song0ref44
;	db $42
;	dw @song0ch19loop
