; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

music_data_15_chaos_emerald:
	db 1
	dw @instruments
	dw @instruments_exp
	dw @samples-4
;	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,@song0ch5,@song0ch6,@song0ch7,@song0ch8,@song0ch9,@song0ch10,@song0ch11,@song0ch12,@song0ch13,@song0ch14,@song0ch15,@song0ch16,@song0ch17,@song0ch18,@song0ch19 ; 00 : 15 - Chaos Emerald

	dw 0 ;@song0ch0 ; 2a03 sq1
	dw 0 ;@song0ch1 ; 2a03 sq2
	dw 0 ;@song0ch2 ; triangle
	dw 0 ;@song0ch3 ; noise
	dw 0 ;@song0ch4 ; dpcm
	dw @song0ch5 ; epsm sq1
	dw @song0ch6 ; epsm sq1
	dw 0 ;@song0ch7 ; epsm sq2
	dw @song0ch8 ; epsm fm1
        dw @song0ch9 ; epsm fm2	
	dw @song0ch10 ; epsm fm3
	dw @song0ch11 ; epsm fm4
	dw @song0ch12 ; epsm fm5
	dw 0 ;@song0ch13 ; epsm fm6
	dw 0 ;@song0ch14 epsm
	dw 0 ;@song0ch15 epsm
	dw 0 ;@song0ch16 epsm
	dw 0 ;@song0ch17 epsm
	dw 0 ;@song0ch18 epsm
        dw 0 ;@song0ch19 epsm

	db <(@tempo_env_1_mid), >(@tempo_env_1_mid), 0, 0

@instruments:

@instruments_exp:
	dw @env3, @env5, @env0 ; 00 : 1 Short Soft
	dw @env7, @env5
	dw @instrument_epsm_extra_patch0
	db $04,$c0,$00,$20+4
	dw @env2, @env5, @env0 ; 01 : Chaos 1
	dw @env7, @env5
	dw @instrument_epsm_extra_patch1
	db $04,$c0,$35,$23+4
	dw @env2, @env5, @env0 ; 02 : Chaos 2
	dw @env7, @env5
	dw @instrument_epsm_extra_patch2
	db $04,$c0,$35,$23+4
	dw @env2, @env5, @env0 ; 03 : Chaos 3
	dw @env7, @env5
	dw @instrument_epsm_extra_patch3
	db $3c,$c0,$31,$1a+4

@instrument_epsm_extra_patch0:
	db $1f,$00,$00,$07,$00,$00,$00+4,$1f,$00,$00,$07,$00,$00,$20+4,$1f,$00,$00,$07,$00,$00,$00+4,$1f,$00,$00,$07,$00,$00
@instrument_epsm_extra_patch1:
	db $1f,$07,$00,$1f,$00,$72,$1c+4,$1f,$0a,$0b,$0f,$00,$54,$1d+4,$1f,$07,$00,$1f,$00,$46,$08+4,$1f,$0d,$0b,$0f,$00,$00
@instrument_epsm_extra_patch2:
	db $1f,$07,$00,$1f,$00,$72,$1b+4,$1f,$0a,$0b,$0f,$00,$54,$1d+4,$1f,$07,$00,$1f,$00,$46,$07+4,$1f,$0d,$0b,$0f,$00,$00
@instrument_epsm_extra_patch3:
	db $52,$08,$04,$10,$00,$52,$16+4,$53,$00,$00,$07,$00,$50,$16+4,$52,$08,$04,$10,$00,$30,$16+4,$53,$00,$00,$07,$00,$00

@env0:
	db $00,$c0,$7f,$00,$02
@env1:
	db $c1,$c0,$00,$01
@env2:
	db $00,$cf,$7f,$00,$02
@env3:
	db $00,$cb,$cc,$02,$cb,$cb,$ca,$ca,$c9,$00,$08
@env4:
	db $bf,$bf,$c0,$00,$02
@env5:
	db $c0,$7f,$00,$01
@env6:
	db $7f,$00,$00
@env7:
	db $c8,$7f,$00,$00

@samples:

@tempo_env_1_mid:
	db $03,$05,$80

;@song0ch0:
;	db $ff, $ff, $e7
;@song0ch0loop:
;	db $00, $42
;	dw @song0ch0loop
;@song0ch1:
;	db $ff, $ff, $e7
;@song0ch1loop:
;	db $00, $42
;	dw @song0ch1loop
;@song0ch2:
;	db $ff, $ff, $e7
;@song0ch2loop:
;	db $00, $42
;	dw @song0ch2loop
;@song0ch3:
;	db $ff, $ff, $e7
;@song0ch3loop:
;	db $00, $42
;	dw @song0ch3loop
;@song0ch4:
;	db $ff, $ff, $e7
;@song0ch4loop:
;	db $00, $42
;	dw @song0ch4loop
@song0ch5:
	db $f1, $7d
@song0ref43:
	db $80
@song0ref44:
	db $40, $50, $8b, $40, $4e, $8b, $40, $4d, $8b, $3f, $8b, $7c
	db $41, $08
	dw @song0ref44
	db $7b
	db $41, $08
	dw @song0ref44
	db $7a
	db $41, $08
	dw @song0ref44
	db $00, $93
@song0ch5loop:
	db $00, $42
	dw @song0ch5loop
@song0ch6:
	db $f9, $7a
	db $41, $08
	dw @song0ref43
	db $79
	db $41, $08
	dw @song0ref44
	db $78
	db $41, $08
	dw @song0ref44
	db $77, $40, $50, $8b, $40, $4e, $8b, $40, $4d, $8b, $3f, $83, $00, $93
@song0ch6loop:
	db $00, $42
	dw @song0ch6loop
;@song0ch7:
;	db $ff, $ff, $e7
;@song0ch7loop:
;	db $00, $42
;	dw @song0ch7loop
@song0ch8:
	db $82
@song0ref115:
	db $29, $89, $2c, $8b, $31, $8b, $35, $9b, $31, $99, $38, $e3, $5a, $ff, $87, $00, $93
@song0ch8loop:
	db $00, $42
	dw @song0ch8loop
@song0ch9:
	db $82, $25, $89, $29, $8b, $2c, $8b, $31, $9b, $2e, $99, $4d, $fc, $33, $e3, $4d, $00, $5a, $ff, $87, $00, $93
@song0ch9loop:
	db $00, $42
	dw @song0ch9loop
@song0ch10:
	db $84
	db $41, $11
	dw @song0ref115
@song0ch10loop:
	db $00, $42
	dw @song0ch10loop
@song0ch11:
	db $86, $29, $97, $29, $8b, $2c, $8d, $5a, $8b, $2c, $8b, $5a, $8b, $31, $e3, $5a, $ff, $87, $00, $93
@song0ch11loop:
	db $00, $42
	dw @song0ch11loop
@song0ch12:
	db $86, $31, $97, $5a, $31, $89, $5a, $35, $8b, $5a, $8d, $35, $89, $5a, $8d, $38, $e1, $5a, $ff, $87, $00, $93
	db $5b ; halt	
@song0ch12loop:
	db $00, $42
	dw @song0ch12loop
;@song0ch13:
;	db $86, $2c, $99, $2c, $8b, $31, $8b, $5a, $8d, $31, $89, $5a, $8d, $35, $e1, $5a, $ff, $87, $00, $93
;	db $5b ; halt
;@song0ch13loop:
;	db $00, $42
;	dw @song0ch13loop
;@song0ch14:
;	db $ff, $ff, $e7
;@song0ch14loop:
;	db $00, $42
;	dw @song0ch14loop
;@song0ch15:
;	db $ff, $ff, $e7
;@song0ch15loop:
;	db $00, $42
;	dw @song0ch15loop
;@song0ch16:
;	db $ff, $ff, $e7
;@song0ch16loop:
;	db $00, $42
;	dw @song0ch16loop
;@song0ch17:
;	db $ff, $ff, $e7
;@song0ch17loop:
;	db $00, $42
;	dw @song0ch17loop
;@song0ch18:
;	db $ff, $ff, $e7
;@song0ch18loop:
;	db $00, $42
;	dw @song0ch18loop
;@song0ch19:
;	db $ff, $ff, $e7
;@song0ch19loop:
;	db $00, $42
;	dw @song0ch19loop
